//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PBGeneratedMessage.h"

@class BaseResponse, NSMutableArray, NSString;

@interface AddOpenIMChatRoomMemberResp : PBGeneratedMessage
{
    unsigned int hasBaseResponse:1;
    unsigned int hasPopUpWording:1;
    BaseResponse *baseResponse;
    NSMutableArray *mutableMemberListList;
    NSString *popUpWording;
}

+ (id)parseFromData:(id)arg1;
@property(retain, nonatomic, setter=SetPopUpWording:) NSString *popUpWording; // @synthesize popUpWording;
@property(readonly, nonatomic) BOOL hasPopUpWording; // @synthesize hasPopUpWording;
@property(retain, nonatomic) NSMutableArray *mutableMemberListList; // @synthesize mutableMemberListList;
@property(retain, nonatomic, setter=SetBaseResponse:) BaseResponse *baseResponse; // @synthesize baseResponse;
@property(readonly, nonatomic) BOOL hasBaseResponse; // @synthesize hasBaseResponse;
- (void).cxx_destruct;
- (void)addMemberList:(id)arg1;
- (void)addMemberListFromArray:(id)arg1;
- (id)mergeFromCodedInputStream:(id)arg1;
- (int)serializedSize;
- (void)writeToCodedOutputStream:(id)arg1;
- (BOOL)isInitialized;
@property(retain, nonatomic) NSMutableArray *memberList; // @dynamic memberList;
- (id)memberListList;
- (id)init;

@end

