//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMViewController.h"

#import "WKNavigationDelegate.h"
#import "WKScriptMessageHandler.h"
#import "WKUIDelegate.h"
#import "WebViewGetA8KeyLogicDelegate.h"
#import "WebViewJSApiVerifyMgrDelegate.h"
#import "WebViewJSLogicDelegate.h"

@class MMOutlineButton, MMProgressView, MMTimer, MMToastView, MMWKWebView, NSMutableArray, NSMutableDictionary, NSString, NSTextField, NSView, WKWebViewConfiguration, WebViewDataItem, WebViewDataLogic, WebViewGetA8KeyLogic, WebViewJSApiVerifyMgr, WebViewJSLogic;

@interface BaseWebViewController : MMViewController <WKNavigationDelegate, WKUIDelegate, WKScriptMessageHandler, WebViewGetA8KeyLogicDelegate, WebViewJSLogicDelegate, WebViewJSApiVerifyMgrDelegate>
{
    BOOL _isInitial;
    MMWKWebView *_wkWebView;
    WebViewDataItem *_dataItem;
    id <BaseWebViewControllerDelegate> _delegate;
    NSView *_toolbarContanier;
    MMProgressView *_progressView;
    NSTextField *_hostLabel;
    NSView *_contentContainer;
    NSView *_errorContainer;
    NSTextField *_errorDesc;
    MMOutlineButton *_retryBtn;
    WebViewJSLogic *_webViewJSLogic;
    WKWebViewConfiguration *_configuration;
    WebViewGetA8KeyLogic *_getA8KeyLogic;
    WebViewJSApiVerifyMgr *_jsapiVerifyMgr;
    NSMutableDictionary *_jsInitInfo;
    WebViewDataLogic *_dataLogic;
    MMToastView *_toastView;
    MMTimer *_toastTimer;
    NSMutableArray *_arrRouteUrl;
}

@property(nonatomic) BOOL isInitial; // @synthesize isInitial=_isInitial;
@property(retain, nonatomic) NSMutableArray *arrRouteUrl; // @synthesize arrRouteUrl=_arrRouteUrl;
@property(retain, nonatomic) MMTimer *toastTimer; // @synthesize toastTimer=_toastTimer;
@property(retain, nonatomic) MMToastView *toastView; // @synthesize toastView=_toastView;
@property(retain, nonatomic) WebViewDataLogic *dataLogic; // @synthesize dataLogic=_dataLogic;
@property(retain, nonatomic) NSMutableDictionary *jsInitInfo; // @synthesize jsInitInfo=_jsInitInfo;
@property(retain, nonatomic) WebViewJSApiVerifyMgr *jsapiVerifyMgr; // @synthesize jsapiVerifyMgr=_jsapiVerifyMgr;
@property(retain, nonatomic) WebViewGetA8KeyLogic *getA8KeyLogic; // @synthesize getA8KeyLogic=_getA8KeyLogic;
@property(retain, nonatomic) WKWebViewConfiguration *configuration; // @synthesize configuration=_configuration;
@property(retain, nonatomic) WebViewJSLogic *webViewJSLogic; // @synthesize webViewJSLogic=_webViewJSLogic;
@property(retain, nonatomic) MMOutlineButton *retryBtn; // @synthesize retryBtn=_retryBtn;
@property(retain, nonatomic) NSTextField *errorDesc; // @synthesize errorDesc=_errorDesc;
@property(retain, nonatomic) NSView *errorContainer; // @synthesize errorContainer=_errorContainer;
@property(retain, nonatomic) NSView *contentContainer; // @synthesize contentContainer=_contentContainer;
@property(retain, nonatomic) NSTextField *hostLabel; // @synthesize hostLabel=_hostLabel;
@property(retain, nonatomic) MMProgressView *progressView; // @synthesize progressView=_progressView;
@property(retain, nonatomic) NSView *toolbarContanier; // @synthesize toolbarContanier=_toolbarContanier;
@property(nonatomic) __weak id <BaseWebViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) WebViewDataItem *dataItem; // @synthesize dataItem=_dataItem;
@property(retain, nonatomic) MMWKWebView *wkWebView; // @synthesize wkWebView=_wkWebView;
- (void).cxx_destruct;
- (id)handleGetRouteUrls;
- (void)handleHideOptionMenuEvent;
- (void)handleShowOptionMenuEvent;
- (void)handlePreVerifyJSAPI:(id)arg1 failHandleBlock:(CDUnknownBlockType)arg2;
- (void)handleCurrentMpInfoJSEventWithBrandName:(id)arg1;
- (void)handleCloseWindowJSEvent;
- (void)handleOpenExtraWebviewJSEventWithUrl:(id)arg1;
- (void)handleSendAppMessageJSEventWithData:(id)arg1;
- (void)handleJumpToBizProfileJSEventWithContact:(id)arg1;
- (void)handleBizChatJSEventWithContact:(id)arg1;
- (void)handleProfileJSEventWithUserName:(id)arg1;
- (void)handleAddContactJSEventWithContact:(id)arg1;
- (BOOL)shouldShowMenuItem:(id)arg1;
- (BOOL)shouldDisableMenuItem:(id)arg1;
- (void)disableMenuItemAction;
- (id)logicBaseWebViewController;
- (void)onCopy:(id)arg1;
- (void)onDomReady;
- (void)onPageStateChange:(id)arg1;
- (id)getAuthorizedMonitorEvents:(id)arg1;
- (void)webView:(id)arg1 didReceiveServerRedirectForProvisionalNavigation:(id)arg2;
- (void)webView:(id)arg1 decidePolicyForNavigationResponse:(id)arg2 decisionHandler:(CDUnknownBlockType)arg3;
- (void)webView:(id)arg1 decidePolicyForNavigationAction:(id)arg2 decisionHandler:(CDUnknownBlockType)arg3;
- (void)webView:(id)arg1 didFailNavigation:(id)arg2 withError:(id)arg3;
- (void)webView:(id)arg1 didFinishNavigation:(id)arg2;
- (void)webView:(id)arg1 didCommitNavigation:(id)arg2;
- (void)webView:(id)arg1 didFailProvisionalNavigation:(id)arg2 withError:(id)arg3;
- (void)webView:(id)arg1 didStartProvisionalNavigation:(id)arg2;
- (id)webView:(id)arg1 createWebViewWithConfiguration:(id)arg2 forNavigationAction:(id)arg3 windowFeatures:(id)arg4;
- (void)webView:(id)arg1 runJavaScriptTextInputPanelWithPrompt:(id)arg2 defaultText:(id)arg3 initiatedByFrame:(id)arg4 completionHandler:(CDUnknownBlockType)arg5;
- (void)webView:(id)arg1 runJavaScriptConfirmPanelWithMessage:(id)arg2 initiatedByFrame:(id)arg3 completionHandler:(CDUnknownBlockType)arg4;
- (void)webView:(id)arg1 runJavaScriptAlertPanelWithMessage:(id)arg2 initiatedByFrame:(id)arg3 completionHandler:(CDUnknownBlockType)arg4;
- (void)webView:(id)arg1 runOpenPanelWithParameters:(id)arg2 initiatedByFrame:(id)arg3 completionHandler:(CDUnknownBlockType)arg4;
- (void)userContentController:(id)arg1 didReceiveScriptMessage:(id)arg2;
- (id)getJSFunctionDef:(id)arg1;
- (unsigned int)currentGetA8KeyScene;
- (void)removeUrlPermissionForUrl:(id)arg1;
- (void)saveUrlPermission:(id)arg1 url:(id)arg2;
- (void)saveJSAPIPermissions:(id)arg1 url:(id)arg2;
- (void)onJsapiGetA8key:(BOOL)arg1 requestUrl:(id)arg2 requestHeaders:(id)arg3;
- (void)onJumpToURL:(id)arg1 withCustomerCookies:(id)arg2;
- (void)onJumpToBack;
- (void)onJumpToSafariWithUrl:(id)arg1;
- (void)getA8KeyDidFaildWithReason:(int)arg1;
- (void)getA8keyDidFinishedWithReason:(int)arg1 req:(id)arg2 resp:(id)arg3;
- (void)favoriteWithDefault;
- (void)favoriteWithData:(id)arg1;
- (void)forwardWithDefault;
- (void)forwardWithData:(id)arg1;
- (void)doShareWithDefault;
- (void)doShareWithData:(id)arg1;
- (void)shareWithAppScene:(id)arg1;
- (void)onCopyAction:(id)arg1;
- (void)onDomReadyAction;
- (void)onPageStateChangeAction:(id)arg1;
- (void)openBlankInWebView;
- (void)openInExternalBrowser;
- (void)copyUrl;
- (void)addToFavorites;
- (void)forwardDataField:(id)arg1 toUserNames:(id)arg2;
- (void)forwardFavoriteItem:(id)arg1 toUserNames:(id)arg2;
- (void)forwardMessage:(id)arg1 toUserNames:(id)arg2;
- (void)forwardMessageFromUserName:(id)arg1 toUserNames:(id)arg2 title:(id)arg3 url:(id)arg4 description:(id)arg5 thumbUrl:(id)arg6;
- (void)forwardContent;
- (void)refreshContent;
- (void)nextItem;
- (void)previousItem;
- (id)currentSourceIdWithUrl:(id)arg1;
- (void)onLoadFinish:(id)arg1;
- (id)currentMainDocumentURL;
- (void)updateCurrentA8KeyUrl:(id)arg1;
- (id)currentShareUrl;
- (id)currentWebViewWindow;
- (BOOL)shouldUpdateWebViewWindowTitle;
- (BOOL)shouldUpdateWebViewTitle;
- (void)saveMpTitle:(id)arg1 withUrl:(id)arg2;
- (void)updateWebViewTitle;
- (void)updateWebViewTitleWithStr:(id)arg1;
- (void)showWebViewTitleWithValue:(double)arg1;
- (void)showWebViewTitle:(BOOL)arg1;
- (id)currentAppName;
- (id)currentWebViewDesc;
- (id)currentWebViewWindowTitle;
- (id)currentWebViewTitle;
- (void)showHostLabelWithValue:(double)arg1;
- (id)currentHostText;
- (void)hideToastAnimation;
- (void)stopToastTimer;
- (void)showWebViewToastWithText:(id)arg1;
- (void)showNetworkErrorHint;
- (void)showNonNetworkErrorHint;
- (void)hideErrorHint;
- (void)recordArrRouteUrl:(id)arg1;
- (void)openInWebView:(id)arg1;
- (void)initJsInitInfo:(id)arg1;
- (void)showWebViewWithDataItem:(id)arg1 initialShowing:(BOOL)arg2;
- (void)showAlertSheetWithMessage:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)resetWebView:(BOOL)arg1;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (id)webViewUserScript;
- (void)setupWebView;
- (void)handleWeixinJumpScheme:(id)arg1;
- (void)updateMenuItems;
- (void)updateNavigation;
- (void)setupUIControls;
- (void)dealloc;
- (void)viewDidLoad;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

