//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class MMSessionInfo, NSString;

@protocol BrandSessionMgrExt <NSObject>
- (void)onDeleteBrandSession:(NSString *)arg1 withIndex:(unsigned long long)arg2;
- (void)onBrandSessionChanged:(MMSessionInfo *)arg1;
- (void)onBrandSessionsReoredered;
@end

