//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCopying.h"

@class NSString;

@interface CExtendInfoOfSystem : NSObject <NSCopying>
{
    int _m_newxmlType;
    unsigned long long _m_svrId;
    NSString *_m_content;
    NSString *_m_typeStr;
    NSString *_m_sessionId;
}

@property(retain, nonatomic) NSString *m_sessionId; // @synthesize m_sessionId=_m_sessionId;
@property(retain, nonatomic) NSString *m_typeStr; // @synthesize m_typeStr=_m_typeStr;
@property(retain, nonatomic) NSString *m_content; // @synthesize m_content=_m_content;
@property(nonatomic) unsigned long long m_svrId; // @synthesize m_svrId=_m_svrId;
@property(nonatomic) int m_newxmlType; // @synthesize m_newxmlType=_m_newxmlType;
- (void).cxx_destruct;
- (void)encodeMsgFieldToXML:(id)arg1;
- (void)parseMsgFieldFromXML:(id)arg1;
- (id)parseNewXMLType:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)dealloc;
- (id)init;

@end

