//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "IMessageDataExt.h"
#import "IMsgExtendOperation.h"
#import "NSCopying.h"

@class MessageData, NSMutableArray, NSString;

@interface CExtendInfoOfPushMail : NSObject <IMsgExtendOperation, IMessageDataExt, NSCopying>
{
    NSString *nsSender;
    NSString *nsSenderAddress;
    NSString *nsSubject;
    NSString *nsDigest;
    NSString *nsDate;
    NSString *nsWapLink;
    NSString *nsMailID;
    NSString *nsAccount;
    NSString *nsArgs;
    unsigned long long uiUin;
    BOOL bHasAttachment;
    NSMutableArray *arrToList;
    NSMutableArray *arrCCList;
    MessageData *m_refMessageData;
}

+ (void)CreateExtendInfoWithType:(unsigned int)arg1 retExtendInfo:(id *)arg2;
@property(nonatomic) MessageData *m_refMessageData; // @synthesize m_refMessageData;
@property(retain, nonatomic) NSMutableArray *arrCCList; // @synthesize arrCCList;
@property(retain, nonatomic) NSMutableArray *arrToList; // @synthesize arrToList;
@property(nonatomic) unsigned long long uiUin; // @synthesize uiUin;
@property(nonatomic) BOOL bHasAttachment; // @synthesize bHasAttachment;
@property(retain, nonatomic) NSString *nsArgs; // @synthesize nsArgs;
@property(retain, nonatomic) NSString *nsAccount; // @synthesize nsAccount;
@property(retain, nonatomic) NSString *nsMailID; // @synthesize nsMailID;
@property(retain, nonatomic) NSString *nsWapLink; // @synthesize nsWapLink;
@property(retain, nonatomic) NSString *nsDate; // @synthesize nsDate;
@property(retain, nonatomic) NSString *nsDigest; // @synthesize nsDigest;
@property(retain, nonatomic) NSString *nsSubject; // @synthesize nsSubject;
@property(retain, nonatomic) NSString *nsSenderAddress; // @synthesize nsSenderAddress;
@property(retain, nonatomic) NSString *nsSender; // @synthesize nsSender;
- (void).cxx_destruct;
- (void)parseMsgFieldFromXML;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

