//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMService.h"

#import "MMService.h"

@class GetContactLogic, NSLock, NSMutableDictionary, NSObject<OS_dispatch_queue>, NSString, WCContactDB;

@interface ContactStorage : MMService <MMService>
{
    WCContactDB *m_contactDB;
    unsigned int m_uLoadedType;
    GetContactLogic *_getContactLogic;
    GetContactLogic *_getStrangerLogic;
    NSLock *m_lock;
    NSMutableDictionary *m_dictContacts;
    BOOL m_hasClearData;
    BOOL _hasGetContactForAllFavContactsDone;
    NSObject<OS_dispatch_queue> *_getContactOnStartANewChatQueue;
    NSMutableDictionary *_dataDict;
}

+ (void)DeleteContactDatabase;
@property(retain, nonatomic) NSMutableDictionary *dataDict; // @synthesize dataDict=_dataDict;
@property(nonatomic) BOOL hasGetContactForAllFavContactsDone; // @synthesize hasGetContactForAllFavContactsDone=_hasGetContactForAllFavContactsDone;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *getContactOnStartANewChatQueue; // @synthesize getContactOnStartANewChatQueue=_getContactOnStartANewChatQueue;
- (void).cxx_destruct;
- (void)UpdateContactIfNeeded:(id)arg1;
- (void)saveCache;
- (void)loadCache;
- (id)getContactCache:(id)arg1;
- (id)GetAllFriendContacts;
- (BOOL)DeleteContactByUI:(id)arg1 ListType:(unsigned int)arg2;
- (BOOL)modifyContactTypeWithFlag:(unsigned int)arg1 setOpen:(BOOL)arg2 userName:(id)arg3 syncToServer:(BOOL)arg4;
- (BOOL)ModifyChatStatusNotifyOpen:(BOOL)arg1 withUserName:(id)arg2 syncToServer:(BOOL)arg3;
- (BOOL)ModifyIsFav:(BOOL)arg1 withUserName:(id)arg2 syncToServer:(BOOL)arg3;
- (BOOL)ModifyIsTop:(BOOL)arg1 withUserName:(id)arg2 syncToServer:(BOOL)arg3;
- (BOOL)ModifyRemarkWithUserName:(id)arg1 remark:(id)arg2 syncToServer:(BOOL)arg3;
- (BOOL)ModifyRemarkWithUserName:(id)arg1 remark:(id)arg2;
- (BOOL)updateContact:(id)arg1 withTagList:(id)arg2;
- (BOOL)UpdateLocalizedContact:(id)arg1;
- (id)GetAllFavContacts;
- (id)GetContactList:(unsigned int)arg1 ContactType:(unsigned int)arg2;
- (id)GetContactsWithUserNames:(id)arg1;
- (id)GetContactWithNickName:(id)arg1;
- (id)GetContact:(id)arg1;
- (id)GetSelfContact;
- (BOOL)IsFriendContact:(id)arg1;
- (BOOL)IsContactExistInCache:(id)arg1;
- (BOOL)IsContactExist:(id)arg1;
- (void)addLocalHardCodeContacts;
- (void)onServiceClearData;
- (void)onServiceInit;
- (id)init;
- (unsigned int)deleteOpenIMContactOplog:(id)arg1;
- (unsigned int)setOpenIMContactOplog:(id)arg1 favour:(BOOL)arg2;
- (unsigned int)setOpenIMContactOplog:(id)arg1 mute:(BOOL)arg2;
- (unsigned int)setOpenImContactOplog:(id)arg1 top:(BOOL)arg2;
- (unsigned int)setOpenImContactOplog:(id)arg1 black:(BOOL)arg2;
- (unsigned int)setOpenIMContactOplog:(id)arg1 remark:(id)arg2;
- (unsigned int)addOplogType:(unsigned int)arg1 Buffer:(id)arg2;
- (BOOL)addOpLog_ModifyBrandContact:(id)arg1 sync:(BOOL)arg2;
- (BOOL)isSkipContact:(id)arg1;
- (BOOL)addOpLog_DeleteChatContact:(id)arg1 sync:(BOOL)arg2;
- (BOOL)addOpLog_ModifyContact:(id)arg1 sync:(BOOL)arg2;
- (BOOL)addOpLog_ModifyContact:(id)arg1 addScene:(unsigned int)arg2 sync:(BOOL)arg3;
- (BOOL)addOpLog_ModifyContact:(id)arg1 withCardDescription:(id)arg2 sync:(BOOL)arg3;
- (void)storeContactToDBAndCache:(id)arg1;
- (BOOL)deleteContactByServer:(id)arg1;
- (BOOL)GetStrangerContactsFromSvr:(id)arg1;
- (BOOL)GetNormalContactsFromSvr:(id)arg1;
- (BOOL)ModifyAntispamTicket:(id)arg1 antispamTicket:(id)arg2;
- (BOOL)DeleteContactOnDelCmd:(id)arg1;
- (void)OnModStrangerContacts_Thread:(id)arg1;
- (void)OnModSingleContacts_Thread:(id)arg1;
- (void)onModifySelfContact:(id)arg1;
- (BOOL)updateBrandContact:(id)arg1;
- (id)GetAllBrandContacts;
- (void)notifyDeleteContactOnMainThread:(id)arg1;
- (void)notifyModifyContactsOnMainThread:(id)arg1;
- (void)notifyModifyStrangerContactsOnMainThread:(id)arg1;
- (id)getLocalHardCodeContact:(id)arg1;
- (id)addLocalHardCodeContact:(id)arg1;
- (BOOL)deleteContactInLocal:(id)arg1;
- (BOOL)loadContactsWithType:(unsigned int)arg1;
- (void)removeContactCache:(id)arg1;
- (void)setContactsCache:(id)arg1;
- (void)setContactCache:(id)arg1;
- (unsigned long long)contactCacheCount;
- (id)allKeysOfContactCache;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

