//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "AccountServiceExt.h"
#import "INewABTestMgrExt.h"

@class MMTimer, NSMutableDictionary, NSObject<OS_dispatch_queue>, NSString;

@interface CpuMonitor : NSObject <AccountServiceExt, INewABTestMgrExt>
{
    int m_min_total_cpu_usage;
    int m_continuous_times;
    int m_count;
    float m_tot_cpu;
    int m_higher_min_total_cpu_usage;
    int m_higher_continuous_times;
    int m_higher_count;
    float m_higher_tot_cpu;
    NSMutableDictionary *m_cpu_detail;
    NSMutableDictionary *m_higher_cpu_detail;
    int m_min_main_cpu_usage;
    int m_min_sub_cpu_usage;
    int m_cpu_report_period;
    int m_cpu_count;
    MMTimer *m_cpu_usage_timer;
    int m_cpu_check_period;
    unsigned int main_thread_id;
    NSObject<OS_dispatch_queue> *m_monitorQueue;
    int m_cpu_report_usage;
    int m_cpu_log_tot_usage;
}

- (void).cxx_destruct;
- (id)genCPUDetail:(id)arg1 count:(long long)arg2;
- (void)onModifyABTestItem:(id)arg1 bizId:(id)arg2 abTestItem:(id)arg3;
- (void)onUserLogout;
- (void)initParameters;
- (void)startTimer;
- (void)stopTimer;
- (void)cpuUsageReportIfNeed;
- (void)dealloc;
- (void)setupCpuMonitor;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

