//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "AccountServiceExt.h"

@class NSString;

@interface DiskMonitor : NSObject <AccountServiceExt>
{
    unsigned int _lastCheckDiskTimeStamp;
    unsigned long long _totalDiskSize;
    unsigned long long _freeSpaceLow;
    unsigned long long _freeSpaceLower;
    unsigned long long _freeSpaceLowest;
}

@property(nonatomic) unsigned int lastCheckDiskTimeStamp; // @synthesize lastCheckDiskTimeStamp=_lastCheckDiskTimeStamp;
@property(nonatomic) unsigned long long freeSpaceLowest; // @synthesize freeSpaceLowest=_freeSpaceLowest;
@property(nonatomic) unsigned long long freeSpaceLower; // @synthesize freeSpaceLower=_freeSpaceLower;
@property(nonatomic) unsigned long long freeSpaceLow; // @synthesize freeSpaceLow=_freeSpaceLow;
@property(nonatomic) unsigned long long totalDiskSize; // @synthesize totalDiskSize=_totalDiskSize;
- (void)FFAddRecvFavZZ:(BOOL)arg1;
- (unsigned long long)getFreeDiskSpace;
- (void)checkFreeDiskspace;
- (void)onDelayCheckoutFreeSpace;
- (BOOL)isAllowDiskDetect;
- (void)dealloc;
- (void)setup;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

