//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMMessageCellView.h"

@class CAShapeLayer, NSTextField;

@interface DividerMessageCellView : MMMessageCellView
{
    NSTextField *_dividerTextField;
    CAShapeLayer *_strokeLayer;
}

+ (double)cellHeightWithMessage:(id)arg1 constrainedToWidth:(double)arg2;
@property(retain, nonatomic) CAShapeLayer *strokeLayer; // @synthesize strokeLayer=_strokeLayer;
@property(retain, nonatomic) NSTextField *dividerTextField; // @synthesize dividerTextField=_dividerTextField;
- (void).cxx_destruct;
- (BOOL)allowMultipleSelect;
- (void)setChoosable:(BOOL)arg1;
- (BOOL)showsContextMenuButton;
- (void)mouseDragged:(id)arg1;
- (void)resizeSubviewsWithOldSize:(struct CGSize)arg1;
- (void)updateDivider;
- (void)populateWithMessage:(id)arg1;
- (void)handleNewTextSize;
- (void)prepareForReuse;
- (id)initWithFrame:(struct CGRect)arg1;

@end

