//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "MMCGIDelegate.h"

@class NSData, NSString;

@interface EmoticonUploadCGI : NSObject <MMCGIDelegate>
{
    BOOL _isUploading;
    unsigned int _m_sessionId;
    unsigned int _m_totalLen;
    unsigned int _m_startPos;
    id <EmoticonUploadCGIDelegate> _delegate;
    NSString *_m_md5;
    NSString *_m_filePath;
    NSData *_m_data;
}

@property(retain, nonatomic) NSData *m_data; // @synthesize m_data=_m_data;
@property(copy, nonatomic) NSString *m_filePath; // @synthesize m_filePath=_m_filePath;
@property(copy, nonatomic) NSString *m_md5; // @synthesize m_md5=_m_md5;
@property(nonatomic) unsigned int m_startPos; // @synthesize m_startPos=_m_startPos;
@property(nonatomic) unsigned int m_totalLen; // @synthesize m_totalLen=_m_totalLen;
@property(nonatomic) unsigned int m_sessionId; // @synthesize m_sessionId=_m_sessionId;
@property(nonatomic) BOOL isUploading; // @synthesize isUploading=_isUploading;
@property(nonatomic) __weak id <EmoticonUploadCGIDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)OnResponseCGI:(BOOL)arg1 sessionId:(unsigned int)arg2 cgiWrap:(id)arg3;
- (void)stopUploadEmoticon;
- (void)sendUploadEmojiRequest;
- (void)startUploadEmoticon;
- (id)initWithMD5:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

