//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "MMCGIDelegate.h"

@class NSString;

@interface ExptLogic : NSObject <MMCGIDelegate>
{
    unsigned int _lastUpdateTime;
    unsigned int _interval;
}

+ (id)exptPath:(id)arg1;
@property(nonatomic) unsigned int interval; // @synthesize interval=_interval;
@property(nonatomic) unsigned int lastUpdateTime; // @synthesize lastUpdateTime=_lastUpdateTime;
- (BOOL)saveTimeToFile:(unsigned int)arg1 fileName:(id)arg2;
- (unsigned int)getTimeFromFile:(id)arg1;
- (unsigned int)getExptInterval;
- (void)noteGetExptIntervalSec:(unsigned int)arg1;
- (unsigned int)getLastGetExptTime;
- (void)noteGetExptTime:(unsigned int)arg1;
- (void)onReceNewXmlMsg:(id)arg1 type:(id)arg2 messageData:(id)arg3;
- (void)OnResponseCGI:(BOOL)arg1 sessionId:(unsigned int)arg2 cgiWrap:(id)arg3;
- (void)getSvrExpt;
- (void)checkToGetSvrExpt;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

