//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSWindowController.h"

@class NSTextField;

@interface ExptDebugWindowController : NSWindowController
{
    NSTextField *_keyInput;
    NSTextField *_defaultInput;
    NSTextField *_valueInput;
}

@property __weak NSTextField *valueInput; // @synthesize valueInput=_valueInput;
@property __weak NSTextField *defaultInput; // @synthesize defaultInput=_defaultInput;
@property __weak NSTextField *keyInput; // @synthesize keyInput=_keyInput;
- (void).cxx_destruct;
- (void)onClickGetAllBtn:(id)arg1;
- (void)onClickGetValueBtn:(id)arg1;
- (void)windowDidLoad;
- (id)windowNibName;

@end

