//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMService.h"

#import "AccountServiceExt.h"
#import "IExptLogicCallback.h"
#import "IMessageExt.h"
#import "MMService.h"

@class ExptLogic, NSMutableDictionary, NSString;

@interface ExptService : MMService <IExptLogicCallback, AccountServiceExt, IMessageExt, MMService>
{
    BOOL _hadLoadedExpt;
    NSMutableDictionary *_exptItemMap;
    NSMutableDictionary *_exptKeyMap;
    ExptLogic *_exptLogic;
}

@property(retain, nonatomic) ExptLogic *exptLogic; // @synthesize exptLogic=_exptLogic;
@property(nonatomic) BOOL hadLoadedExpt; // @synthesize hadLoadedExpt=_hadLoadedExpt;
@property(retain, nonatomic) NSMutableDictionary *exptKeyMap; // @synthesize exptKeyMap=_exptKeyMap;
@property(retain, nonatomic) NSMutableDictionary *exptItemMap; // @synthesize exptItemMap=_exptItemMap;
- (void).cxx_destruct;
- (id)mmExptPath:(id)arg1;
- (BOOL)checkNeedDelAllExpt:(unsigned int)arg1;
- (void)onGotSvrExptList:(id)arg1 deleteExptIds:(id)arg2 andExptFlag:(unsigned int)arg3;
- (void)getLocalExptList:(id)arg1;
- (void)tryToSaveExpt;
- (void)tryToLoadExpt;
- (void)onGetNewXmlMsg:(id)arg1 type:(id)arg2 msgData:(id)arg3;
- (void)FFAddRecvFavZZ:(BOOL)arg1;
- (void)getSvrExpt;
- (void)dealloc;
- (void)onServiceEnterForeground;
- (void)onServiceReloadData;
- (void)onServiceClearData;
- (void)onServiceInit;
- (id)getAllExpt;
- (id)getExpt:(id)arg1 withStringDefault:(id)arg2;
- (id)getExptItemWith:(id)arg1;
- (BOOL)getExpt:(id)arg1 withBoolDefault:(BOOL)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

