//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PBGeneratedMessage.h"

@class NSString;

@interface ExptItem : PBGeneratedMessage
{
    unsigned int hasExptId:1;
    unsigned int hasGroupId:1;
    unsigned int hasExptSequence:1;
    unsigned int hasExptContent:1;
    unsigned int hasExptType:1;
    unsigned int exptId;
    unsigned int groupId;
    unsigned int exptSequence;
    unsigned int exptType;
    NSString *exptContent;
}

+ (id)parseFromData:(id)arg1;
@property(nonatomic, setter=SetExptType:) unsigned int exptType; // @synthesize exptType;
@property(readonly, nonatomic) BOOL hasExptType; // @synthesize hasExptType;
@property(retain, nonatomic, setter=SetExptContent:) NSString *exptContent; // @synthesize exptContent;
@property(readonly, nonatomic) BOOL hasExptContent; // @synthesize hasExptContent;
@property(nonatomic, setter=SetExptSequence:) unsigned int exptSequence; // @synthesize exptSequence;
@property(readonly, nonatomic) BOOL hasExptSequence; // @synthesize hasExptSequence;
@property(nonatomic, setter=SetGroupId:) unsigned int groupId; // @synthesize groupId;
@property(readonly, nonatomic) BOOL hasGroupId; // @synthesize hasGroupId;
@property(nonatomic, setter=SetExptId:) unsigned int exptId; // @synthesize exptId;
@property(readonly, nonatomic) BOOL hasExptId; // @synthesize hasExptId;
- (void).cxx_destruct;
- (id)mergeFromCodedInputStream:(id)arg1;
- (int)serializedSize;
- (void)writeToCodedOutputStream:(id)arg1;
- (BOOL)isInitialized;
- (id)init;

@end

