//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "MMCGIDelegate.h"

@class GetContactChecker, NSLock, NSMutableDictionary, NSMutableSet, NSString;

@interface GetContactLogic : NSObject <MMCGIDelegate>
{
    unsigned int _getContactType;
    BOOL _isGetContacting;
    NSMutableSet *_waitGetUsrnameSet;
    NSMutableDictionary *_dictGetingUsrname;
    GetContactChecker *_contactChecker;
    NSLock *_lock;
    BOOL _isStop;
    unsigned int _maxGetContactPerTime;
}

- (void).cxx_destruct;
- (void)checkupGettingUserName:(id)arg1;
- (void)OnResponseCGI:(BOOL)arg1 sessionId:(unsigned int)arg2 cgiWrap:(id)arg3;
- (id)handleOpenIMChatRoomContactResponse:(id)arg1;
- (id)getOpenIMChatRoomContactRequest:(id)arg1;
- (id)handleOpenIMContactResponse:(id)arg1;
- (id)getOpenIMGetContactRequest:(id)arg1;
- (id)handleContactResponse:(id)arg1;
- (id)getNormalGetContactRequest:(id)arg1;
- (BOOL)sendGetContactsReq;
- (BOOL)addUsrnamesToGettingQueue:(id)arg1;
- (void)stop;
- (void)dealloc;
- (id)initWithType:(unsigned int)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

