//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PBGeneratedMessage.h"

@class BaseRequest, NSMutableArray;

@interface GetExptRequest : PBGeneratedMessage
{
    unsigned int hasBaseRequest:1;
    unsigned int hasLastGetSvrSecond:1;
    unsigned int hasScene:1;
    unsigned int lastGetSvrSecond;
    unsigned int scene;
    BaseRequest *baseRequest;
    NSMutableArray *mutableLocalExptListList;
}

+ (id)parseFromData:(id)arg1;
@property(retain, nonatomic) NSMutableArray *mutableLocalExptListList; // @synthesize mutableLocalExptListList;
@property(nonatomic, setter=SetScene:) unsigned int scene; // @synthesize scene;
@property(readonly, nonatomic) BOOL hasScene; // @synthesize hasScene;
@property(nonatomic, setter=SetLastGetSvrSecond:) unsigned int lastGetSvrSecond; // @synthesize lastGetSvrSecond;
@property(readonly, nonatomic) BOOL hasLastGetSvrSecond; // @synthesize hasLastGetSvrSecond;
@property(retain, nonatomic, setter=SetBaseRequest:) BaseRequest *baseRequest; // @synthesize baseRequest;
@property(readonly, nonatomic) BOOL hasBaseRequest; // @synthesize hasBaseRequest;
- (void).cxx_destruct;
- (void)addLocalExptList:(id)arg1;
- (void)addLocalExptListFromArray:(id)arg1;
- (id)mergeFromCodedInputStream:(id)arg1;
- (int)serializedSize;
- (void)writeToCodedOutputStream:(id)arg1;
- (BOOL)isInitialized;
@property(retain, nonatomic) NSMutableArray *localExptList; // @dynamic localExptList;
- (id)localExptListList;
- (id)init;

@end

