//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMService.h"

#import "MMService.h"

@class GetContactLogic, GroupDB, MMCache, NSMutableArray, NSMutableDictionary, NSRecursiveLock, NSString;

@interface GroupStorage : MMService <MMService>
{
    GroupDB *m_groupDB;
    unsigned int m_uLoadedType;
    GetContactLogic *_getContactLogic;
    NSMutableDictionary *m_dictGroupContacts;
    MMCache *m_groupMembersCache;
    BOOL m_hasClearData;
    NSRecursiveLock *_m_groupLock;
    NSMutableArray *_m_getMemberDetailTasks;
    NSMutableArray *_m_getChatRoomInfoTasks;
}

+ (void)DeleteGroupDatabase;
@property(retain, nonatomic) NSMutableArray *m_getChatRoomInfoTasks; // @synthesize m_getChatRoomInfoTasks=_m_getChatRoomInfoTasks;
@property(retain, nonatomic) NSMutableArray *m_getMemberDetailTasks; // @synthesize m_getMemberDetailTasks=_m_getMemberDetailTasks;
@property(retain, nonatomic) NSRecursiveLock *m_groupLock; // @synthesize m_groupLock=_m_groupLock;
- (void).cxx_destruct;
- (void)SetGroupDetailWithUserName:(id)arg1 content:(id)arg2 withCompletion:(CDUnknownBlockType)arg3;
- (void)GetGroupDetailWithContact:(id)arg1 withCompletion:(CDUnknownBlockType)arg2;
- (void)UpdateGroupMemberDetailIfNeeded:(id)arg1 withCompletion:(CDUnknownBlockType)arg2;
- (id)GetAllGroups;
- (BOOL)GetGroupContactsFromSvr:(id)arg1;
- (BOOL)DeleteGroupContactByUI:(id)arg1 ListType:(unsigned int)arg2;
- (void)ModifyGroupContact:(id)arg1 withCompletion:(CDUnknownBlockType)arg2;
- (void)ModifyGroupMembers:(id)arg1 onlyInsertNew:(BOOL)arg2;
- (void)ModifyOpenIMGroupMember:(id)arg1;
- (void)SetGroupChatAnnouncementWithGroupUserName:(id)arg1 announceContent:(id)arg2 withCompletion:(CDUnknownBlockType)arg3;
- (void)GetGroupChatAnnouncementWithGroupUserName:(id)arg1 withCompletion:(CDUnknownBlockType)arg2;
- (void)UpdateGroupChatMemberDetailWithGroupUserName:(id)arg1 withCompletion:(CDUnknownBlockType)arg2;
- (BOOL)ModifyShowInAddressBook:(BOOL)arg1 withGroupUsrName:(id)arg2;
- (BOOL)ModifyShouldShowGroupDisplayName:(BOOL)arg1 withGroupUsrName:(id)arg2 selfUsrName:(id)arg3 syncToServer:(BOOL)arg4;
- (BOOL)ModifyChatStatusNotifyOpen:(BOOL)arg1 withGroupUserName:(id)arg2 syncToServer:(BOOL)arg3;
- (BOOL)ModifyIsTop:(BOOL)arg1 withGroupUsrName:(id)arg2 syncToServer:(BOOL)arg3;
- (BOOL)ModifyGroupChatName:(id)arg1 withGroupUserName:(id)arg2;
- (unsigned long long)GetGroupMemberCountWithGroupContact:(id)arg1;
- (unsigned long long)GetGroupMemberCountWithGroupUserName:(id)arg1;
- (id)GetGroupMemberListWithGroupContact:(id)arg1 limit:(unsigned int)arg2;
- (id)GetGroupMemberListWithGroupContact:(id)arg1;
- (id)GetGroupMemberListWithGroupUserName:(id)arg1 limit:(unsigned int)arg2;
- (id)GetGroupMemberListWithGroupUserName:(id)arg1;
- (id)GetGroupContactList:(unsigned int)arg1 ContactType:(unsigned int)arg2;
- (id)GetGroupMemberContact:(id)arg1;
- (BOOL)IsGroupMemberContactExist:(id)arg1;
- (id)GetGroupContactsWithUserNames:(id)arg1;
- (id)GetGroupContact:(id)arg1;
- (BOOL)IsGroupContactExist:(id)arg1;
- (id)GetGroupContactWithNickName:(id)arg1;
- (BOOL)QuitGroup:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (BOOL)DeleteGroupMemberWithGroupUserName:(id)arg1 memberUserNameList:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (BOOL)InviteGroupMemberWithChatRoomName:(id)arg1 memberList:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (BOOL)AddGroupMembers:(id)arg1 withGroupUserName:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (void)CreateGroupChatWithTopic:(id)arg1 groupMembers:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (void)clearGroupContacts;
- (void)onServiceClearData;
- (void)onServiceInit;
- (void)dealloc;
- (id)init;
- (BOOL)UIQuitGroup:(id)arg1;
- (BOOL)UIQuitGroup:(id)arg1 withConfirm:(BOOL)arg2 completion:(CDUnknownBlockType)arg3;
- (int)handleCreateOpenIMChatRoomResponse:(id)arg1;
- (void)createOpenIMChatRoom:(id)arg1 WithMemberList:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (int)handleCreateNormalChatRoomResponse:(id)arg1;
- (void)createNormalChatRoom:(id)arg1 WithMemberList:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (void)UICreateGroup:(id)arg1 withMemberList:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (void)deleteMemberFromOpenIMChatRoom:(id)arg1 withMemberList:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (void)deleteMemberFromChatRoom:(id)arg1 withMemberList:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (BOOL)UIDeleteGroupMember:(id)arg1 withMemberList:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (void)inviteNormalGroupMemberWithChatRoomName:(id)arg1 memberList:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (void)inviteOpenIMMemberWithChatRoomName:(id)arg1 memberList:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (BOOL)UIInviteGroupMemberWithChatRoomName:(id)arg1 memberList:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (void)addGroupMemberToChatRoom:(id)arg1 withMemberList:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (void)addGroupMemberToOpenIMChatRoom:(id)arg1 withMemberList:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (BOOL)UIAddGroupMember:(id)arg1 withMemberList:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (id)contactWithOpenImMemberResp:(id)arg1;
- (id)contactWithMemberResp:(id)arg1;
- (void)addChatMemberNeedVerifyMsg:(id)arg1 ContactList:(id)arg2;
- (void)addCreateMsg:(id)arg1 ContactList:(id)arg2;
- (void)getOpenIMChatRoomMemberDetailWithUserName:(id)arg1 withCompletion:(CDUnknownBlockType)arg2;
- (void)getNormalChatRoomMemberDetailWithUserName:(id)arg1 withCompletion:(CDUnknownBlockType)arg2;
- (void)getChatroomMemberDetailWithUserName:(id)arg1 withCompletion:(CDUnknownBlockType)arg2;
- (void)setOpenIMChatRoomAnnouncementWithUserName:(id)arg1 announceContent:(id)arg2 withCompletion:(CDUnknownBlockType)arg3;
- (void)setNormalChatRoomAnnouncementWithUserName:(id)arg1 announceContent:(id)arg2 withCompletion:(CDUnknownBlockType)arg3;
- (void)setChatRoomAnnouncementWithUserName:(id)arg1 announceContent:(id)arg2 withCompletion:(CDUnknownBlockType)arg3;
- (void)getChatRoomAnnouncementWithUserName:(id)arg1 withCompletion:(CDUnknownBlockType)arg2;
- (BOOL)DeleteGroupContactOnDelCmd:(id)arg1;
- (void)OnModGroupMemberContacts_Thread:(id)arg1;
- (void)OnModGroupContacts_Thread:(id)arg1;
- (BOOL)quitOpenIMGroupChatRoom:(id)arg1 sync:(BOOL)arg2;
- (BOOL)addOpenIMChatRoomToContactBook:(id)arg1 inContactBook:(BOOL)arg2 sync:(BOOL)arg3;
- (BOOL)addOpenIMChatRoomShowDislayName:(id)arg1 show:(BOOL)arg2 sync:(BOOL)arg3;
- (BOOL)addOpenIMOplogChatRoom:(id)arg1 announcement:(id)arg2 sync:(BOOL)arg3;
- (BOOL)addOpenIMOplogChatRoom:(id)arg1 withTopic:(id)arg2 sync:(BOOL)arg3;
- (BOOL)addOpenIMOplogChatRoom:(id)arg1 top:(BOOL)arg2 sync:(BOOL)arg3;
- (BOOL)addOpenIMOplogChatRoom:(id)arg1 mute:(BOOL)arg2 sync:(BOOL)arg3;
- (BOOL)addOplog_ModifyShowDisplayNameWithGroupChatUserName:(id)arg1 usrName:(id)arg2 flag:(unsigned int)arg3 open:(BOOL)arg4 sync:(BOOL)arg5;
- (BOOL)addOplog_ModifyNotifyStatus:(id)arg1 withStatus:(unsigned int)arg2 sync:(BOOL)arg3;
- (unsigned int)ChatNotifyC2S:(unsigned int)arg1;
- (BOOL)addOpLog_SetGroupTopic:(id)arg1 withTopic:(id)arg2 NeedSync:(BOOL)arg3;
- (BOOL)addOplog_QuitGroup:(id)arg1 withUsrName:(id)arg2 NeedSync:(BOOL)arg3;
- (BOOL)addOpLog_ModifyGroupContact:(id)arg1 addScene:(unsigned int)arg2 sync:(BOOL)arg3;
- (BOOL)addOpLog_ModifyGroupContact:(id)arg1 sync:(BOOL)arg2;
- (void)notifyModifyGroupMemberContactOnMainThread:(id)arg1;
- (void)notifyModifyGroupContactsOnMainThread:(id)arg1;
- (void)notifyDeleteGroupContactOnMainThread:(id)arg1;
- (BOOL)deleteMemberContactInLocal:(id)arg1;
- (BOOL)deleteGroupContactInLocal:(id)arg1;
- (void)deleteGroupMember:(id)arg1 removedMemberNameList:(id)arg2;
- (void)addOrModifyGroupContactMembers:(id)arg1;
- (void)addOrModifyGroupContact:(id)arg1 arrMembersList:(id)arg2;
- (BOOL)loadGroupContactsWithType:(unsigned int)arg1;
- (void)removeGroupMemberContactCache:(id)arg1;
- (void)setGroupMemberContactsCache:(id)arg1;
- (void)setGroupMemberContactCache:(id)arg1;
- (id)getGroupMemberContactCache:(id)arg1;
- (void)removeGroupContactCache:(id)arg1;
- (void)setGroupContactsCache:(id)arg1;
- (void)setGroupContactCache:(id)arg1;
- (id)getGroupContactCacheKeys;
- (unsigned long long)getGroupContactCacheCount;
- (id)getGroupContactCache:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

