//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSWindowController.h"

#import "NSWindowDelegate.h"

@class NSMutableAttributedString, NSString, NSTextView;

@interface JSConsoleWindwController : NSWindowController <NSWindowDelegate>
{
    NSTextView *_consoleView;
    NSMutableAttributedString *_showLogInfo;
}

@property(retain, nonatomic) NSMutableAttributedString *showLogInfo; // @synthesize showLogInfo=_showLogInfo;
@property NSTextView *consoleView; // @synthesize consoleView=_consoleView;
- (void).cxx_destruct;
- (void)appendLogInfo:(id)arg1;
- (void)windowWillClose:(id)arg1;
- (void)windowDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

