//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "IExptServiceExt.h"
#import "IIPxxExt.h"

@class MemoryRecordInfo, MemoryStatConfig, MemoryStatReporter, NSRecursiveLock, NSString;

@interface MemoryStatManager : NSObject <IIPxxExt, IExptServiceExt>
{
    NSString *m_rootDir;
    NSString *m_dataDir;
    NSString *m_configPath;
    NSRecursiveLock *m_lock;
    MemoryStatConfig *m_config;
    MemoryRecordInfo *m_currRecord;
    MemoryRecordInfo *m_lastRecord;
    BOOL m_isStartTracking;
    MemoryStatReporter *m_reporter;
}

+ (id)sharedInstance;
- (void).cxx_destruct;
- (void)onExptItemListChange;
- (void)didBecomeActive;
- (void)onGetIpxxMsgContent:(id)arg1;
- (void)uploadReportWithCurrentRecord;
- (void)startTracking;
- (void)saveConfig;
- (BOOL)checkDataValid;
- (void)clearUnnecessaryData;
- (void)loadConfig;
- (void)uploadReport:(id)arg1;
- (id)recordList;
- (void)setMemoryStatEnabled:(BOOL)arg1;
- (BOOL)isMemoryStatEnabled;
- (void)setCurrRecordInvalid;
- (void)removeAndDeleteFile;
- (void)checkAndRecord;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

