//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMService.h"

#import "AppMessageHandlerDelegate.h"
#import "EmoticonMessageHandlerDelegate.h"
#import "ImgMessageHandlerDelegate.h"
#import "MMService.h"
#import "RecordMessageHandlerDelegate.h"
#import "TextMessageHandlerDelegate.h"
#import "VideoMessageHandlerDelegate.h"
#import "VoiceMessageHandlerDelegate.h"

@class AppMessageHandler, EmoticonMessageHandler, ImgMessageHandler, NSLock, NSMutableDictionary, NSMutableSet, NSRecursiveLock, NSString, RecordMessageHandler, TextMessageHandler, ThumbDownloadMgr, VideoMessageHandler, VoiceMessageHandler;

@interface MessageService : MMService <TextMessageHandlerDelegate, ImgMessageHandlerDelegate, VideoMessageHandlerDelegate, VoiceMessageHandlerDelegate, AppMessageHandlerDelegate, EmoticonMessageHandlerDelegate, RecordMessageHandlerDelegate, MMService>
{
    NSRecursiveLock *m_dbCacheLock;
    NSMutableDictionary *m_dictMsgDB;
    TextMessageHandler *m_textMsgHandler;
    VoiceMessageHandler *m_voiceMsgHandler;
    ImgMessageHandler *m_imgMsgHandler;
    VideoMessageHandler *m_videoMsgHandler;
    AppMessageHandler *m_appMsgHandler;
    EmoticonMessageHandler *m_emoticonMsgHandler;
    ThumbDownloadMgr *m_thumbDownloadMgr;
    NSRecursiveLock *m_oLockForVideoCompress;
    RecordMessageHandler *m_recordMsgHandler;
    NSLock *m_lock;
    BOOL _isMacHelperHasNewChanges;
    BOOL _m_hasClearData;
    NSMutableSet *_revokingMessages;
    NSMutableSet *_translatingMessages;
}

+ (void)DeleteMessageDatabase;
+ (void)registerClsMethod_MessageDataExt;
+ (void)RegisterClsMethod;
+ (id)ConvertVideoFavItem2MsgWrap:(id)arg1;
+ (id)ConvertFavData2FavItem:(id)arg1;
+ (BOOL)savesMessagesToDisk;
+ (void)setSavesMessagesToDisk:(BOOL)arg1;
+ (void)delMsgDBs;
@property BOOL m_hasClearData; // @synthesize m_hasClearData=_m_hasClearData;
@property(retain, nonatomic) NSMutableSet *translatingMessages; // @synthesize translatingMessages=_translatingMessages;
@property(retain, nonatomic) NSMutableSet *revokingMessages; // @synthesize revokingMessages=_revokingMessages;
@property(nonatomic) BOOL isMacHelperHasNewChanges; // @synthesize isMacHelperHasNewChanges=_isMacHelperHasNewChanges;
- (void).cxx_destruct;
- (void)reportFileLog:(id)arg1 isForward:(BOOL)arg2;
- (id)forwardAppImageMessage:(id)arg1 toUser:(id)arg2 errMsg:(id *)arg3;
- (id)sendWebStreamVideoMessage:(id)arg1 toUsrName:(id)arg2;
- (id)forwardVideoMessage:(id)arg1 toUser:(id)arg2 extType:(int)arg3 errMsg:(id *)arg4;
- (id)SendVideoMessage:(id)arg1 toUsrName:(id)arg2 videoInfo:(id)arg3 msgType:(unsigned int)arg4 refMesageData:(id)arg5;
- (void)asyncCompressVideoInGlobalQueue:(id)arg1 videoDataInfo:(id)arg2 toUsrName:(id)arg3;
- (BOOL)updateUploadAndDownloadStatusInDBWithMessage:(id)arg1;
- (BOOL)updateVideoInformationInDBWithMessage:(id)arg1;
- (BOOL)updateFileInformationInDBWithMessage:(id)arg1;
- (BOOL)updateTranslateStatusInDBWithMessage:(id)arg1;
- (BOOL)updateVoiceTextInDBWithMessage:(id)arg1;
- (void)RemoveTranslationForMessage:(id)arg1;
- (void)TranslateMsg:(id)arg1 withCompletion:(CDUnknownBlockType)arg2;
- (void)notifyAppMsgUploadProgress:(id)arg1 msgData:(id)arg2 uploadedBytes:(int)arg3 totalBytes:(int)arg4;
- (void)onAppMsgSendFinish:(id)arg1 msgData:(id)arg2;
- (void)onFailedToParseXMLWhenDownloading:(id)arg1;
- (void)onVoiceDowloadFinished:(id)arg1 isSuccess:(BOOL)arg2 isNeedSave:(BOOL)arg3 offset:(unsigned long long)arg4;
- (void)onVoiceUploadCanceledWhenDownloading:(id)arg1;
- (void)notifyUpdateVideoStatus:(id)arg1 msgData:(id)arg2;
- (void)onVideoMsgSendFinish:(id)arg1 msgData:(id)arg2;
- (void)notifyCheckQQ;
- (void)notifyUploadProgress:(id)arg1 msgData:(id)arg2;
- (void)onImgMsgSendFinish:(id)arg1 msgData:(id)arg2;
- (void)onTextMsgSendFinish:(id)arg1 msgData:(id)arg2;
- (void)onEmoticonMsgSendFailed:(id)arg1 msgData:(id)arg2;
- (void)onEmoticonMsgSendFinish:(id)arg1 msgData:(id)arg2;
- (BOOL)isAppMsgDownloading:(id)arg1;
- (BOOL)isVideoMsgDownloading:(id)arg1;
- (BOOL)isAppMsgUploading:(id)arg1;
- (BOOL)isVideoMsgUploading:(id)arg1;
- (BOOL)isImgMsgUploading:(id)arg1;
- (BOOL)isEmojiMsgUploading:(id)arg1;
- (BOOL)isTextMsgUploading:(id)arg1;
- (void)ensureCreateVideoThumb:(id)arg1 thumbPath:(id)arg2;
- (void)ensureCreateImageThumb:(id)arg1 thumbPath:(id)arg2;
- (void)cancelUploadVideoMsg:(id)arg1 msgData:(id)arg2;
- (void)cancelUploadAppMsg:(id)arg1 msgData:(id)arg2;
- (void)cancelDownloadAppMsg:(id)arg1 msgData:(id)arg2;
- (void)StartDownloadAppMsg:(id)arg1 msgData:(id)arg2;
- (void)StartDownloadVoice:(id)arg1;
- (void)AddRevokePromptMsg:(id)arg1 msgData:(id)arg2;
- (void)AddTestMsg:(id)arg1 msgData:(id)arg2;
- (void)AddLocalMsg:(id)arg1 msgData:(id)arg2;
- (id)ForwardMessage:(id)arg1 withReaderWrap:(id)arg2 toUser:(id)arg3;
- (id)ForwardMessage:(id)arg1 toUser:(id)arg2 errMsg:(id *)arg3;
- (void)addAppMsgToSendQueue:(id)arg1 toUserName:(id)arg2 scene:(unsigned int)arg3;
- (id)forwardAppMsgMessage:(id)arg1 toUser:(id)arg2 errMsg:(id *)arg3;
- (id)forwardAppEmojiMessage:(id)arg1 toUser:(id)arg2 errMsg:(id *)arg3;
- (id)forwardAppFileMessage:(id)arg1 toUser:(id)arg2 errMsg:(id *)arg3;
- (id)forwardEmojiMessage:(id)arg1 toUser:(id)arg2 errMsg:(id *)arg3;
- (id)forwardImageMessage:(id)arg1 toUser:(id)arg2 errMsg:(id *)arg3;
- (id)forwardTextMessage:(id)arg1 toUser:(id)arg2 errMsg:(id *)arg3;
- (void)notifyUIAndSessionOnMainThread:(id)arg1 withMsg:(id)arg2;
- (id)creatNewMessage:(id)arg1 withUserName:(id)arg2;
- (void)ResendMsg:(id)arg1 toUser:(id)arg2;
- (void)onRecordMsgUploadCDNModMsgByBitSet:(id)arg1 MsgWrap:(id)arg2 BitSet:(unsigned int)arg3;
- (void)sendChatSyncAppMsg:(id)arg1;
- (id)SendNoteAppMsgTo:(id)arg1 withFavoritesItem:(id)arg2;
- (id)SendRecordAppMsgTo:(id)arg1 withFavoritesItem:(id)arg2;
- (id)SendFileAppMsgTo:(id)arg1 fileName:(id)arg2 filePath:(id)arg3;
- (id)SendGifAppMsgFromUsr:(id)arg1 toUser:(id)arg2 gifFilePath:(id)arg3;
- (id)SendGifFileMsgFromUsr:(id)arg1 toUser:(id)arg2 gifFileName:(id)arg3 gifFilePath:(id)arg4;
- (id)getEmoticonMsgContentWithMD5:(id)arg1 emoticonType:(unsigned int)arg2;
- (id)_getWWNamecardMsgContentForContact:(id)arg1;
- (id)_getNamecardMsgContentForContact:(id)arg1;
- (id)SendLocationMsgFromUser:(id)arg1 toUser:(id)arg2 withLatitude:(double)arg3 longitude:(double)arg4 poiName:(id)arg5 label:(id)arg6;
- (id)SendNamecardMsgFromUser:(id)arg1 toUser:(id)arg2 containingContact:(id)arg3;
- (id)SendStickerStoreEmoticonMsgFromUsr:(id)arg1 toUsrName:(id)arg2 md5:(id)arg3 productID:(id)arg4;
- (id)SendEmoticonMsgFromUsr:(id)arg1 toUsrName:(id)arg2 md5:(id)arg3 emoticonType:(unsigned int)arg4;
- (void)AddShortVideoMsg:(id)arg1 ToUsr:(id)arg2 VideoInfo:(id)arg3;
- (void)AddShortVideoMsg:(id)arg1 ToUsr:(id)arg2 VideoInfo:(id)arg3 isKFSession:(BOOL)arg4;
- (id)SendImgMessage:(id)arg1 toUsrName:(id)arg2 thumbImgData:(id)arg3 midImgData:(id)arg4 imgData:(id)arg5 imgInfo:(id)arg6;
- (id)SendTextMessage:(id)arg1 toUsrName:(id)arg2 msgText:(id)arg3 atUserList:(id)arg4;
- (id)SendAppMusicMessageFromUser:(id)arg1 toUsrName:(id)arg2 withTitle:(id)arg3 url:(id)arg4 description:(id)arg5 thumbnailData:(id)arg6;
- (id)SendAppURLMessageFromUser:(id)arg1 toUsrName:(id)arg2 withTitle:(id)arg3 url:(id)arg4 description:(id)arg5 thumbnailData:(id)arg6;
- (id)SendAppURLMessageFromUser:(id)arg1 toUsrName:(id)arg2 withTitle:(id)arg3 url:(id)arg4 description:(id)arg5 thumbUrl:(id)arg6;
- (BOOL)updateImageSizeWithMessage:(id)arg1;
- (void)DelMsg:(id)arg1 msgList:(id)arg2 isDelAll:(BOOL)arg3 isManual:(BOOL)arg4;
- (void)cleanDownloadTask:(id)arg1;
- (BOOL)ClearUnRead:(id)arg1 FromCreateTime:(unsigned int)arg2 ToCreateTime:(unsigned int)arg3;
- (BOOL)RecallMsgWithChatName:(id)arg1 msgData:(id)arg2 erroHandler:(CDUnknownBlockType)arg3;
- (void)ModifyMsgDataInDBWithMessage:(id)arg1 chatName:(id)arg2;
- (void)ModifyMsgDataField:(id)arg1 msgData:(id)arg2 bitSet:(unsigned int)arg3;
- (void)checkDownloadStatus:(id)arg1;
- (void)checkUploadStatus:(id)arg1;
- (void)CheckMessageStatus:(id)arg1;
- (BOOL)hasMsgInChat:(id)arg1;
- (unsigned int)GetUnReadCount:(id)arg1;
- (id)GetMsgData:(id)arg1 svrId:(unsigned long long)arg2;
- (id)GetMsgData:(id)arg1 localId:(unsigned int)arg2;
- (id)GetAllMsgWithChatName:(id)arg1 messageType:(unsigned int)arg2;
- (id)GetMsgListWithChatName:(id)arg1 fromMinCreateTime:(unsigned int)arg2 svrId:(unsigned long long)arg3 limitCnt:(unsigned int)arg4 hasMore:(char *)arg5;
- (id)GetMsgListWithChatName:(id)arg1 fromCreateTime:(unsigned int)arg2 limitCnt:(unsigned int)arg3 hasMore:(char *)arg4 messageTypes:(id)arg5 sortAscend:(BOOL)arg6;
- (id)GetMsgListWithChatName:(id)arg1 fromCreateTime:(unsigned int)arg2 limitCnt:(unsigned int)arg3 hasMore:(char *)arg4 sortAscend:(BOOL)arg5;
- (id)GetLastMsg:(id)arg1;
- (void)onServiceClearData;
- (void)setupMacHelperOnMainThread;
- (void)onServiceInit;
- (id)init;
- (BOOL)addNewSyncMsg:(id)arg1 chatName:(id)arg2 msgDb:(id)arg3;
- (void)processAddMsg:(id)arg1 sessionMsgList:(id)arg2 isFirstSync:(BOOL)arg3;
- (void)addChatList:(id)arg1;
- (void)addMarkRead:(id)arg1 createTime:(unsigned int)arg2;
- (void)addQuitSession:(id)arg1;
- (void)addEnterSession:(id)arg1;
- (void)processStatusNotifyOpCode:(unsigned int)arg1 userName:(id)arg2 msgData:(id)arg3;
- (void)processStatusNotifyOpCode:(unsigned int)arg1 OpNode:(struct XmlReaderNode_t *)arg2 msgData:(id)arg3;
- (void)processStatusNotifyMsg:(id)arg1;
- (void)processSysMsg:(id)arg1;
- (void)processVoipInviteMsg:(id)arg1;
- (void)processYoMsg:(id)arg1;
- (void)processNewXMLMsg:(id)arg1;
- (void)FFToNameFavChatZZ:(id)arg1;
- (BOOL)isCanAddToDB:(id)arg1;
- (BOOL)isFilterMsg:(id)arg1;
- (BOOL)isMsgSpecialProcess:(id)arg1;
- (id)genMsgDataFromAddMsg:(id)arg1;
- (id)filterAddMsg:(id)arg1;
- (void)OnSyncModMsgStatus:(id)arg1;
- (void)OnSyncBatchAddFunctionMsgs:(id)arg1 isFirstSync:(BOOL)arg2;
- (void)FFImgToOnFavInfoInfoVCZZ:(id)arg1 isFirstSync:(BOOL)arg2;
- (id)GetImgOrVideoNextMsg:(id)arg1 FromID:(unsigned int)arg2 CreateTime:(unsigned int)arg3 Limit:(unsigned int)arg4;
- (id)GetImgOrVideoLastMsg:(id)arg1 FromID:(unsigned int)arg2 CreateTime:(unsigned int)arg3 Limit:(unsigned int)arg4;
- (id)GetImgOrAppNextMsg:(id)arg1 FromID:(unsigned int)arg2 CreateTime:(unsigned int)arg3 Limit:(unsigned int)arg4;
- (id)GetImgOrAppLastMsg:(id)arg1 FromID:(unsigned int)arg2 CreateTime:(unsigned int)arg3 Limit:(unsigned int)arg4;
- (BOOL)isPreviewVideoMsgDownloading:(id)arg1;
- (BOOL)isPreviewImageMsgDownloading:(id)arg1;
- (id)ForwardFavoritesItem:(id)arg1 withThumbnailData:(id)arg2 thumbnailSize:(struct CGSize)arg3 imageData:(id)arg4 toUserName:(id)arg5;
- (id)ForwardFavoritesItem:(id)arg1 toUserName:(id)arg2;
- (id)GetMsgList:(id)arg1 mesLocalIDs:(id)arg2;
- (id)GetMsgList:(id)arg1 arrFTSMessageData:(id)arg2;
- (id)GetMsgListWithChatName:(id)arg1 minCreateTime:(unsigned int)arg2 limitCnt:(unsigned int)arg3;
- (id)GetMsgListWithChatName:(id)arg1 minMesLocalId:(unsigned int)arg2 limitCnt:(unsigned int)arg3;
- (id)getMaxLocalIdMsg:(id)arg1;
- (id)searchWithKeyword:(id)arg1 chatName:(id)arg2 minMesLocalID:(unsigned int)arg3 limitCount:(unsigned int)arg4;
- (void)deleteMsgGapBy:(id)arg1;
- (void)updateMsgGapBy:(id)arg1;
- (void)deleteMsgGapEarlierThan:(unsigned int)arg1;
- (id)getMsgGapsFrom:(unsigned int)arg1 to:(unsigned int)arg2 chat:(id)arg3;
- (void)addMsgGapForSessions:(id)arg1 startTime:(unsigned int)arg2 endTime:(unsigned int)arg3;
- (int)changeType:(id)arg1 oldMsg:(id)arg2;
- (id)getOldMsg:(long long)arg1 oldMsgList:(id)arg2;
- (void)movePathsFromOldMessage:(id)arg1 toNewMessage:(id)arg2;
- (void)sendChatSyncNewXml:(id)arg1 startTime:(unsigned int)arg2 endTime:(unsigned int)arg3 sessionName:(id)arg4 identifier:(id)arg5 limit:(unsigned int)arg6;
- (BOOL)insertMsgList:(id)arg1 chatName:(id)arg2 toDB:(id)arg3 oldMsgList:(id)arg4;
- (id)genMsgDataFromBakChatMsgItem:(id)arg1;
- (void)updateSession:(id)arg1 chatName:(id)arg2 toDB:(id)arg3;
- (BOOL)isInMessageException:(id)arg1 chatName:(id)arg2 toDB:(id)arg3 sender:(id)arg4;
- (id)getAdjustMessage:(id)arg1 chatName:(id)arg2 toDB:(id)arg3 oldMsgList:(id)arg4;
- (BOOL)canAddToDB:(id)arg1;
- (id)getFilterDeleteMessage:(id)arg1 chatName:(id)arg2 toDB:(id)arg3;
- (BOOL)shouldFilterMsg:(id)arg1;
- (id)getFilterUnSupportMessage:(id)arg1;
- (id)parseAndSortSyncMsgList:(id)arg1;
- (void)OnSyncBatchBakChatMsg:(id)arg1 sender:(id)arg2 message:(id)arg3 msgGap:(id)arg4;
- (id)getMsgDBWithIdentifier:(id)arg1 withChatName:(id)arg2;
- (id)getMsgDBWithIdentifier:(id)arg1;
- (id)getMsgDB:(id)arg1;
- (void)notifyMsgResendOnMainThread:(id)arg1 msgData:(id)arg2;
- (void)notifyCheckQQOnMainThread;
- (void)notifyImgUploadProgressOnMainThread:(id)arg1 msgData:(id)arg2;
- (void)notifyImgMsgSendFinishOnMainThread:(id)arg1 msgData:(id)arg2;
- (void)notifyUnreadCntChangeOnMainThread:(id)arg1;
- (void)notifyAddMsgListForSessionOnMainThread:(id)arg1;
- (void)notifyDelAllMsgOnMainThread:(id)arg1;
- (void)notifyMsgDeletedForSessionOnMainThread:(id)arg1;
- (void)notifyDelMsgOnMainThread:(id)arg1 msgData:(id)arg2;
- (void)notifyAddRevokePromptMsgOnMainThread:(id)arg1 msgData:(id)arg2;
- (void)notifyModMsgOnMainThread:(id)arg1 msgData:(id)arg2;
- (void)notifyChatSyncMessagesMergedOnMainThread:(id)arg1;
- (void)notifyChatSyncMsgsOnMainThread:(id)arg1 msgList:(id)arg2;
- (void)notifyAddMsgOnMainThread:(id)arg1 msgData:(id)arg2;
- (void)notifyNewMsgNotificationOnMainThread:(id)arg1 msgData:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

