//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMTextMessageCellView.h"

@interface MMAppBaseMessageCellView : MMTextMessageCellView
{
}

- (void)setChoosable:(BOOL)arg1;
- (BOOL)allowChoose;
- (BOOL)allowOperate;
- (BOOL)allowOpen;
- (BOOL)allowMultipleSelect;
- (BOOL)allowRecall;
- (void)prepareForReuse;
- (id)initWithFrame:(struct CGRect)arg1;

@end

