//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMMessageCellView.h"

@class CAShapeLayer, MMImageView, MMReaderWrapView, MMView, NSImageView, NSTextField, ReaderWrap;

@interface MMAppSingleReaderMessageCellView : MMMessageCellView
{
    ReaderWrap *_readerData;
    MMReaderWrapView *_containerView;
    NSTextField *_readerTitleLabel;
    NSTextField *_readerTimeLabel;
    MMImageView *_readerThumbnail;
    NSTextField *_readerDescription;
    MMView *_readerSeperator;
    NSTextField *_readMore;
    NSImageView *_rightArrowIcon;
    CAShapeLayer *_strokeLayer;
}

+ (double)cellHeightWithMessage:(id)arg1 constrainedToWidth:(double)arg2;
+ (BOOL)isAppReaderMessage:(id)arg1;
+ (BOOL)hasUrlForMessage:(id)arg1;
+ (double)heightForTopNewsDescriptionStr:(id)arg1 withContentWidth:(double)arg2;
+ (BOOL)hasThumbnailForMessage:(id)arg1;
+ (double)thumbnailHeightWithContentWidth:(double)arg1;
+ (double)contentWidthWithCellWidth:(double)arg1;
@property(retain, nonatomic) CAShapeLayer *strokeLayer; // @synthesize strokeLayer=_strokeLayer;
@property(retain, nonatomic) NSImageView *rightArrowIcon; // @synthesize rightArrowIcon=_rightArrowIcon;
@property(retain, nonatomic) NSTextField *readMore; // @synthesize readMore=_readMore;
@property(retain, nonatomic) MMView *readerSeperator; // @synthesize readerSeperator=_readerSeperator;
@property(retain, nonatomic) NSTextField *readerDescription; // @synthesize readerDescription=_readerDescription;
@property(retain, nonatomic) MMImageView *readerThumbnail; // @synthesize readerThumbnail=_readerThumbnail;
@property(retain, nonatomic) NSTextField *readerTimeLabel; // @synthesize readerTimeLabel=_readerTimeLabel;
@property(retain, nonatomic) NSTextField *readerTitleLabel; // @synthesize readerTitleLabel=_readerTitleLabel;
@property(retain, nonatomic) MMReaderWrapView *containerView; // @synthesize containerView=_containerView;
@property(retain, nonatomic) ReaderWrap *readerData; // @synthesize readerData=_readerData;
- (void).cxx_destruct;
- (void)setChoosable:(BOOL)arg1;
- (BOOL)allowChoose;
- (void)contextMenuForward;
- (id)getOperationMenuItem;
- (BOOL)allowRecall;
- (BOOL)showsSaveToFavoritesButton;
- (BOOL)showsContextMenuButton;
- (id)draggingImage;
- (BOOL)draggingEnabled;
- (struct CGRect)bubbleFrame;
- (struct CGRect)clickableArea;
- (void)layoutReaderSeperator;
- (void)layoutReadMoreView;
- (void)layoutDescription;
- (void)layoutThumbnail;
- (void)layoutReaderTitleLabel;
- (void)layoutReaderTimeLabel;
- (void)layoutContainerView;
- (void)layoutViews;
- (void)viewDidMoveToSuperview;
- (void)updateMessageLayer;
- (void)updateHighlightMaskView;
- (void)populateWithMessage:(id)arg1;
- (void)prepareForReuse;
- (void)setHighlighted:(BOOL)arg1;
- (void)resizeSubviewsWithOldSize:(struct CGSize)arg1;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;
- (BOOL)hasUrl;
- (BOOL)hasThumbnail;

@end

