//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMService.h"

#import "GetHeadImageDelegate.h"
#import "IContactMgrExt.h"
#import "IGroupMgrExt.h"
#import "MMService.h"
#import "SyncExt.h"

@class AFHTTPSessionManager, GetHeadImage, MMCache, NSLock, NSMutableDictionary, NSObject<OS_dispatch_queue>, NSString;

@interface MMAvatarService : MMService <IContactMgrExt, GetHeadImageDelegate, IGroupMgrExt, SyncExt, MMService>
{
    NSObject<OS_dispatch_queue> *_queue;
    BOOL _isDownloadMgrValid;
    BOOL _isSendingDownloadCGI;
    MMCache *_avatarCache;
    AFHTTPSessionManager *_downloadMgr;
    NSMutableDictionary *_downloadingUrlBlocks;
    GetHeadImage *_cgiGetter;
    NSMutableDictionary *_cgiTasks;
    NSLock *_m_lock;
    NSLock *_m_blocksLock;
}

@property(retain, nonatomic) NSLock *m_blocksLock; // @synthesize m_blocksLock=_m_blocksLock;
@property(retain, nonatomic) NSLock *m_lock; // @synthesize m_lock=_m_lock;
@property(retain, nonatomic) NSMutableDictionary *cgiTasks; // @synthesize cgiTasks=_cgiTasks;
@property(retain, nonatomic) GetHeadImage *cgiGetter; // @synthesize cgiGetter=_cgiGetter;
@property(nonatomic) BOOL isSendingDownloadCGI; // @synthesize isSendingDownloadCGI=_isSendingDownloadCGI;
@property(retain, nonatomic) NSMutableDictionary *downloadingUrlBlocks; // @synthesize downloadingUrlBlocks=_downloadingUrlBlocks;
@property BOOL isDownloadMgrValid; // @synthesize isDownloadMgrValid=_isDownloadMgrValid;
@property(retain, nonatomic) AFHTTPSessionManager *downloadMgr; // @synthesize downloadMgr=_downloadMgr;
@property(retain, nonatomic) MMCache *avatarCache; // @synthesize avatarCache=_avatarCache;
- (void).cxx_destruct;
- (void)setupDownloadMgr;
- (void)proxySettingsDidChange:(id)arg1;
- (id)resizeToSquareAvatarImage:(id)arg1;
- (void)onDownloadImage:(id)arg1 forScene:(int)arg2 isHD:(BOOL)arg3 imageData:(id)arg4;
- (void)onDownloadImageFail:(id)arg1 forScene:(int)arg2 isHD:(BOOL)arg3;
- (BOOL)isNeedGetImage:(id)arg1 forScene:(int)arg2 isHD:(BOOL)arg3 isForce:(BOOL)arg4;
- (void)makeAvatarWithMemberList:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)generateGroupChatAvatarWithContact:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (id)signalWithContact:(id)arg1;
- (void)updateNativeAvatarImageWithContact:(id)arg1 image:(id)arg2;
- (void)updateAvatarOnModifyContacts:(id)arg1;
- (void)OnModifyGroupMemberContact:(id)arg1;
- (void)onDeleteContacts:(id)arg1;
- (void)onModifyStrangerContacts:(id)arg1;
- (void)onModifyContacts:(id)arg1;
- (void)downloadAvatarImageWithUsername:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)getAvatarImageWithUsername:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)downloadAvatarWithUrl:(id)arg1 userName:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (BOOL)checkIsDwonloadingAndAddCallback:(CDUnknownBlockType)arg1 forKey:(id)arg2;
- (void)callBackForKey:(id)arg1 withImage:(id)arg2 userName:(id)arg3 url:(id)arg4 err:(id)arg5;
- (void)callBackFailedForUserNames:(id)arg1 err:(id)arg2;
- (void)getAvatarImageAfterAuthOKWithUrl:(id)arg1 userName:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (void)getAvatarImageBeforeAuthOKWithUrl:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)getAvatarHDImageWithContact:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)getAvatarImageWithContact:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (id)_genAvatarKeyWithUrl:(id)arg1 userName:(id)arg2 isHD:(BOOL)arg3;
- (void)forceSendRequestUpdateAvatarImageRemoteOutOfLimitTimeWithContact:(id)arg1;
- (void)forceGetAvatarImageRemoteWithContact:(id)arg1 isHD:(BOOL)arg2 completion:(CDUnknownBlockType)arg3;
- (void)__removeAvatarFromStorageWithUrl:(id)arg1 userName:(id)arg2 isHD:(BOOL)arg3;
- (void)_removeAvatarHDFromStorageWithUrl:(id)arg1 userName:(id)arg2;
- (void)_removeAvatarFromStorageWithUrl:(id)arg1 userName:(id)arg2;
- (void)_removeImageFromDiskWithMd5Key:(id)arg1 userName:(id)arg2;
- (void)_removeImageFromCacheWithMd5Key:(id)arg1;
- (void)_storeImageToDisk:(id)arg1 url:(id)arg2 userName:(id)arg3 isHD:(BOOL)arg4;
- (void)_storeImageToCache:(id)arg1 url:(id)arg2 userName:(id)arg3 isHD:(BOOL)arg4;
- (id)_getImageFromCacheWithMD5Key:(id)arg1;
- (void)_storeImage:(id)arg1 url:(id)arg2 userName:(id)arg3 isHD:(BOOL)arg4;
- (void)_fetchAvatarRemoteWithUrl:(id)arg1 secondWithUserName:(id)arg2 isHD:(BOOL)arg3 completion:(CDUnknownBlockType)arg4;
- (void)_fetchAvatarFirstWithUrl:(id)arg1 secondWithUserName:(id)arg2 isHD:(BOOL)arg3 completion:(CDUnknownBlockType)arg4;
- (BOOL)hasSpecialAvatarWithUserName:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)clearCache;
- (id)getAvatarImageNativeWithContact:(id)arg1 isHD:(BOOL)arg2;
- (void)getSelfAvatarHDImageWithCompletion:(CDUnknownBlockType)arg1;
- (void)getSelfAvatarImageWithCompletion:(CDUnknownBlockType)arg1;
- (id)brandSessionHolderAvatar;
- (id)defaultHDAvatar;
- (id)defaultAvatarImage;
- (id)qqmailAvatarImage;
- (id)avatarSavePathWithFileName:(id)arg1 userName:(id)arg2;
- (id)avatarBeforeAuthOKSavePathWithFileName:(id)arg1;
- (void)onServiceClearData;
- (void)onServiceInit;
- (void)onInitCancel;
- (void)destroy;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

