//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "MMBrandSubMenuViewControllerDelegate.h"
#import "NSPopoverDelegate.h"

@class NSPopover, NSString, WCContactData;

@interface MMBrandMenuPlugin : NSObject <MMBrandSubMenuViewControllerDelegate, NSPopoverDelegate>
{
    WCContactData *_currentChatContact;
    NSPopover *_brandSubMenuPopover;
}

@property(retain, nonatomic) NSPopover *brandSubMenuPopover; // @synthesize brandSubMenuPopover=_brandSubMenuPopover;
@property(retain, nonatomic) WCContactData *currentChatContact; // @synthesize currentChatContact=_currentChatContact;
- (void).cxx_destruct;
- (void)popoverDidClose:(id)arg1;
- (void)popoverShouldClose;
- (void)setupBrandSubMenuView:(id)arg1 relativeView:(id)arg2;
- (void)onMenuButtonClick:(id)arg1;
- (void)setupBrandMenuListWithCurrentContact:(id)arg1 menuContainerView:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

