//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMViewController.h"

#import "MMTableViewDelegate.h"
#import "NSTableViewDataSource.h"
#import "NSTableViewDelegate.h"

@class MMTableView, NSArray, NSString;

@interface MMBrandSubMenuViewController : MMViewController <NSTableViewDelegate, NSTableViewDataSource, MMTableViewDelegate>
{
    id <MMBrandSubMenuViewControllerDelegate> _delegate;
    MMTableView *_tableView;
    NSString *_currUserName;
    NSArray *_menuItemData;
}

@property(retain, nonatomic) NSArray *menuItemData; // @synthesize menuItemData=_menuItemData;
@property(retain, nonatomic) NSString *currUserName; // @synthesize currUserName=_currUserName;
@property __weak MMTableView *tableView; // @synthesize tableView=_tableView;
@property(nonatomic) __weak id <MMBrandSubMenuViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)tableView:(id)arg1 rowGotMouseUp:(long long)arg2;
- (void)tableView:(id)arg1 rowGotMouseDown:(long long)arg2;
- (void)chooseCurrentItem;
- (void)selectNextItem;
- (void)selectPrevItem;
- (id)tableView:(id)arg1 viewForTableColumn:(id)arg2 row:(long long)arg3;
- (double)tableView:(id)arg1 heightOfRow:(long long)arg2;
- (long long)numberOfRowsInTableView:(id)arg1;
- (void)hide;
- (void)setMenuItemData:(id)arg1 withUserName:(id)arg2;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

