//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSTableCellView.h"

#import "IContactMgrExt.h"
#import "IMMSessionMgrExt.h"
#import "MMEmoticonDescMgrExt.h"
#import "NSMenuDelegate.h"

@class CAShapeLayer, MMBadgeOverlayView, MMChatsCellAvatarView, MMImageView, MMSessionInfo, MMSidebarColorIconView, MMSidebarLabelTextField, MMTextField, MMView, NSString, NSView;

@interface MMChatsTableCellView : NSTableCellView <IContactMgrExt, NSMenuDelegate, MMEmoticonDescMgrExt, IMMSessionMgrExt>
{
    BOOL _selected;
    BOOL _shouldRemoveHighlight;
    BOOL _shouldDrawFocusRing;
    id <MMChatsTableCellViewDelegate> _delegate;
    MMSessionInfo *_sessionInfo;
    MMView *_vibrancyContainer;
    NSView *_containerView;
    NSView *_stickyBackgroundView;
    MMView *_seperator;
    MMSidebarColorIconView *_muteIndicator;
    MMChatsCellAvatarView *_avatar;
    MMBadgeOverlayView *_badgeView;
    MMSidebarLabelTextField *_summary;
    MMSidebarLabelTextField *_timeLabel;
    MMTextField *_nickName;
    NSString *_messageTime;
    NSString *_userName;
    MMImageView *_sendFailedImg;
    MMImageView *_openimGroupFlag;
    CAShapeLayer *_shapeLayer;
}

@property(retain, nonatomic) CAShapeLayer *shapeLayer; // @synthesize shapeLayer=_shapeLayer;
@property(retain, nonatomic) MMImageView *openimGroupFlag; // @synthesize openimGroupFlag=_openimGroupFlag;
@property(retain, nonatomic) MMImageView *sendFailedImg; // @synthesize sendFailedImg=_sendFailedImg;
@property(nonatomic) BOOL shouldDrawFocusRing; // @synthesize shouldDrawFocusRing=_shouldDrawFocusRing;
@property(readonly, nonatomic) NSString *userName; // @synthesize userName=_userName;
@property(retain, nonatomic) NSString *messageTime; // @synthesize messageTime=_messageTime;
@property(retain, nonatomic) MMTextField *nickName; // @synthesize nickName=_nickName;
@property(retain, nonatomic) MMSidebarLabelTextField *timeLabel; // @synthesize timeLabel=_timeLabel;
@property(retain, nonatomic) MMSidebarLabelTextField *summary; // @synthesize summary=_summary;
@property(retain, nonatomic) MMBadgeOverlayView *badgeView; // @synthesize badgeView=_badgeView;
@property(retain, nonatomic) MMChatsCellAvatarView *avatar; // @synthesize avatar=_avatar;
@property(retain, nonatomic) MMSidebarColorIconView *muteIndicator; // @synthesize muteIndicator=_muteIndicator;
@property(retain, nonatomic) MMView *seperator; // @synthesize seperator=_seperator;
@property(retain, nonatomic) NSView *stickyBackgroundView; // @synthesize stickyBackgroundView=_stickyBackgroundView;
@property(nonatomic) BOOL shouldRemoveHighlight; // @synthesize shouldRemoveHighlight=_shouldRemoveHighlight;
@property(retain, nonatomic) NSView *containerView; // @synthesize containerView=_containerView;
@property(retain, nonatomic) MMView *vibrancyContainer; // @synthesize vibrancyContainer=_vibrancyContainer;
@property(nonatomic) BOOL selected; // @synthesize selected=_selected;
@property(retain, nonatomic) MMSessionInfo *sessionInfo; // @synthesize sessionInfo=_sessionInfo;
@property(nonatomic) __weak id <MMChatsTableCellViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)mouseDown:(id)arg1;
- (void)updateStoreEmoticonDescSuccess;
- (void)onSessionUpdated:(id)arg1 withType:(long long)arg2;
- (void)onModifyUserImageWithUrl:(id)arg1 userName:(id)arg2;
- (void)contextMenuRename;
- (void)contextMenuMute:(id)arg1;
- (void)contextMenuSticky:(id)arg1;
- (void)contextMenuDelete:(id)arg1;
- (void)contextMenuProfile:(id)arg1;
- (void)menuDidClose:(id)arg1;
- (void)menuWillOpen:(id)arg1;
- (id)menuForEvent:(id)arg1;
- (BOOL)canBecomeKeyView;
- (BOOL)performDragOperation:(id)arg1;
- (void)draggingEnded:(id)arg1;
- (void)draggingExited:(id)arg1;
- (unsigned long long)draggingEntered:(id)arg1;
- (BOOL)prepareForDragOperation:(id)arg1;
- (id)acceptableDragTypes;
- (id)summaryAttributedString;
- (BOOL)shouldUseSelectedColorForText;
- (void)drawSelectionBackground;
- (void)updateSelectionBackground;
- (void)layoutSummaryViews;
- (void)updateSummary;
- (void)updateMuteIndicator;
- (void)updateMsgStatus;
- (void)layoutNickNameViews;
- (void)updateTimeLabel;
- (void)updateOpenIMGroupIcon;
- (void)updateNickname;
- (void)updateBadgeView;
- (void)updateAvatarImage;
- (void)updateStickyBgView;
- (id)lastMessage;
- (BOOL)isWxWorkSession;
- (BOOL)isMentionedUnread;
- (BOOL)isMsgStatusFailed;
- (BOOL)isMuted;
- (BOOL)isSticky;
- (void)setupWithSessionInfo:(id)arg1;
- (void)resizeSubviewsWithOldSize:(struct CGSize)arg1;
- (void)prepareForReuse;
- (void)showUIDebugGuidesChanged:(id)arg1;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

