//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMMessageCellView.h"

#import "IMessageExt.h"

@class CAShapeLayer, MMCTTextView, MMTextView, MMView, NSString;

@interface MMChatLogMessageCellView : MMMessageCellView <IMessageExt>
{
    BOOL _isRetry;
    MMView *_containerView;
    MMCTTextView *_titleLabel;
    MMCTTextView *_descriptionTextView;
    MMView *_divider;
    MMTextView *_bottomTextView;
    CAShapeLayer *_strokeLayer;
}

+ (void)handleGlobalTextSizeChange;
+ (void)load;
+ (double)containerHeightWithMessage:(id)arg1;
+ (double)cellHeightWithMessage:(id)arg1 constrainedToWidth:(double)arg2;
+ (id)_formattedChatLogContentWithMsg:(id)arg1;
+ (id)_genSenderAndContentString:(id)arg1 isLastOne:(BOOL)arg2;
@property(retain, nonatomic) CAShapeLayer *strokeLayer; // @synthesize strokeLayer=_strokeLayer;
@property(nonatomic) BOOL isRetry; // @synthesize isRetry=_isRetry;
@property(retain, nonatomic) MMTextView *bottomTextView; // @synthesize bottomTextView=_bottomTextView;
@property(retain, nonatomic) MMView *divider; // @synthesize divider=_divider;
@property(retain, nonatomic) MMCTTextView *descriptionTextView; // @synthesize descriptionTextView=_descriptionTextView;
@property(retain, nonatomic) MMCTTextView *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(retain, nonatomic) MMView *containerView; // @synthesize containerView=_containerView;
- (void).cxx_destruct;
- (void)onDownloadAppAttachExpiredFail:(id)arg1 msgData:(id)arg2;
- (void)onAppRecordMsgDownloadFinish:(id)arg1 msgData:(id)arg2 isSuccess:(BOOL)arg3;
- (void)resendMessage;
- (void)setChoosable:(BOOL)arg1;
- (BOOL)allowChoose;
- (struct CGRect)contentFrame;
- (struct CGRect)bubbleFrame;
- (void)writeIntoPasteboard:(id)arg1 orItem:(id)arg2 provideDataForType:(id)arg3;
- (void)updateMessageLayer;
- (id)draggingImage;
- (void)setHighlighted:(BOOL)arg1;
- (id)getOperationMenuItem;
- (BOOL)isCanAddToFavorites;
- (struct CGRect)clickableArea;
- (void)mouseUp:(id)arg1;
- (void)mouseDown:(id)arg1;
- (void)layoutBottomView;
- (void)layoutdescriptionTextView;
- (void)layoutTitleLabel;
- (void)layoutContainerView;
- (void)populateWithMessage:(id)arg1;
- (void)resizeSubviewsWithOldSize:(struct CGSize)arg1;
- (void)prepareForReuse;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

