//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMAttachmentReusableView.h"

@class MMCTTextView, NSTextField;

@interface MMChatLogAttachmentView : MMAttachmentReusableView
{
    NSTextField *_titleLable;
    MMCTTextView *_detailLabel;
}

+ (double)suggestedHeightWithAttributedString:(id)arg1 constrainedToWidth:(double)arg2;
@property(retain, nonatomic) MMCTTextView *detailLabel; // @synthesize detailLabel=_detailLabel;
@property(retain, nonatomic) NSTextField *titleLable; // @synthesize titleLable=_titleLable;
- (void).cxx_destruct;
- (void)initView;
- (id)initWithIdentifier:(id)arg1;

@end

