//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSViewController.h"

#import "IContactMgrExt.h"
#import "IGroupMgrExt.h"
#import "MMTableViewDelegate.h"
#import "NSTableViewDataSource.h"
#import "NSTableViewDelegate.h"
#import "OpenIMResourceMgrExt.h"

@class MMChatDetailAnnounceView, MMChatDetailEventView, MMChatDetailNameView, MMDivider, MMGroupChatAnnounceWindow, MMOutlineButton, MMSearchField, MMSessionPickerWindow, MMTableView, MMTextField, MMView, NSArray, NSMutableArray, NSString, NSView, WCContactData;

@interface MMChatMemberListViewController : NSViewController <NSTableViewDelegate, NSTableViewDataSource, MMTableViewDelegate, IGroupMgrExt, IContactMgrExt, OpenIMResourceMgrExt>
{
    BOOL _isShown;
    BOOL _isAnimating;
    BOOL _isGroupChatOwner;
    BOOL _isSearching;
    WCContactData *_contact;
    CDUnknownBlockType _viewDidLoadBlock;
    CDUnknownBlockType _isAnimatingBlock;
    id <MMComposeInputViewDelegate> _composeInputViewDelegate;
    NSArray *_groupMemberList;
    NSMutableArray *_searchMemberList;
    MMSessionPickerWindow *_sessionPickerWindow;
    MMGroupChatAnnounceWindow *_announceWindow;
    MMView *_backgroundView;
    MMDivider *_divider;
    MMView *_topSeperator;
    MMView *_bottomSeperator;
    MMChatDetailNameView *_chatNameView;
    MMChatDetailAnnounceView *_chatAnnounceView;
    MMOutlineButton *_quitGroupChatButton;
    MMTextField *_noSearchResultHint;
    MMChatDetailEventView *_eventView;
    NSView *_contentView;
    MMTableView *_tableView;
    MMSearchField *_searchField;
}

@property(nonatomic) __weak MMSearchField *searchField; // @synthesize searchField=_searchField;
@property(nonatomic) __weak MMTableView *tableView; // @synthesize tableView=_tableView;
@property(nonatomic) __weak NSView *contentView; // @synthesize contentView=_contentView;
@property(retain, nonatomic) MMChatDetailEventView *eventView; // @synthesize eventView=_eventView;
@property(retain, nonatomic) MMTextField *noSearchResultHint; // @synthesize noSearchResultHint=_noSearchResultHint;
@property(retain, nonatomic) MMOutlineButton *quitGroupChatButton; // @synthesize quitGroupChatButton=_quitGroupChatButton;
@property(retain, nonatomic) MMChatDetailAnnounceView *chatAnnounceView; // @synthesize chatAnnounceView=_chatAnnounceView;
@property(retain, nonatomic) MMChatDetailNameView *chatNameView; // @synthesize chatNameView=_chatNameView;
@property(retain, nonatomic) MMView *bottomSeperator; // @synthesize bottomSeperator=_bottomSeperator;
@property(retain, nonatomic) MMView *topSeperator; // @synthesize topSeperator=_topSeperator;
@property(retain, nonatomic) MMDivider *divider; // @synthesize divider=_divider;
@property(retain, nonatomic) MMView *backgroundView; // @synthesize backgroundView=_backgroundView;
@property(nonatomic) __weak MMGroupChatAnnounceWindow *announceWindow; // @synthesize announceWindow=_announceWindow;
@property(retain, nonatomic) MMSessionPickerWindow *sessionPickerWindow; // @synthesize sessionPickerWindow=_sessionPickerWindow;
@property(nonatomic) BOOL isSearching; // @synthesize isSearching=_isSearching;
@property(nonatomic) BOOL isGroupChatOwner; // @synthesize isGroupChatOwner=_isGroupChatOwner;
@property(retain, nonatomic) NSMutableArray *searchMemberList; // @synthesize searchMemberList=_searchMemberList;
@property(retain, nonatomic) NSArray *groupMemberList; // @synthesize groupMemberList=_groupMemberList;
@property(nonatomic) __weak id <MMComposeInputViewDelegate> composeInputViewDelegate; // @synthesize composeInputViewDelegate=_composeInputViewDelegate;
@property(nonatomic) BOOL isAnimating; // @synthesize isAnimating=_isAnimating;
@property(nonatomic) BOOL isShown; // @synthesize isShown=_isShown;
@property(copy, nonatomic) CDUnknownBlockType isAnimatingBlock; // @synthesize isAnimatingBlock=_isAnimatingBlock;
@property(copy, nonatomic) CDUnknownBlockType viewDidLoadBlock; // @synthesize viewDidLoadBlock=_viewDidLoadBlock;
@property(retain, nonatomic) WCContactData *contact; // @synthesize contact=_contact;
- (void).cxx_destruct;
- (void)_resetSearch;
- (void)searchTextChanged:(id)arg1;
- (void)_relayoutSearchControls;
- (void)_relayoutGroupChatInfoViews;
- (void)handleAppFontSize;
- (void)deleteFromGroupChatWithSelectedUserNames:(id)arg1;
- (void)startAGroupChatWithSelectedUserNames:(id)arg1;
- (void)startANewSingleChatWithSelectedUserName:(id)arg1;
- (void)addToGroupChatWithSelectedUserNames:(id)arg1;
- (void)menuActionDeleteGroupMember:(id)arg1;
- (void)menuActionMentionGroupMember:(id)arg1;
- (void)menuActionAddFriendWithGroupMember:(id)arg1;
- (void)menuActionChatWithGroupMember:(id)arg1;
- (void)buttonActionRemoveMember;
- (void)buttonActionAddMember;
- (id)makeDeleteMemberMenuItem:(id)arg1 title:(id)arg2 action:(SEL)arg3;
- (id)makeMemberListMenuItem:(id)arg1 title:(id)arg2 action:(SEL)arg3;
- (void)didDoubleClickedWithContact:(id)arg1;
- (void)didRightClickOnMemberRowView:(id)arg1;
- (void)didClickOnMemberRowView:(id)arg1;
- (void)didClickOnButtonRowView:(id)arg1;
- (void)keyDown:(id)arg1;
- (void)OnModifyGroupMemberContact:(id)arg1;
- (void)OpenIMResourceWordingIds:(id)arg1 didFinish:(id)arg2;
- (void)updateGroupMemberOnModifyContacts:(id)arg1;
- (void)updateGroupChatOnModifyContacts:(id)arg1;
- (void)updateSingleChatOnModifyContacts:(id)arg1;
- (void)onModifyContacts:(id)arg1;
- (void)tableView:(id)arg1 rowGotDoubleClicked:(long long)arg2;
- (void)tableView:(id)arg1 rowGotRightMouseUp:(long long)arg2;
- (void)tableView:(id)arg1 rowGotMouseUp:(long long)arg2;
- (void)tableView:(id)arg1 rowGotRightMouseDown:(long long)arg2;
- (void)tableView:(id)arg1 rowGotMouseDown:(long long)arg2;
- (id)tableView:(id)arg1 rowViewForRow:(long long)arg2;
- (long long)numberOfRowsInTableView:(id)arg1;
- (void)hideToast;
- (void)showToast:(id)arg1 image:(id)arg2;
- (void)showToast:(id)arg1;
- (void)showSubviews:(BOOL)arg1;
- (BOOL)isSelfSession;
- (BOOL)isButtonRowView:(long long)arg1;
- (void)updateGroupMemberList:(id)arg1;
- (void)delayReloadTableView;
- (void)reloadTableView;
- (BOOL)isPointInsideChatMemberListView:(struct CGPoint)arg1;
- (void)hideWithMouseEvent:(id)arg1;
- (void)hideWithAnimated:(BOOL)arg1 makeFirstResponder:(unsigned char)arg2;
- (void)showWithAnimated:(BOOL)arg1;
- (void)toggle;
- (void)updateTableView:(BOOL)arg1;
- (void)setupDidShowAnnouncementBlock;
- (void)setupDidUpdateNicknameBlock;
- (void)updateGroupChatAnnouncement;
- (void)updateGroupChatNickname;
- (void)updateSearchField:(BOOL)arg1;
- (void)refreshContact:(id)arg1;
- (void)setupGroupChatInfoViews;
- (void)setupQuitGroupChatButton;
- (void)setupSearchControls;
- (void)setupContentView;
- (void)setupEventView;
- (void)viewDidLoad;
- (void)dealloc;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

