//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSTableCellView.h"

#import "NSDraggingSource.h"

@class FavoritesItem, FavoritesItemDataField, MMAvatarImageView, MMBorderView, MMChatLogEventView, MMTextView, MessageData, NSImage, NSString;

@interface MMChatLogBaseCellView : NSTableCellView <NSDraggingSource>
{
    BOOL _selected;
    FavoritesItemDataField *_currentDataField;
    MessageData *_parentMessage;
    FavoritesItem *_parentFavItem;
    FavoritesItemDataField *_parentDataField;
    id <MMChatLogCellViewDelegate> _delegate;
    MMChatLogEventView *_contentView;
    MMAvatarImageView *_avatarImageView;
    MMBorderView *_solidLine;
    MMTextView *_senderNameInfoTextView;
    MMTextView *_senderDateInfoTextView;
    NSImage *_savedDraggingImage;
    struct CGPoint _mouseDownLocation;
}

+ (BOOL)isContentViewUseFixWidth:(id)arg1;
+ (id)getSenderDateInfo:(id)arg1;
+ (id)getSenderNameInfo:(id)arg1;
+ (double)senderInfoViewHeightWithFavItemDataField:(id)arg1 constrainedToWidth:(double)arg2;
+ (id)summaryWithCurrentDataField:(id)arg1;
+ (double)cellHeightWithFavItemDataField:(id)arg1 parentMessage:(id)arg2 parentFavItem:(id)arg3 parentDataField:(id)arg4 constrainedToWidth:(double)arg5;
@property(nonatomic) struct CGPoint mouseDownLocation; // @synthesize mouseDownLocation=_mouseDownLocation;
@property(retain, nonatomic) NSImage *savedDraggingImage; // @synthesize savedDraggingImage=_savedDraggingImage;
@property(retain, nonatomic) MMTextView *senderDateInfoTextView; // @synthesize senderDateInfoTextView=_senderDateInfoTextView;
@property(retain, nonatomic) MMTextView *senderNameInfoTextView; // @synthesize senderNameInfoTextView=_senderNameInfoTextView;
@property(retain, nonatomic) MMBorderView *solidLine; // @synthesize solidLine=_solidLine;
@property(retain, nonatomic) MMAvatarImageView *avatarImageView; // @synthesize avatarImageView=_avatarImageView;
@property(retain, nonatomic) MMChatLogEventView *contentView; // @synthesize contentView=_contentView;
@property(nonatomic) __weak id <MMChatLogCellViewDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) FavoritesItemDataField *parentDataField; // @synthesize parentDataField=_parentDataField;
@property(retain, nonatomic) FavoritesItem *parentFavItem; // @synthesize parentFavItem=_parentFavItem;
@property(retain, nonatomic) MessageData *parentMessage; // @synthesize parentMessage=_parentMessage;
@property(retain, nonatomic) FavoritesItemDataField *currentDataField; // @synthesize currentDataField=_currentDataField;
@property(nonatomic) BOOL selected; // @synthesize selected=_selected;
- (void).cxx_destruct;
- (BOOL)notMoveFar:(id)arg1;
- (BOOL)menuEventIsInClickableArea:(id)arg1;
- (id)resizedDraggingImage;
- (BOOL)isShouldDisplayAvatar;
- (void)layoutAvatarWithCurrentDataField:(id)arg1;
- (id)_getContactWithDataField:(id)arg1;
- (id)_getRealChatNameWithDataField:(id)arg1;
- (void)layoutAvatar;
- (void)layoutSenderInfoView;
- (void)layoutContentView;
- (BOOL)isOriginalFileExisting;
- (id)originalFileName;
- (id)originalFilePath;
- (void)contextMenuExport;
- (void)contextMenuFavorites;
- (void)contextMenuForward;
- (void)contextMenuCopy;
- (BOOL)allowExport;
- (BOOL)allowAddToFavorites;
- (BOOL)allowForward;
- (BOOL)allowCopy;
- (id)contextMenu;
- (struct CGRect)clickableArea;
- (id)menuForEvent:(id)arg1;
- (void)handleMouseDownEvent;
- (void)populateWithFavItemDataField:(id)arg1 parentDataField:(id)arg2;
- (void)populateWithFavItemDataField:(id)arg1 parentFavItem:(id)arg2;
- (void)populateWithFavItemDataField:(id)arg1 parentMessage:(id)arg2;
- (unsigned long long)draggingSession:(id)arg1 sourceOperationMaskForDraggingContext:(long long)arg2;
- (id)generatePasteboardItem;
- (struct CGRect)draggingFrameForEvent:(id)arg1;
- (id)draggingImage;
- (BOOL)allowDraging;
- (void)mouseDragged:(id)arg1;
- (void)mouseDown:(id)arg1;
- (void)prepareForReuse;
- (void)drawRect:(struct CGRect)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

