//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMTableDataSource.h"

#import "IGroupMgrExt.h"
#import "IMMSessionMgrExt.h"
#import "IMessageExt.h"

@class NSString;

@interface MMChatMessageDataSource : MMTableDataSource <IMessageExt, IGroupMgrExt, IMMSessionMgrExt>
{
    BOOL _shouldShowTypingCell;
    BOOL _canLoadMoreFromPullDown;
    BOOL _canLoadMoreFromPullUp;
    BOOL _canLoadMoreFromPhone;
    unsigned int _chatSyncFirstLocalId;
    unsigned int _minCreateTime;
    unsigned int _maxCreateTime;
    unsigned int _lastTimeStamp;
    NSString *_userName;
    unsigned long long _lastMsgSvrId;
    CDUnknownBlockType _didReceiveNewMessagesBlock;
    CDUnknownBlockType _didChangeShowDisplayNameBlock;
    CDUnknownBlockType _didRemoveMessageBlock;
    CDUnknownBlockType _didRemoveAllMessageBlock;
    CDUnknownBlockType _didSendMessageFailedBlock;
    CDUnknownBlockType _didSendMessageSucceededBlock;
    CDUnknownBlockType _didUpdateMessageBlock;
    CDUnknownBlockType _didAddRevokePromptMessageBlock;
    CDUnknownBlockType _didAddNewLocalSystemMessagesBlock;
    CDUnknownBlockType _didUpdateUnreadCountMessagesBlock;
    CDUnknownBlockType _didUnreadCountChangedBlock;
}

@property(nonatomic) BOOL canLoadMoreFromPhone; // @synthesize canLoadMoreFromPhone=_canLoadMoreFromPhone;
@property(nonatomic) BOOL canLoadMoreFromPullUp; // @synthesize canLoadMoreFromPullUp=_canLoadMoreFromPullUp;
@property(nonatomic) BOOL canLoadMoreFromPullDown; // @synthesize canLoadMoreFromPullDown=_canLoadMoreFromPullDown;
@property(copy, nonatomic) CDUnknownBlockType didUnreadCountChangedBlock; // @synthesize didUnreadCountChangedBlock=_didUnreadCountChangedBlock;
@property(copy, nonatomic) CDUnknownBlockType didUpdateUnreadCountMessagesBlock; // @synthesize didUpdateUnreadCountMessagesBlock=_didUpdateUnreadCountMessagesBlock;
@property(copy, nonatomic) CDUnknownBlockType didAddNewLocalSystemMessagesBlock; // @synthesize didAddNewLocalSystemMessagesBlock=_didAddNewLocalSystemMessagesBlock;
@property(copy, nonatomic) CDUnknownBlockType didAddRevokePromptMessageBlock; // @synthesize didAddRevokePromptMessageBlock=_didAddRevokePromptMessageBlock;
@property(copy, nonatomic) CDUnknownBlockType didUpdateMessageBlock; // @synthesize didUpdateMessageBlock=_didUpdateMessageBlock;
@property(copy, nonatomic) CDUnknownBlockType didSendMessageSucceededBlock; // @synthesize didSendMessageSucceededBlock=_didSendMessageSucceededBlock;
@property(copy, nonatomic) CDUnknownBlockType didSendMessageFailedBlock; // @synthesize didSendMessageFailedBlock=_didSendMessageFailedBlock;
@property(copy, nonatomic) CDUnknownBlockType didRemoveAllMessageBlock; // @synthesize didRemoveAllMessageBlock=_didRemoveAllMessageBlock;
@property(copy, nonatomic) CDUnknownBlockType didRemoveMessageBlock; // @synthesize didRemoveMessageBlock=_didRemoveMessageBlock;
@property(copy, nonatomic) CDUnknownBlockType didChangeShowDisplayNameBlock; // @synthesize didChangeShowDisplayNameBlock=_didChangeShowDisplayNameBlock;
@property(copy, nonatomic) CDUnknownBlockType didReceiveNewMessagesBlock; // @synthesize didReceiveNewMessagesBlock=_didReceiveNewMessagesBlock;
@property(nonatomic) unsigned int lastTimeStamp; // @synthesize lastTimeStamp=_lastTimeStamp;
@property(nonatomic) unsigned long long lastMsgSvrId; // @synthesize lastMsgSvrId=_lastMsgSvrId;
@property(nonatomic) unsigned int maxCreateTime; // @synthesize maxCreateTime=_maxCreateTime;
@property(nonatomic) unsigned int minCreateTime; // @synthesize minCreateTime=_minCreateTime;
@property(nonatomic) unsigned int chatSyncFirstLocalId; // @synthesize chatSyncFirstLocalId=_chatSyncFirstLocalId;
@property(nonatomic) BOOL shouldShowTypingCell; // @synthesize shouldShowTypingCell=_shouldShowTypingCell;
@property(retain, nonatomic) NSString *userName; // @synthesize userName=_userName;
- (void).cxx_destruct;
- (BOOL)hasMoreMessageFromRemote;
- (BOOL)hasMoreMessageInLocalDB;
- (BOOL)hasMoreMessageFromPullUp;
- (BOOL)hasMoreMessageFromPullDown;
- (void)OnChangeMemberShowDisplayName:(id)arg1;
- (void)onUnReadCountChangeFromSvr:(id)arg1;
- (void)onGetNewXmlMsg:(id)arg1 type:(id)arg2 msgData:(id)arg3;
- (void)_debugPrintMsgList;
- (void)onModMsg:(id)arg1 msgData:(id)arg2;
- (void)onDelAllMsg:(id)arg1;
- (void)onDelMsg:(id)arg1 msgData:(id)arg2;
- (void)onAddRevokePromptMsg:(id)arg1 msgData:(id)arg2;
- (void)onAddMsg:(id)arg1 msgData:(id)arg2;
- (BOOL)shouldInsertTimeStampWithNewMessage:(id)arg1 lastTimeStamp:(unsigned int)arg2;
- (id)messageTableItemWithType:(int)arg1 msgCreateTime:(unsigned int)arg2;
- (id)messageTableItemWithMessage:(id)arg1;
- (long long)typingCellIndex;
- (void)clearAndLoadRecentMessage;
- (long long)clearAndGetPageUnreadMessage:(unsigned long long)arg1;
- (void)clearAndGetUnReadFromBottom:(unsigned long long)arg1;
- (void)clearAndGetUnReadFromTop:(unsigned long long)arg1;
- (BOOL)loadMoreFromPullUp;
- (BOOL)loadMoreFromPullDown;
- (unsigned long long)loadMoreMessages;
- (void)getRecentMessages;
- (void)getMsgFromPhoneIfNeed:(unsigned int)arg1 endTime:(unsigned int)arg2;
- (unsigned long long)totalMessageCount;
- (id)unreadMessages;
- (void)markAllMessagesAsRead:(id)arg1;
- (long long)indexOfLocalID:(unsigned int)arg1;
- (unsigned long long)indexOfMessageWithUniqueId:(id)arg1;
- (unsigned long long)indexOfMessage:(id)arg1;
- (BOOL)insertHistoryRecordURLForBrandUser;
- (BOOL)insertChatSyncDividerAtLocalId:(unsigned int)arg1;
- (BOOL)insertNewMessageDividerAtIndex:(unsigned long long)arg1;
- (void)removeMessageAtIndex:(unsigned long long)arg1;
- (void)setMessageAtIndex:(unsigned long long)arg1 withItem:(id)arg2;
- (id)messageWithIndex:(unsigned long long)arg1;
@property(readonly, nonatomic) unsigned long long messageCount;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

