//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSViewController.h"

#import "IContactMgrExt.h"
#import "MMComposeInputViewDelegate.h"
#import "MMComposeRichAttachmentTextViewDelegate.h"
#import "MMComposeTextEmotionProtDelegate.h"
#import "MMNetExt.h"
#import "MMViewerWindowDelegate.h"
#import "MessageBatchExportMgrExt.h"
#import "MessageServiceExt.h"
#import "NSTextViewDelegate.h"

@class MMBatchExportViewWindow, MMBrandMenuPlugin, MMComposeInputScrollView, MMComposeTextStorage, MMComposeTextView, MMEmotionPromptWindowController, MMIgnoreEventView, MMMessageSendLogic, NSButton, NSClipView, NSMutableDictionary, NSString, NSTextField, NSView, WCContactData;

@interface MMComposeInputViewController : NSViewController <MMNetExt, IContactMgrExt, MMComposeInputViewDelegate, MMComposeRichAttachmentTextViewDelegate, NSTextViewDelegate, MessageBatchExportMgrExt, MMViewerWindowDelegate, MessageServiceExt, MMComposeTextEmotionProtDelegate>
{
    BOOL isNoNetwork;
    MMComposeTextView *_composeTextView;
    MMEmotionPromptWindowController *_emotionPromptControl;
    id <MMComposeTextViewDelegate> _composeTextViewDelegate;
    WCContactData *_currnetChatContact;
    MMMessageSendLogic *_messageSendLogic;
    CDUnknownBlockType _viewDidLoadBlock;
    id <MMChatDetailSplitViewPositionInterface><MMChatMemberListViewDelegate><MMAnimateVoipTipsDelegate> _delegate;
    id <MMMutipleSelectionDelegate> _multiSelectDelegate;
    MMComposeTextStorage *_textStorage;
    NSView *_toolBarView;
    NSButton *_stickerButton;
    NSButton *_attachmentButton;
    NSButton *_screenShotButton;
    NSButton *_videoButton;
    NSButton *_voiceButton;
    NSButton *_chatManagerButton;
    NSButton *_openBrandMenuButton;
    MMComposeInputScrollView *_scrollView;
    NSClipView *_clipView;
    MMIgnoreEventView *_multipleSelectView;
    NSView *_multipleButtonContainer;
    NSTextField *_forwardLabel;
    NSTextField *_mergeForwardLabel;
    NSTextField *_addFavoritesLabel;
    NSTextField *_saveLabel;
    NSTextField *_deleteLabel;
    MMIgnoreEventView *_brandMenuContainerView;
    NSView *_brandMenuListView;
    NSButton *_closeBrandMenuButton;
    MMBatchExportViewWindow *_exportViewWindow;
    NSMutableDictionary *_viewerWindowDic;
    MMBrandMenuPlugin *_brandMenuPlugin;
}

@property(retain, nonatomic) MMBrandMenuPlugin *brandMenuPlugin; // @synthesize brandMenuPlugin=_brandMenuPlugin;
@property(retain, nonatomic) NSMutableDictionary *viewerWindowDic; // @synthesize viewerWindowDic=_viewerWindowDic;
@property(retain, nonatomic) MMBatchExportViewWindow *exportViewWindow; // @synthesize exportViewWindow=_exportViewWindow;
@property(nonatomic) __weak NSButton *closeBrandMenuButton; // @synthesize closeBrandMenuButton=_closeBrandMenuButton;
@property(nonatomic) __weak NSView *brandMenuListView; // @synthesize brandMenuListView=_brandMenuListView;
@property(nonatomic) __weak MMIgnoreEventView *brandMenuContainerView; // @synthesize brandMenuContainerView=_brandMenuContainerView;
@property(nonatomic) __weak NSTextField *deleteLabel; // @synthesize deleteLabel=_deleteLabel;
@property(nonatomic) __weak NSTextField *saveLabel; // @synthesize saveLabel=_saveLabel;
@property(nonatomic) __weak NSTextField *addFavoritesLabel; // @synthesize addFavoritesLabel=_addFavoritesLabel;
@property(nonatomic) __weak NSTextField *mergeForwardLabel; // @synthesize mergeForwardLabel=_mergeForwardLabel;
@property(nonatomic) __weak NSTextField *forwardLabel; // @synthesize forwardLabel=_forwardLabel;
@property(nonatomic) __weak NSView *multipleButtonContainer; // @synthesize multipleButtonContainer=_multipleButtonContainer;
@property(nonatomic) __weak MMIgnoreEventView *multipleSelectView; // @synthesize multipleSelectView=_multipleSelectView;
@property(retain, nonatomic) NSClipView *clipView; // @synthesize clipView=_clipView;
@property(retain, nonatomic) MMComposeInputScrollView *scrollView; // @synthesize scrollView=_scrollView;
@property(nonatomic) __weak NSButton *openBrandMenuButton; // @synthesize openBrandMenuButton=_openBrandMenuButton;
@property(nonatomic) __weak NSButton *chatManagerButton; // @synthesize chatManagerButton=_chatManagerButton;
@property(nonatomic) __weak NSButton *voiceButton; // @synthesize voiceButton=_voiceButton;
@property(nonatomic) __weak NSButton *videoButton; // @synthesize videoButton=_videoButton;
@property(nonatomic) __weak NSButton *screenShotButton; // @synthesize screenShotButton=_screenShotButton;
@property(nonatomic) __weak NSButton *attachmentButton; // @synthesize attachmentButton=_attachmentButton;
@property(nonatomic) __weak NSButton *stickerButton; // @synthesize stickerButton=_stickerButton;
@property(nonatomic) __weak NSView *toolBarView; // @synthesize toolBarView=_toolBarView;
@property(retain, nonatomic) MMComposeTextStorage *textStorage; // @synthesize textStorage=_textStorage;
@property(nonatomic) __weak id <MMMutipleSelectionDelegate> multiSelectDelegate; // @synthesize multiSelectDelegate=_multiSelectDelegate;
@property(nonatomic) __weak id <MMChatDetailSplitViewPositionInterface><MMChatMemberListViewDelegate><MMAnimateVoipTipsDelegate> delegate; // @synthesize delegate=_delegate;
@property(copy, nonatomic) CDUnknownBlockType viewDidLoadBlock; // @synthesize viewDidLoadBlock=_viewDidLoadBlock;
@property(retain, nonatomic) MMMessageSendLogic *messageSendLogic; // @synthesize messageSendLogic=_messageSendLogic;
@property(retain, nonatomic) WCContactData *currnetChatContact; // @synthesize currnetChatContact=_currnetChatContact;
@property(nonatomic) __weak id <MMComposeTextViewDelegate> composeTextViewDelegate; // @synthesize composeTextViewDelegate=_composeTextViewDelegate;
@property(retain, nonatomic) MMEmotionPromptWindowController *emotionPromptControl; // @synthesize emotionPromptControl=_emotionPromptControl;
@property(retain, nonatomic) MMComposeTextView *composeTextView; // @synthesize composeTextView=_composeTextView;
- (void).cxx_destruct;
- (void)windowDidColsed:(id)arg1;
- (void)textView:(id)arg1 doubleClickedOnCell:(id)arg2 inRect:(struct CGRect)arg3 atIndex:(unsigned long long)arg4;
- (id)textView:(id)arg1 attachmentViewWithAttachment:(id)arg2;
- (void)SaveMutipleSelect;
- (void)ForwardMutipleSelect:(BOOL)arg1;
- (void)showSessionPickerWithSendMsgList:(id)arg1 isNeedMerge:(BOOL)arg2;
- (BOOL)supportMergeForward:(id)arg1 shouldShowAlert:(BOOL)arg2;
- (void)completeSendEmotion;
- (void)pasteQuotedMessageToInputView:(id)arg1;
- (void)insertMentionContactToInputView:(id)arg1;
- (void)performStartVoipVideoChat;
- (void)performStartVoipVoiceChat;
- (void)performKeyDown:(id)arg1;
- (void)performMultiSelection;
- (BOOL)shouldMakeFirstResponder;
- (void)showEmotionPrompt;
- (void)resetEmotionPrompt;
- (void)closeEmoticonPrompt;
- (BOOL)showEmotionPromptWithKeyEvent:(id)arg1;
- (void)clearComposeViewAndPromot;
- (void)OnBatchExportFinishedWithTotalFileCount:(unsigned long long)arg1 failedMsgList:(id)arg2 reasons:(id)arg3;
- (void)OnBatchExportProgressWithMessage:(id)arg1 totalFileCount:(unsigned long long)arg2 finishedFileCount:(unsigned long long)arg3 shouldShowExportProgress:(BOOL)arg4;
- (void)onModifyContacts:(id)arg1;
- (void)onNetStatusChange:(int)arg1;
- (void)setupBrandMenu;
- (void)onSendVideoMsgFailed:(id)arg1 toUsrName:(id)arg2 videoPath:(id)arg3;
- (void)setupMultipleSelect;
- (void)updateChatComposeTextViewDelegate;
- (void)setupView;
- (void)CloseMultipleSelect:(id)arg1;
- (void)DeleteByMultipleSelect:(id)arg1;
- (void)SaveByMultipleSelect:(id)arg1;
- (void)AddFavoritesByMultipleSelect:(id)arg1;
- (void)ForwardByMergeMutipleSelect:(id)arg1;
- (void)ForwardByMultipleSelect:(id)arg1;
- (void)openChatManager:(id)arg1;
- (void)addLocalTipsMsg:(id)arg1;
- (void)setupPushMailMenuItemList;
- (void)setupBrandMenuItemList;
- (void)_cleanBrandMenuSubviews;
- (void)_removeBrandMenuMode;
- (void)hideBrandMenu:(id)arg1;
- (void)showPushMailMenu;
- (void)showBrandMenu:(id)arg1;
- (void)showVoiceChat:(id)arg1;
- (void)showVideoChat:(id)arg1;
- (void)screenShotButtonPress:(id)arg1;
- (void)showAttachmentMenu:(id)arg1;
- (void)showStickerPicker:(id)arg1;
- (void)updateViewAndLayouts;
- (void)layoutForResize;
- (double)brandMenuViewHeight;
- (double)multipleSelectViewHeight;
- (BOOL)isMultipleSelectViewHidden;
- (void)composeTextViewTextChanged:(id)arg1;
- (void)fontSizeClassChanged:(id)arg1;
- (void)viewDidDisappear;
- (void)viewDidAppear;
- (void)viewDidLoad;
- (void)dealloc;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

