//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "AccountServiceExt.h"

@class MMChatFTSSearchLogic, NSString;

@interface MMComplexChatLogSearchMgr : NSObject <AccountServiceExt>
{
    MMChatFTSSearchLogic *_ftsSearchLogic;
}

+ (id)sharedInstance;
@property(retain, nonatomic) MMChatFTSSearchLogic *ftsSearchLogic; // @synthesize ftsSearchLogic=_ftsSearchLogic;
- (void).cxx_destruct;
- (void)getGlobalSearchResultWithSearchKey:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)onUserLogout;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

