//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMRichAttachmentBaseTextViewDelegate.h"

@class MMComposeTextView;

@protocol MMComposeRichAttachmentTextViewDelegate <MMRichAttachmentBaseTextViewDelegate>
- (void)textView:(MMComposeTextView *)arg1 doubleClickedOnCell:(id <NSTextAttachmentCell>)arg2 inRect:(struct CGRect)arg3 atIndex:(unsigned long long)arg4;
@end

