//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMViewController.h"

#import "AccountServiceExt.h"
#import "IContactMgrExt.h"
#import "MMCGIDelegate.h"
#import "MMTableViewDelegate.h"
#import "MMViewerWindowDelegate.h"
#import "NSTableViewDataSource.h"
#import "NSTableViewDelegate.h"
#import "NSTextFieldDelegate.h"
#import "OpenIMResourceMgrExt.h"

@class MMCTTextView, MMContactProfileData, MMContactProfileMgr, MMProfileFooterView, MMProfileHeaderView, MMTableView, NSScrollView, NSString, NSVisualEffectView, NSWindow, RBLPopover, RBLPopoverBackgroundView, WCContactData;

@interface MMContactProfileController : MMViewController <OpenIMResourceMgrExt, MMViewerWindowDelegate, NSTextFieldDelegate, AccountServiceExt, NSTableViewDataSource, NSTableViewDelegate, MMTableViewDelegate, MMCGIDelegate, IContactMgrExt>
{
    int _type;
    unsigned int _mySessionId;
    WCContactData *_contactData;
    NSString *_groupName;
    unsigned long long _preferredEdge;
    RBLPopover *_rblPopover;
    RBLPopoverBackgroundView *_rblBackgroundView;
    NSVisualEffectView *_visualEffectView;
    NSWindow *_parentWindow;
    MMProfileHeaderView *_headerView;
    MMProfileFooterView *_footerView;
    MMCTTextView *_officeAccountDesc;
    MMTableView *_tableView;
    NSScrollView *_scrollView;
    NSString *_remarkValue;
    MMContactProfileMgr *_model;
    MMContactProfileData *_data;
    double _singleLineHeight;
    struct CGRect _relativeToRect;
}

@property(nonatomic) unsigned int mySessionId; // @synthesize mySessionId=_mySessionId;
@property(nonatomic) double singleLineHeight; // @synthesize singleLineHeight=_singleLineHeight;
@property(retain, nonatomic) MMContactProfileData *data; // @synthesize data=_data;
@property(retain, nonatomic) MMContactProfileMgr *model; // @synthesize model=_model;
@property(nonatomic) int type; // @synthesize type=_type;
@property(copy, nonatomic) NSString *remarkValue; // @synthesize remarkValue=_remarkValue;
@property(retain, nonatomic) NSScrollView *scrollView; // @synthesize scrollView=_scrollView;
@property(retain, nonatomic) MMTableView *tableView; // @synthesize tableView=_tableView;
@property(retain, nonatomic) MMCTTextView *officeAccountDesc; // @synthesize officeAccountDesc=_officeAccountDesc;
@property(retain, nonatomic) MMProfileFooterView *footerView; // @synthesize footerView=_footerView;
@property(retain, nonatomic) MMProfileHeaderView *headerView; // @synthesize headerView=_headerView;
@property(nonatomic) __weak NSWindow *parentWindow; // @synthesize parentWindow=_parentWindow;
@property(retain, nonatomic) NSVisualEffectView *visualEffectView; // @synthesize visualEffectView=_visualEffectView;
@property(retain, nonatomic) RBLPopoverBackgroundView *rblBackgroundView; // @synthesize rblBackgroundView=_rblBackgroundView;
@property(retain, nonatomic) RBLPopover *rblPopover; // @synthesize rblPopover=_rblPopover;
@property(nonatomic) unsigned long long preferredEdge; // @synthesize preferredEdge=_preferredEdge;
@property(nonatomic) struct CGRect relativeToRect; // @synthesize relativeToRect=_relativeToRect;
@property(copy, nonatomic) NSString *groupName; // @synthesize groupName=_groupName;
@property(retain, nonatomic) WCContactData *contactData; // @synthesize contactData=_contactData;
- (void).cxx_destruct;
- (void)onModifyUserImageWithUrl:(id)arg1 userName:(id)arg2;
- (void)handleGetOpenIMContactResponse:(id)arg1;
- (void)handleGetContactResponse:(id)arg1;
- (void)OpenIMResourceWordingIds:(id)arg1 didFinish:(id)arg2;
- (void)OnResponseCGI:(BOOL)arg1 sessionId:(unsigned int)arg2 cgiWrap:(id)arg3;
- (void)onUserLogout;
- (void)onCurrentDeviceLockStateChanged:(BOOL)arg1;
- (void)adjustPopoverWindowFrame:(double)arg1;
- (void)windowDidColsed;
- (struct CGRect)originScreenRectForAnimationForWindow:(id)arg1;
- (void)tableViewSelectionDidChange:(id)arg1;
- (void)tableView:(id)arg1 rowGotMouseDown:(long long)arg2;
- (id)tableView:(id)arg1 viewForTableColumn:(id)arg2 row:(long long)arg3;
- (double)tableView:(id)arg1 heightOfRow:(long long)arg2;
- (long long)numberOfRowsInTableView:(id)arg1;
- (void)onOpemIMDescInfoClick:(id)arg1;
- (void)onAvatorImageClick;
- (void)onOfficeHistoryButtonClick;
- (void)onAddFriendButtonClick;
- (void)onShareButtonClick;
- (void)onMessageButtonClick;
- (void)onButtonClick:(int)arg1;
- (BOOL)isShown;
- (void)hide;
- (void)showInView:(id)arg1;
- (void)sendGetOpenIMContact:(id)arg1 withGroupName:(id)arg2;
- (void)sendGetContactRequest:(id)arg1 withGroupName:(id)arg2;
- (int)checkContactProfileType;
- (void)setupContact;
- (void)refreshModel:(id)arg1;
- (void)setupModel:(id)arg1;
- (double)numberOfOpenIMCustomItem;
- (double)calTableViewContentHeight;
- (double)calHeightSingleLineWithAdjustFont;
- (double)calContentWidthWithAdjustFont;
- (double)setupBodyView1:(double)arg1;
- (double)setupBodyView0:(double)arg1;
- (void)refreshUI;
- (void)setupUI;
- (void)initUI;
- (void)setupPopoperView:(id)arg1;
- (void)initPopoverView;
- (void)unRegisterExt;
- (void)dealloc;
- (void)viewDidDisappear;
- (void)viewDidLoad;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

