//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface MMFavShareReportData : NSObject
{
    unsigned int _favType;
    unsigned int _shareOp;
    unsigned int _shareFrom;
    unsigned int _favId;
    unsigned int _favSourceTime;
    unsigned int _favSourceType;
    unsigned int _subTransmitScene;
    unsigned int _bSubFile;
    NSString *_favInfoLength;
    NSString *_favSourceInfo;
    NSString *_transmitInfo;
    NSString *_dataIdList;
}

@property(retain, nonatomic) NSString *dataIdList; // @synthesize dataIdList=_dataIdList;
@property(nonatomic) unsigned int bSubFile; // @synthesize bSubFile=_bSubFile;
@property(retain, nonatomic) NSString *transmitInfo; // @synthesize transmitInfo=_transmitInfo;
@property(nonatomic) unsigned int subTransmitScene; // @synthesize subTransmitScene=_subTransmitScene;
@property(retain, nonatomic) NSString *favSourceInfo; // @synthesize favSourceInfo=_favSourceInfo;
@property(nonatomic) unsigned int favSourceType; // @synthesize favSourceType=_favSourceType;
@property(nonatomic) unsigned int favSourceTime; // @synthesize favSourceTime=_favSourceTime;
@property(retain, nonatomic) NSString *favInfoLength; // @synthesize favInfoLength=_favInfoLength;
@property(nonatomic) unsigned int favId; // @synthesize favId=_favId;
@property(nonatomic) unsigned int shareFrom; // @synthesize shareFrom=_shareFrom;
@property(nonatomic) unsigned int shareOp; // @synthesize shareOp=_shareOp;
@property(nonatomic) unsigned int favType; // @synthesize favType=_favType;
- (void).cxx_destruct;
- (void)configWithFavItem:(id)arg1;
- (id)init;

@end

