//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class FavoritesItemDataField;

@interface MMFavoriteFileDownloadTask : NSObject
{
    BOOL _fromRetry;
    FavoritesItemDataField *_dataField;
}

@property(nonatomic) BOOL fromRetry; // @synthesize fromRetry=_fromRetry;
@property(retain, nonatomic) FavoritesItemDataField *dataField; // @synthesize dataField=_dataField;
- (void).cxx_destruct;

@end

