//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface MMFavEnterDetailReportData : NSObject
{
    unsigned int _favType;
    unsigned int _searchType;
    unsigned int _enterNum;
}

@property(nonatomic) unsigned int enterNum; // @synthesize enterNum=_enterNum;
@property(nonatomic) unsigned int searchType; // @synthesize searchType=_searchType;
@property(nonatomic) unsigned int favType; // @synthesize favType=_favType;
- (void)configWithFavItem:(id)arg1;
- (id)init;

@end

