//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMViewController.h"

#import "MMFavoritesViewControllerDetailProtocol.h"

@class MMDraggingOverlayView, MMImageView, MMView, NSTextField;

@interface MMFavoritesPlaceholderViewController : MMViewController <MMFavoritesViewControllerDetailProtocol>
{
    MMView *_containerView;
    MMImageView *_placeHolderImgView;
    NSTextField *_noItemsDescTextField;
    NSTextField *_addItemsTipsTextField;
    MMDraggingOverlayView *_draggingOverlayView;
    id _mouseDraggedEvent;
}

@property(retain, nonatomic) id mouseDraggedEvent; // @synthesize mouseDraggedEvent=_mouseDraggedEvent;
@property(retain, nonatomic) MMDraggingOverlayView *draggingOverlayView; // @synthesize draggingOverlayView=_draggingOverlayView;
@property(retain) NSTextField *addItemsTipsTextField; // @synthesize addItemsTipsTextField=_addItemsTipsTextField;
@property(retain) NSTextField *noItemsDescTextField; // @synthesize noItemsDescTextField=_noItemsDescTextField;
@property(retain) MMImageView *placeHolderImgView; // @synthesize placeHolderImgView=_placeHolderImgView;
@property(retain) MMView *containerView; // @synthesize containerView=_containerView;
- (void).cxx_destruct;
- (void)windowDidBecomeKeyAction:(id)arg1;
- (void)windowDidResignKeyAction:(id)arg1;
- (void)setupDraggingOverlayView;
- (void)adjustContainerView;
- (id)getCollectionView;
- (void)openItem:(id)arg1;
- (void)scrollToItem:(id)arg1;
- (void)searchWithKeyword:(id)arg1;
- (void)clearSearch;
- (void)scrollToLatest:(BOOL)arg1;
- (void)scrollToBottomAnimated:(BOOL)arg1;
- (void)scrollToTopAnimated:(BOOL)arg1;
- (void)reloadData:(CDUnknownBlockType)arg1;
- (void)reloadData;
- (void)dealloc;
- (void)viewDidLoad;

@end

