//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface MMGetA8KeyConfig : NSObject
{
    BOOL _useFullUrl;
    unsigned int _scene;
    int _reason;
}

@property(nonatomic) int reason; // @synthesize reason=_reason;
@property(nonatomic) BOOL useFullUrl; // @synthesize useFullUrl=_useFullUrl;
@property(nonatomic) unsigned int scene; // @synthesize scene=_scene;
- (id)description;

@end

