//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class MMHandoffItem, NSIndexSet;

@protocol MMHandoffServiceExt <NSObject>

@optional
- (void)onUpdateHandoffExpt:(BOOL)arg1;
- (void)onReceiveNewHandoff:(MMHandoffItem *)arg1;
- (void)onClearHandoffUnread;
- (void)didHandoffItemUploadingFromPhone:(MMHandoffItem *)arg1;
- (void)didHandoffItemFailedUploadFromPhone:(MMHandoffItem *)arg1;
- (void)didHandoffItemDeleteFromPhone:(MMHandoffItem *)arg1;
- (void)didHandoffItemFinishUploadFromPhone:(MMHandoffItem *)arg1;
- (void)didHandoffRefreshItem:(int)arg1 withIndexSet:(NSIndexSet *)arg2;
@end

