//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMHandoffTableCellView.h"

@interface MMHandoffFileHelperCell : MMHandoffTableCellView
{
}

- (void)openHandoffByMenu;
- (id)contentMenu;
- (void)updateUI:(id)arg1 withBox:(BOOL)arg2;

@end

