//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSImage, NSString;

@interface MMHandoffItem : NSObject
{
    int _type;
    int _category;
    int _source;
    unsigned int _createTime;
    unsigned int _size;
    unsigned int _uploadSize;
    int _fileStatus;
    NSString *_itemId;
    NSString *_icon;
    NSString *_title;
    NSImage *_iconImage;
    NSString *_fromUserName;
    NSString *_toUserName;
    NSString *_localId;
    NSString *_fileType;
    NSString *_md5;
    NSString *_cdnUrl;
    NSString *_aseKey;
    NSString *_authKey;
    NSString *_serverId;
    NSString *_extId;
    NSString *_filePath;
    NSString *_url;
    NSString *_appName;
    NSString *_appPage;
    NSString *_appId;
    NSString *_mediaId;
    NSString *_sdkVersion;
    NSString *_fileAppId;
}

@property(retain, nonatomic) NSString *fileAppId; // @synthesize fileAppId=_fileAppId;
@property(retain, nonatomic) NSString *sdkVersion; // @synthesize sdkVersion=_sdkVersion;
@property(retain, nonatomic) NSString *mediaId; // @synthesize mediaId=_mediaId;
@property(retain, nonatomic) NSString *appId; // @synthesize appId=_appId;
@property(retain, nonatomic) NSString *appPage; // @synthesize appPage=_appPage;
@property(retain, nonatomic) NSString *appName; // @synthesize appName=_appName;
@property(retain, nonatomic) NSString *url; // @synthesize url=_url;
@property(retain, nonatomic) NSString *filePath; // @synthesize filePath=_filePath;
@property(nonatomic) int fileStatus; // @synthesize fileStatus=_fileStatus;
@property(retain, nonatomic) NSString *extId; // @synthesize extId=_extId;
@property(retain, nonatomic) NSString *serverId; // @synthesize serverId=_serverId;
@property(retain, nonatomic) NSString *authKey; // @synthesize authKey=_authKey;
@property(retain, nonatomic) NSString *aseKey; // @synthesize aseKey=_aseKey;
@property(retain, nonatomic) NSString *cdnUrl; // @synthesize cdnUrl=_cdnUrl;
@property(retain, nonatomic) NSString *md5; // @synthesize md5=_md5;
@property(nonatomic) unsigned int uploadSize; // @synthesize uploadSize=_uploadSize;
@property(nonatomic) unsigned int size; // @synthesize size=_size;
@property(nonatomic) NSString *fileType; // @synthesize fileType=_fileType;
@property(retain, nonatomic) NSString *localId; // @synthesize localId=_localId;
@property(retain, nonatomic) NSString *toUserName; // @synthesize toUserName=_toUserName;
@property(retain, nonatomic) NSString *fromUserName; // @synthesize fromUserName=_fromUserName;
@property(retain, nonatomic) NSImage *iconImage; // @synthesize iconImage=_iconImage;
@property(retain, nonatomic) NSString *title; // @synthesize title=_title;
@property(retain, nonatomic) NSString *icon; // @synthesize icon=_icon;
@property(nonatomic) unsigned int createTime; // @synthesize createTime=_createTime;
@property(nonatomic) int source; // @synthesize source=_source;
@property(nonatomic) int category; // @synthesize category=_category;
@property(nonatomic) int type; // @synthesize type=_type;
@property(retain, nonatomic) NSString *itemId; // @synthesize itemId=_itemId;
- (void).cxx_destruct;

@end

