//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class MMHandoffItem;

@protocol MMHandoffDownloadMgrExt <NSObject>
- (void)onDownloadHandoffItem:(MMHandoffItem *)arg1 withProgress:(double)arg2;
- (void)didExpriedDownloadHandoffItem:(MMHandoffItem *)arg1;
- (void)didFailedDownloadHandoffItem:(MMHandoffItem *)arg1;
- (void)didFinishDownloadHandoffItem:(MMHandoffItem *)arg1;
@end

