//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMService.h"

#import "MMService.h"

@class MMImageEditWindowController, MMTimer, MMToastPanel, NSOperationQueue, NSString;

@interface MMImageEditManger : MMService <MMService>
{
    unsigned long long _completeType;
    unsigned long long _imageIdentifier;
    NSString *_fromChatName;
    NSString *_imageMessageUniqueID;
    NSString *_editImgCompressPath;
    MMImageEditWindowController *_imageEditWindowController;
    MMToastPanel *_toastPanel;
    MMTimer *_screenshotSuccessTimer;
    NSOperationQueue *_operationQueue;
}

@property(retain, nonatomic) NSOperationQueue *operationQueue; // @synthesize operationQueue=_operationQueue;
@property(retain, nonatomic) MMTimer *screenshotSuccessTimer; // @synthesize screenshotSuccessTimer=_screenshotSuccessTimer;
@property(retain, nonatomic) MMToastPanel *toastPanel; // @synthesize toastPanel=_toastPanel;
@property(retain, nonatomic) MMImageEditWindowController *imageEditWindowController; // @synthesize imageEditWindowController=_imageEditWindowController;
@property(retain, nonatomic) NSString *editImgCompressPath; // @synthesize editImgCompressPath=_editImgCompressPath;
@property(retain, nonatomic) NSString *imageMessageUniqueID; // @synthesize imageMessageUniqueID=_imageMessageUniqueID;
@property(retain, nonatomic) NSString *fromChatName; // @synthesize fromChatName=_fromChatName;
@property(nonatomic) unsigned long long imageIdentifier; // @synthesize imageIdentifier=_imageIdentifier;
@property(nonatomic) unsigned long long completeType; // @synthesize completeType=_completeType;
- (void).cxx_destruct;
- (void)closeToast;
- (void)closeToastPanel;
- (void)showCompleteToastWith:(id)arg1;
- (void)stopImageEdit;
- (unsigned char)replaceComposeTextImageWithImage:(id)arg1;
- (void)resetImageEditWindow;
- (unsigned char)startImageEditWith:(id)arg1 startInfo:(id)arg2 completeType:(unsigned long long)arg3;
- (unsigned char)needPreCompressImage:(id)arg1 savePath:(id)arg2;
- (void)onServiceClearData;
- (void)onServiceInit;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

