//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "RFOverlayScrollView.h"

@interface MMImageEditScrollView : RFOverlayScrollView
{
    CDUnknownBlockType _magnificationActionBlock;
}

@property(copy, nonatomic) CDUnknownBlockType magnificationActionBlock; // @synthesize magnificationActionBlock=_magnificationActionBlock;
- (void).cxx_destruct;
- (void)setMagnification:(double)arg1;

@end

