//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMViewController.h"

#import "MMNetExt.h"
#import "SyncExt.h"

@class MMLockViewController, MMLoginOneClickViewController, MMLoginQRCodeViewController, MMLoginStateMachine, MMLoginWaitingConfirmViewController, MMNavigationController, MMTimer, NSString, PushLoginLogic, QRCodeLoginLogic;

@interface MMLoginViewController : MMViewController <SyncExt, MMNetExt>
{
    BOOL _shouldTryAutoAuthWhenNetworkConnected;
    MMLoginStateMachine *_stateMachine;
    QRCodeLoginLogic *_qrCodeLoginLogic;
    PushLoginLogic *_pushLoginLogic;
    MMLoginQRCodeViewController *_qrCodeVIewController;
    MMLoginOneClickViewController *_oneClickViewController;
    MMLoginWaitingConfirmViewController *_waitingConfirmViewController;
    MMNavigationController *_navController;
    MMLockViewController *_lockViewController;
    CDUnknownBlockType _initCGICallbackBlock;
    MMTimer *_checkNetTimer;
    id _keyEventMonitor;
}

@property(retain, nonatomic) id keyEventMonitor; // @synthesize keyEventMonitor=_keyEventMonitor;
@property(retain, nonatomic) MMTimer *checkNetTimer; // @synthesize checkNetTimer=_checkNetTimer;
@property(copy, nonatomic) CDUnknownBlockType initCGICallbackBlock; // @synthesize initCGICallbackBlock=_initCGICallbackBlock;
@property(retain, nonatomic) MMLockViewController *lockViewController; // @synthesize lockViewController=_lockViewController;
@property(retain, nonatomic) MMNavigationController *navController; // @synthesize navController=_navController;
@property(retain, nonatomic) MMLoginWaitingConfirmViewController *waitingConfirmViewController; // @synthesize waitingConfirmViewController=_waitingConfirmViewController;
@property(retain, nonatomic) MMLoginOneClickViewController *oneClickViewController; // @synthesize oneClickViewController=_oneClickViewController;
@property(retain, nonatomic) MMLoginQRCodeViewController *qrCodeVIewController; // @synthesize qrCodeVIewController=_qrCodeVIewController;
@property(retain, nonatomic) PushLoginLogic *pushLoginLogic; // @synthesize pushLoginLogic=_pushLoginLogic;
@property(retain, nonatomic) QRCodeLoginLogic *qrCodeLoginLogic; // @synthesize qrCodeLoginLogic=_qrCodeLoginLogic;
@property(retain, nonatomic) MMLoginStateMachine *stateMachine; // @synthesize stateMachine=_stateMachine;
@property(nonatomic) BOOL shouldTryAutoAuthWhenNetworkConnected; // @synthesize shouldTryAutoAuthWhenNetworkConnected=_shouldTryAutoAuthWhenNetworkConnected;
- (void).cxx_destruct;
- (void)proxySettingsDidChange:(id)arg1;
- (BOOL)isLoginStateReset;
- (void)handleInitFailed;
- (void)handleInitFinish;
- (void)doLoginInitWithCompletion:(CDUnknownBlockType)arg1;
- (void)onNetStatusChange:(int)arg1;
- (void)checkNetwork;
- (void)stopCheckNetTimer;
- (void)startCheckNetTimer;
- (void)removeLockView;
- (void)showLockView;
- (void)onRefreshQRLoginStateIfNeeded;
- (void)fireLoginFailedEvent;
- (void)onAuthFailedWithReason:(id)arg1 errorMsg:(id)arg2;
- (void)onAuthFailedWithAplphaApplyUrl:(id)arg1;
- (void)onInitProcessed:(unsigned int)arg1;
- (void)onInitFail;
- (void)onInitFinish;
- (void)doLogoutLogic;
- (void)stopLogic;
- (void)setupPushLoginLogic;
- (void)setupQRCodeLogic;
- (BOOL)useOneClickLogin;
- (BOOL)useAutoLogin;
- (void)setupAutoLoginEvents;
- (void)setupOneClickEvents;
- (void)setupQRCodeEvents;
- (void)setupCommonEvents;
- (void)setupEvents;
- (void)setupStates;
- (void)setupStateMachine;
- (id)getwaitingConfirmViewController;
- (id)getQRCodeViewController;
- (id)getOneClickViewController;
- (void)removeEventMonitor;
- (void)setupKeyEventHandler;
- (void)dealloc;
- (void)viewDidAppear;
- (void)viewDidLoad;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

