//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSWindowController.h"

#import "IBetaMgrExt.h"
#import "MMTabbarControllerDelegate.h"
#import "NSSplitViewDelegate.h"

@class GetOnlineInfoCGI, MMLoginViewController, MMMainViewController, NSString;

@interface MMMainWindowController : NSWindowController <NSSplitViewDelegate, MMTabbarControllerDelegate, IBetaMgrExt>
{
    MMMainViewController *_mainViewController;
    MMLoginViewController *_loginViewController;
    GetOnlineInfoCGI *_getOnlineInfoCGI;
}

@property(retain, nonatomic) GetOnlineInfoCGI *getOnlineInfoCGI; // @synthesize getOnlineInfoCGI=_getOnlineInfoCGI;
@property(retain, nonatomic) MMLoginViewController *loginViewController; // @synthesize loginViewController=_loginViewController;
@property(retain, nonatomic) MMMainViewController *mainViewController; // @synthesize mainViewController=_mainViewController;
- (void).cxx_destruct;
- (void)onBetaDataLoad;
- (void)makeStandardSize:(id)arg1;
- (void)makeSmaller:(id)arg1;
- (void)makeLarger:(id)arg1;
- (BOOL)validateMenuItem:(id)arg1;
- (void)onAuthFaildForInvalidCGISessionID;
- (void)onAuthFailedWithAplphaApplyUrl:(id)arg1;
- (void)onAuthFailedWithReason:(id)arg1 errorMsg:(id)arg2;
- (void)FFAddRecvFavZZ:(BOOL)arg1;
- (void)onLogoutButtonClick;
- (void)updateWindowTitle;
- (void)adjustMainTranfficLight;
- (void)adjustLoginTranfficLight;
- (void)onApplicationWakeUpFromSleep;
- (void)onApplicationDidResignActive:(id)arg1;
- (void)onApplicationDidBecomeActive:(id)arg1;
- (void)doLoginAnimationWithSize:(struct CGSize)arg1;
- (id)resumeUserLocalSize;
- (void)showMainView:(BOOL)arg1;
- (void)showLoginView;
- (BOOL)isLoginStateReset;
- (void)doLoginInitWithCompletion:(CDUnknownBlockType)arg1;
- (void)removeLoginView;
- (void)removeMainView;
- (id)tabButtonAtIndex:(int)arg1;
- (void)setWindowResizable:(BOOL)arg1;
- (struct CGRect)window:(id)arg1 willPositionSheet:(id)arg2 usingRect:(struct CGRect)arg3;
- (void)windowDidLoad;
- (void)dealloc;
- (id)initWithWindowNibName:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

