//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSWindow.h"

#import "AccountServiceExt.h"
#import "NSWindowDelegate.h"

@class NSString, NSTitlebarAccessoryViewController;

@interface MMMainWindow : NSWindow <NSWindowDelegate, AccountServiceExt>
{
    BOOL _isFullScreen;
    NSTitlebarAccessoryViewController *_titlebarController;
}

@property(retain, nonatomic) NSTitlebarAccessoryViewController *titlebarController; // @synthesize titlebarController=_titlebarController;
@property(nonatomic) BOOL isFullScreen; // @synthesize isFullScreen=_isFullScreen;
- (void).cxx_destruct;
- (void)windowWillEnterFullScreenAction:(id)arg1;
- (void)windowWillExitFullScreenAction:(id)arg1;
- (void)onUserLogout;
- (void)windowDidDeminiaturize:(id)arg1;
- (void)windowDidMiniaturize:(id)arg1;
- (void)toggleFullScreen:(id)arg1;
- (void)adjustTitleBarSubViews;
- (void)onCloseButtonClicked;
- (void)addCloseButtonAction;
- (BOOL)makeFirstResponder:(id)arg1;
- (BOOL)isMovableByWindowBackground;
- (void)dealloc;
- (void)awakeFromNib;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

