//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "RFOverlayScrollView.h"

@class MMTableFreshView;

@interface MMMessageScrollView : RFOverlayScrollView
{
    BOOL _isRefreshing;
    BOOL _overRefreshView;
    MMTableFreshView *_refreshHeader;
    MMTableFreshView *_refreshFooter;
}

@property(retain, nonatomic) MMTableFreshView *refreshFooter; // @synthesize refreshFooter=_refreshFooter;
@property(retain, nonatomic) MMTableFreshView *refreshHeader; // @synthesize refreshHeader=_refreshHeader;
@property(nonatomic) BOOL overRefreshView; // @synthesize overRefreshView=_overRefreshView;
@property(readonly, nonatomic) BOOL isRefreshing; // @synthesize isRefreshing=_isRefreshing;
- (void).cxx_destruct;
- (double)maxmumScroll;
- (double)minimumScroll;
- (BOOL)isInPullUpVisiableRect;
- (BOOL)isInPullDownVisiableRect;
- (void)resetHeaderFooter;
- (void)footerEndRefreshing;
- (void)footerBeginRefreshing;
- (void)headerEndRefreshing;
- (void)headerBeginRefreshing;
- (void)scrollWheel:(id)arg1;
- (BOOL)shouldAutoScrollToBottom;
- (BOOL)reachedBottom;
- (BOOL)reachedTop;
- (BOOL)isAllMessagesVisible;
- (void)createFreshView;
- (void)viewDidMoveToWindow;
- (void)dealloc;
- (id)init;

@end

