//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMWindowController.h"

#import "NSSearchFieldDelegate.h"
#import "NSTextFieldDelegate.h"
#import "NSWindowDelegate.h"

@class MMCacheViewController, MMSearchField, MMTextField, NSObject<OS_dispatch_source>, NSString, NSTabView, NSToolbar;

@interface MMMemoryMonitorController : MMWindowController <NSTextFieldDelegate, NSSearchFieldDelegate, NSWindowDelegate>
{
    NSTabView *_tabView;
    MMTextField *_textField;
    NSToolbar *_toolBar;
    MMSearchField *_searchField;
    MMCacheViewController *_cacheVC;
    NSObject<OS_dispatch_source> *_timer;
}

@property(retain, nonatomic) NSObject<OS_dispatch_source> *timer; // @synthesize timer=_timer;
@property(retain, nonatomic) MMCacheViewController *cacheVC; // @synthesize cacheVC=_cacheVC;
@property(retain, nonatomic) MMSearchField *searchField; // @synthesize searchField=_searchField;
@property(retain, nonatomic) NSToolbar *toolBar; // @synthesize toolBar=_toolBar;
@property(retain, nonatomic) MMTextField *textField; // @synthesize textField=_textField;
@property(retain, nonatomic) NSTabView *tabView; // @synthesize tabView=_tabView;
- (void).cxx_destruct;
- (void)controlTextDidEndEditing:(id)arg1;
- (void)setupTimer;
- (void)refreshMemoryTextField;
- (void)setupTabView;
- (void)close;
- (void)clear;
- (void)showWindow:(id)arg1;
- (void)dealloc;
- (void)awakeFromNib;
- (void)windowWillClose:(id)arg1;
- (void)windowDidLoad;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

