//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMWindowController.h"

#import "NSWindowDelegate.h"

@class NSString, NSTextField, NSTextView, NSURLConnection;

@interface MMNetworkDebugWindowController : MMWindowController <NSWindowDelegate>
{
    NSTextField *_inputTextField;
    NSTextView *_outputTextView;
    NSURLConnection *_connection;
}

@property(retain, nonatomic) NSURLConnection *connection; // @synthesize connection=_connection;
@property(retain, nonatomic) NSTextView *outputTextView; // @synthesize outputTextView=_outputTextView;
@property(retain, nonatomic) NSTextField *inputTextField; // @synthesize inputTextField=_inputTextField;
- (void).cxx_destruct;
- (void)sendHttpRequest:(id)arg1;
- (void)windowWillClose:(id)arg1;
- (void)windowDidLoad;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

