//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableDictionary;

@interface MMProxySettingsStorage : NSObject
{
    NSMutableDictionary *_proxyInfo;
    struct ProxyInfo _marsProxyInfo;
}

+ (id)sharedInstance;
@property(nonatomic) struct ProxyInfo marsProxyInfo; // @synthesize marsProxyInfo=_marsProxyInfo;
@property(retain, nonatomic) NSMutableDictionary *proxyInfo; // @synthesize proxyInfo=_proxyInfo;
- (id).cxx_construct;
- (void).cxx_destruct;
- (void)storeProxyInfoWithType:(int)arg1 Host:(id)arg2 IP:(id)arg3 port:(id)arg4 username:(id)arg5 password:(id)arg6;
- (void)closeProxySettings;
- (unsigned char)testProxy:(struct ProxyInfo *)arg1 isDirect:(unsigned char)arg2;
- (void)setProxyInfoWithType:(int)arg1 Host:(id)arg2 IP:(id)arg3 port:(id)arg4 username:(id)arg5 password:(id)arg6;
- (struct ProxyInfo)setupMarsProxyInfo;
- (unsigned char)isUsingProxy;
- (void)initProxy;
- (struct ProxyInfo)genMarsProxyInfo;
- (id)init;

@end

