//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface MMProxyUtil : NSObject
{
}

+ (id)genStandardHostWith:(id)arg1;
+ (BOOL)isPureInt:(id)arg1;
+ (BOOL)isValidPort:(id)arg1;
+ (BOOL)isValidIP:(id)arg1;

@end

