//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMView.h"

@interface MMPreviewEventView : MMView
{
    CDUnknownBlockType _menuForEventBlock;
}

@property(copy, nonatomic) CDUnknownBlockType menuForEventBlock; // @synthesize menuForEventBlock=_menuForEventBlock;
- (void).cxx_destruct;
- (id)menuForEvent:(id)arg1;

@end

