//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMWindow.h"

@interface MMPreviewWindow : MMWindow
{
    id <MMPreviewWindowDelegate> _closeDelegate;
}

@property(nonatomic) __weak id <MMPreviewWindowDelegate> closeDelegate; // @synthesize closeDelegate=_closeDelegate;
- (void).cxx_destruct;
- (BOOL)performKeyEquivalent:(id)arg1;

@end

