//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSViewController.h"

@class MMPreviewIKImageView, MMPreviewIKScrollView, MMPreviewVideoPlayerView, MMQLPreviewPageInfo, MMTimer, NSImageView;

@interface MMPreviewViewController : NSViewController
{
    BOOL _isSwapingMouse;
    BOOL _isTouchEdge;
    BOOL _shouldPlayVideo;
    BOOL _shouldRefreshThumb;
    CDUnknownBlockType _zoomImageBlock;
    CDUnknownBlockType _restoreImageBlock;
    CDUnknownBlockType _restoreActionBlock;
    MMPreviewIKScrollView *_ikScrollView;
    MMPreviewVideoPlayerView *_videoPlayerView;
    MMQLPreviewPageInfo *_pageInfo;
    NSImageView *_thumbImageView;
    MMPreviewIKImageView *_ikImageView;
    double _originZoomFactor;
    double _originFullScreenZoomFactor;
    double _diff;
    MMTimer *_scrollEndtimer;
    struct CGSize _originFullScreenImageSize;
    struct CGPoint _lastMousePoint;
}

@property(retain, nonatomic) MMTimer *scrollEndtimer; // @synthesize scrollEndtimer=_scrollEndtimer;
@property(nonatomic) struct CGPoint lastMousePoint; // @synthesize lastMousePoint=_lastMousePoint;
@property(nonatomic) double diff; // @synthesize diff=_diff;
@property(nonatomic) BOOL shouldRefreshThumb; // @synthesize shouldRefreshThumb=_shouldRefreshThumb;
@property(nonatomic) struct CGSize originFullScreenImageSize; // @synthesize originFullScreenImageSize=_originFullScreenImageSize;
@property(nonatomic) double originFullScreenZoomFactor; // @synthesize originFullScreenZoomFactor=_originFullScreenZoomFactor;
@property(nonatomic) double originZoomFactor; // @synthesize originZoomFactor=_originZoomFactor;
@property __weak MMPreviewIKImageView *ikImageView; // @synthesize ikImageView=_ikImageView;
@property(retain, nonatomic) NSImageView *thumbImageView; // @synthesize thumbImageView=_thumbImageView;
@property(nonatomic) BOOL shouldPlayVideo; // @synthesize shouldPlayVideo=_shouldPlayVideo;
@property(nonatomic) BOOL isTouchEdge; // @synthesize isTouchEdge=_isTouchEdge;
@property(retain, nonatomic) MMQLPreviewPageInfo *pageInfo; // @synthesize pageInfo=_pageInfo;
@property(nonatomic) BOOL isSwapingMouse; // @synthesize isSwapingMouse=_isSwapingMouse;
@property(retain, nonatomic) MMPreviewVideoPlayerView *videoPlayerView; // @synthesize videoPlayerView=_videoPlayerView;
@property __weak MMPreviewIKScrollView *ikScrollView; // @synthesize ikScrollView=_ikScrollView;
@property(copy, nonatomic) CDUnknownBlockType restoreActionBlock; // @synthesize restoreActionBlock=_restoreActionBlock;
@property(copy, nonatomic) CDUnknownBlockType restoreImageBlock; // @synthesize restoreImageBlock=_restoreImageBlock;
@property(copy, nonatomic) CDUnknownBlockType zoomImageBlock; // @synthesize zoomImageBlock=_zoomImageBlock;
- (void).cxx_destruct;
- (void)addFullScreenToolBar:(id)arg1;
- (void)onScrollViewBoundsDidChanged:(id)arg1;
- (BOOL)startPlayVideoWith:(BOOL)arg1;
- (void)rotateImage;
- (void)standardizeImage;
- (void)restoreImage;
- (void)updateScrollPoint:(BOOL)arg1;
- (void)updateStoreImageStatus:(BOOL)arg1;
- (double)screenScale;
- (void)standardSize;
- (void)zoomOut;
- (void)zoomIn;
- (void)updateZoomImageStatus;
- (void)resetAdjust;
- (void)_setupVideoPlayerView;
- (void)setupWithUrlInfo:(id)arg1;
- (BOOL)isInvalidUrlWithContact:(id)arg1;
- (void)setupWithAvatarPageInfo;
- (void)setupWithChatRecordPageInfo:(id)arg1;
- (void)setupWithFavPageInfo:(id)arg1;
- (void)setupWithMsgPageInfo:(id)arg1;
- (void)removeThumbWhenResizing;
- (void)updateWindowResizeZooming;
- (void)updateExitFullScreenZooming;
- (void)updateEnterFullScreenZooming;
- (void)updateIKImageZoomingForAvatar;
- (void)updateIKImageZooming;
- (void)showIKImageDelay;
- (void)setPreviewIKImageViewWithData:(id)arg1;
- (void)setPreviewIKImageViewWithAvatar:(id)arg1;
- (void)setThumbImageViewWithImage:(id)arg1;
- (void)setThumbImageViewWithFavImage:(id)arg1 thumbImage:(id)arg2 dataField:(id)arg3;
- (void)setThumbImageViewWithAvatarImage:(id)arg1 hdSize:(struct CGSize)arg2;
- (void)resetMagnifyEvent;
- (void)resetIKImageView;
- (void)stopScrollTimer;
- (void)resetScrollTimer;
- (void)disableScrollViewDrag;
- (void)enableScrollViewDrag;
- (void)setupWithPageInfo:(id)arg1;
- (void)viewDidDisappear;
- (void)viewWillDisappear;
- (void)viewWillAppear;
- (void)dealloc;
- (void)viewDidLoad;

@end

