//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMService.h"

#import "MMService.h"

@class MMPreviewWindowController, NSString, NSWindow;

@interface MMPreviewUIMgr : MMService <MMService>
{
    BOOL _shouldShowMainWindow;
    BOOL _useAnimationImage;
    BOOL _shouldOrderFrontWindow;
    NSWindow *_prevWindow;
    MMPreviewWindowController *_previewPanelWindowController;
    struct CGRect _mouseDownRect;
}

@property(retain, nonatomic) MMPreviewWindowController *previewPanelWindowController; // @synthesize previewPanelWindowController=_previewPanelWindowController;
@property(nonatomic) BOOL shouldOrderFrontWindow; // @synthesize shouldOrderFrontWindow=_shouldOrderFrontWindow;
@property(nonatomic) __weak NSWindow *prevWindow; // @synthesize prevWindow=_prevWindow;
@property(nonatomic) BOOL useAnimationImage; // @synthesize useAnimationImage=_useAnimationImage;
@property(nonatomic) BOOL shouldShowMainWindow; // @synthesize shouldShowMainWindow=_shouldShowMainWindow;
@property(nonatomic) struct CGRect mouseDownRect; // @synthesize mouseDownRect=_mouseDownRect;
- (void).cxx_destruct;
- (void)_ensureClosePreviewWindow;
- (void)setupVideoPlayerView;
- (void)resetVideoStatus;
- (void)loadVideoWithUrl:(id)arg1;
- (void)previewPanelHandleAvatarOfCurrentContact:(id)arg1;
- (void)previewPanelHandleUrlsImage:(id)arg1;
- (void)previewPanelHandleCurrentImageParaInfo:(id)arg1 paraInfoList:(id)arg2;
- (void)previewPanelHandleCurrentImageDataField:(id)arg1 parentDataField:(id)arg2;
- (void)previewPanelHandleCurrentImageDataField:(id)arg1 parentMessage:(id)arg2 parentFavItem:(id)arg3;
- (void)previewPanelHandleMediaMessage:(id)arg1 chatContact:(id)arg2 order:(unsigned long long)arg3;
- (void)previewPanelHandleImageFavItem:(id)arg1 favItemList:(id)arg2;
- (void)openWithUrls:(id)arg1;
- (void)openWithAvatarContact:(id)arg1;
- (void)openWithCurrentParaInfo:(id)arg1 paraInfoList:(id)arg2;
- (void)openWithCurrentDataField:(id)arg1 parentDataField:(id)arg2;
- (void)openWithCurrentDataField:(id)arg1 parentMessage:(id)arg2 orParentFavItem:(id)arg3;
- (void)openWithFavItemList:(id)arg1 AndInitialSelectedFavItem:(id)arg2;
- (void)openWithChatContact:(id)arg1 InitialSelectedMessage:(id)arg2 AndOrder:(unsigned long long)arg3;
- (BOOL)isPreviewCanHandleCurrentFavItem:(id)arg1;
- (BOOL)isPreviewCanHandleCurrentMessage:(id)arg1;
- (void)closePreviewWindow;
- (id)currentPreviewWindow;
- (double)currentPreviewScreenScale;
- (id)currentPreviewScreen;
- (BOOL)isCurrentPreviewWindowFullscreen;
- (void)onServiceClearData;
- (void)onServiceInit;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

