//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "AccountServiceExt.h"

@class MMCache, NSObject<OS_dispatch_queue>, NSString;

@interface MMPreviewHDImageCacheLogic : NSObject <AccountServiceExt>
{
    MMCache *_innerCache;
    NSObject<OS_dispatch_queue> *_cacheQueue;
}

+ (id)shareInstance;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *cacheQueue; // @synthesize cacheQueue=_cacheQueue;
@property(retain, nonatomic) MMCache *innerCache; // @synthesize innerCache=_innerCache;
- (void).cxx_destruct;
- (BOOL)isHDImageCached:(id)arg1;
- (void)removeHDImageDataFromCache:(id)arg1;
- (id)getHDImageDataFromCache:(id)arg1;
- (void)originalImageDataWithDataField:(id)arg1 compeletion:(CDUnknownBlockType)arg2;
- (void)originalImageDataWithPreviewItem:(id)arg1 compeletion:(CDUnknownBlockType)arg2;
- (void)ayncCreateHDImageDataCache:(id)arg1 ForKey:(id)arg2;
- (void)onUserLogout;
- (void)destroy;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

