//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMCustomDisableButton.h"

@interface MMPreviewToggleRestoreButton : MMCustomDisableButton
{
    unsigned long long _type;
}

@property(nonatomic) unsigned long long type; // @synthesize type=_type;
- (void)setEnabled:(BOOL)arg1;

@end

