//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMWindowController.h"

#import "NSWindowDelegate.h"

@class NSButton, NSString, NSTextField;

@interface MMRecoverWindowController : MMWindowController <NSWindowDelegate>
{
    NSButton *_uploadDumpButton;
    NSTextField *_helpInfo;
    NSButton *_diskDetectButton;
    NSButton *_DBDetectButton;
}

@property __weak NSButton *DBDetectButton; // @synthesize DBDetectButton=_DBDetectButton;
@property __weak NSButton *diskDetectButton; // @synthesize diskDetectButton=_diskDetectButton;
@property(retain, nonatomic) NSTextField *helpInfo; // @synthesize helpInfo=_helpInfo;
@property(retain, nonatomic) NSButton *uploadDumpButton; // @synthesize uploadDumpButton=_uploadDumpButton;
- (void).cxx_destruct;
- (void)openLagLogDir:(id)arg1;
- (void)openLocalLogDir:(id)arg1;
- (void)openLocalDataDir:(id)arg1;
- (void)recoverSessionListFromLocal:(id)arg1;
- (void)repairSessionList:(id)arg1;
- (void)repairContactList:(id)arg1;
- (void)onDBDetectButtonClick:(id)arg1;
- (void)onDiskDetectButtonClick:(id)arg1;
- (void)cleanMsgDataAndRestart:(id)arg1;
- (void)cleanFavDataAndRestart:(id)arg1;
- (void)cleanDataAndRestart:(id)arg1;
- (void)cleanWebkitCache:(id)arg1;
- (void)windowWillClose:(id)arg1;
- (void)awakeFromNib;
- (void)windowDidLoad;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

