//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMView.h"

@interface MMReaderWrapView : MMView
{
    CDUnknownBlockType _mouseUpEventBlock;
    CDUnknownBlockType _mouseDownEventBlock;
    CDUnknownBlockType _rightMouseDownEventBlock;
    CDUnknownBlockType _mouseDragEventBlock;
    struct CGPoint _mouseDownLocation;
}

@property(nonatomic) struct CGPoint mouseDownLocation; // @synthesize mouseDownLocation=_mouseDownLocation;
@property(copy, nonatomic) CDUnknownBlockType mouseDragEventBlock; // @synthesize mouseDragEventBlock=_mouseDragEventBlock;
@property(copy, nonatomic) CDUnknownBlockType rightMouseDownEventBlock; // @synthesize rightMouseDownEventBlock=_rightMouseDownEventBlock;
@property(copy, nonatomic) CDUnknownBlockType mouseDownEventBlock; // @synthesize mouseDownEventBlock=_mouseDownEventBlock;
@property(copy, nonatomic) CDUnknownBlockType mouseUpEventBlock; // @synthesize mouseUpEventBlock=_mouseUpEventBlock;
- (void).cxx_destruct;
- (BOOL)notMoveFar:(id)arg1;
- (void)mouseDragged:(id)arg1;
- (void)rightMouseDown:(id)arg1;
- (void)mouseUp:(id)arg1;
- (void)mouseDown:(id)arg1;

@end

