//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSTextView.h"

#import "MMTextAttachmentCellDelegate.h"

@class NSMutableDictionary, NSMutableSet, NSString;

@interface MMRichAttachmentBaseTextView : NSTextView <MMTextAttachmentCellDelegate>
{
    BOOL _typingAttributesInProgress;
    NSMutableDictionary *_registerViewDictionary;
    NSMutableSet *_attachmentViews;
    id <MMRichAttachmentBaseTextViewDelegate> _richAttachmentDelegate;
}

+ (id)contentDefaultParagraphStyle;
+ (id)contentDefaultTextAttribute;
@property(nonatomic) BOOL typingAttributesInProgress; // @synthesize typingAttributesInProgress=_typingAttributesInProgress;
@property(nonatomic) __weak id <MMRichAttachmentBaseTextViewDelegate> richAttachmentDelegate; // @synthesize richAttachmentDelegate=_richAttachmentDelegate;
@property(retain, nonatomic) NSMutableSet *attachmentViews; // @synthesize attachmentViews=_attachmentViews;
@property(retain, nonatomic) NSMutableDictionary *registerViewDictionary; // @synthesize registerViewDictionary=_registerViewDictionary;
- (void).cxx_destruct;
- (struct CGRect)cellFrameForAttachmentCell:(id)arg1 withWidthConstrain:(double)arg2;
- (void)textAttachmentCell:(id)arg1 didLoadImage:(id)arg2;
- (id)attachmentViewForAttachment:(id)arg1;
- (void)scrollViewBoundsChange:(id)arg1;
- (void)_calculateAttachmentBounds:(id)arg1;
- (void)_calculateAttachmentsBounds;
- (id)_reusableAttachmentViewForAttachment:(id)arg1;
- (void)invalidateAttachmentsInRange:(struct _NSRange)arg1;
- (BOOL)_shouldChangeTextInRange:(struct _NSRange)arg1 replacementText:(id)arg2 attachmentList:(id *)arg3;
- (void)_didDeleteAttachments:(id)arg1;
- (void)_willDeleteAttachments:(id)arg1;
- (BOOL)hasText;
- (struct _NSRange)fullRange;
- (id)attributesInSelectedRange;
- (id)attachmentsInRange:(struct _NSRange)arg1;
- (void)replaceStringInRange:(struct _NSRange)arg1 withAttachment:(id)arg2;
- (BOOL)replaceTextInRange:(struct _NSRange)arg1 withAttributeText:(id)arg2;
- (id)dequeueReusableAttachmentViewWithIdentifier:(id)arg1;
- (void)registerClass:(Class)arg1 forAttachmentViewWithReuseIdentifier:(id)arg2;
- (void)setAttributedText:(id)arg1;
- (void)deleteBackward:(id)arg1;
- (void)dealloc;
- (void)commitInit;
- (id)initWithFrame:(struct CGRect)arg1 textContainer:(id)arg2;
- (id)initWithFrame:(struct CGRect)arg1 customTextStorage:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

