//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class MMAttachmentReusableView, MMRichAttachmentBaseTextView, MMTextAttachmentCell, NSArray, NSString;

@protocol MMRichAttachmentBaseTextViewDelegate <NSObject>
- (MMAttachmentReusableView *)textView:(MMRichAttachmentBaseTextView *)arg1 attachmentViewWithAttachment:(MMTextAttachmentCell *)arg2;

@optional
- (void)textView:(MMRichAttachmentBaseTextView *)arg1 didDeleteAttachments:(NSArray *)arg2;
- (void)textView:(MMRichAttachmentBaseTextView *)arg1 willDeleteAttachments:(NSArray *)arg2;
- (BOOL)textView:(MMRichAttachmentBaseTextView *)arg1 shouldChangeAttachments:(NSArray *)arg2 andTextInRange:(struct _NSRange)arg3 replacementText:(NSString *)arg4;
@end

