//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSTableRowView.h"

@class NSProgressIndicator;

@interface MMSessionPickerListLoadingRowView : NSTableRowView
{
    NSProgressIndicator *_loadingIndicator;
}

@property(retain, nonatomic) NSProgressIndicator *loadingIndicator; // @synthesize loadingIndicator=_loadingIndicator;
- (void).cxx_destruct;
- (id)menuForEvent:(id)arg1;
- (void)setupWithSessionPickerRow:(id)arg1;
- (void)prepareForReuse;
- (void)_commonInit;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

