//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableArray;

@interface MMSearchResultContainer : NSObject
{
    NSMutableArray *_contactResults;
    NSMutableArray *_groupResults;
    NSMutableArray *_oaResults;
    NSMutableArray *_favResults;
    NSMutableArray *_chatLogResults;
    unsigned long long _logicSearchResultFlag;
}

@property(nonatomic) unsigned long long logicSearchResultFlag; // @synthesize logicSearchResultFlag=_logicSearchResultFlag;
@property(retain, nonatomic) NSMutableArray *chatLogResults; // @synthesize chatLogResults=_chatLogResults;
@property(retain, nonatomic) NSMutableArray *favResults; // @synthesize favResults=_favResults;
@property(retain, nonatomic) NSMutableArray *oaResults; // @synthesize oaResults=_oaResults;
@property(retain, nonatomic) NSMutableArray *groupResults; // @synthesize groupResults=_groupResults;
@property(retain, nonatomic) NSMutableArray *contactResults; // @synthesize contactResults=_contactResults;
- (void).cxx_destruct;
- (id)init;

@end

