//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMSearchTableCellView.h"

@class MMAvatarImageView, MMImageView, MMTextField;

@interface MMSearchContactTableCellView : MMSearchTableCellView
{
    id <MMSearchContactCellDelegate> _delegate;
    MMAvatarImageView *_avatarImageView;
    MMTextField *_nicknameLabel;
    MMTextField *_descriptionLabel;
    MMImageView *_openIMIcon;
}

@property(retain, nonatomic) MMImageView *openIMIcon; // @synthesize openIMIcon=_openIMIcon;
@property(retain, nonatomic) MMTextField *descriptionLabel; // @synthesize descriptionLabel=_descriptionLabel;
@property(retain, nonatomic) MMTextField *nicknameLabel; // @synthesize nicknameLabel=_nicknameLabel;
@property(retain, nonatomic) MMAvatarImageView *avatarImageView; // @synthesize avatarImageView=_avatarImageView;
@property(nonatomic) __weak id <MMSearchContactCellDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (BOOL)performDragOperation:(id)arg1;
- (void)draggingEnded:(id)arg1;
- (void)draggingExited:(id)arg1;
- (unsigned long long)draggingEntered:(id)arg1;
- (BOOL)prepareForDragOperation:(id)arg1;
- (void)mouseUp:(id)arg1;
- (void)mouseDown:(id)arg1;
- (id)menuForEvent:(id)arg1;
- (void)layoutAvatar;
- (id)prefixStringFormatWithType:(unsigned long long)arg1;
- (id)matchedStringWithContact:(id)arg1 type:(unsigned long long)arg2;
- (void)layoutOpenIMIcon;
- (void)layoutLabels;
- (void)resizeSubviewsWithOldSize:(struct CGSize)arg1;
- (id)makeNameLabelAttrString:(id)arg1;
- (id)makeDescLabelAttrString:(id)arg1;
- (id)getCurrentContact;
- (void)populateWithResultItem:(id)arg1 keyword:(id)arg2;
- (void)prepareForReuse;
- (void)setSelected:(BOOL)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

