//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMSidebarRowView.h"

@interface MMSidebarContactRowView : MMSidebarRowView
{
}

- (void)dealloc;
- (void)prepareForReuse;
- (void)mouseDown:(id)arg1;
- (void)resizeSubviewsWithOldSize:(struct CGSize)arg1;
- (void)relayoutSubView;
- (id)initWithFrame:(struct CGRect)arg1;

@end

