//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMWindowController.h"

#import "NSWindowDelegate.h"

@class MMSpaceCleanViewController, NSString;

@interface MMSpaceCleanWindowController : MMWindowController <NSWindowDelegate>
{
    MMSpaceCleanViewController *_spaceViewController;
}

@property(retain, nonatomic) MMSpaceCleanViewController *spaceViewController; // @synthesize spaceViewController=_spaceViewController;
- (void).cxx_destruct;
- (void)showMainViewController;
- (void)windowWillClose:(id)arg1;
- (void)dealloc;
- (void)windowDidLoad;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

