//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMViewController.h"

@class MMOutlineButton, NSProgressIndicator, NSTextField;

@interface MMSpaceCleanCacheViewController : MMViewController
{
    NSTextField *_totalSizeLabel;
    NSTextField *_cleanStatusLabel;
    NSTextField *_totalSpaceTipsLabel;
    MMOutlineButton *_manageSessionBtn;
    NSProgressIndicator *_loadingIndicator;
}

@property(retain, nonatomic) NSProgressIndicator *loadingIndicator; // @synthesize loadingIndicator=_loadingIndicator;
@property(retain, nonatomic) MMOutlineButton *manageSessionBtn; // @synthesize manageSessionBtn=_manageSessionBtn;
@property(retain, nonatomic) NSTextField *totalSpaceTipsLabel; // @synthesize totalSpaceTipsLabel=_totalSpaceTipsLabel;
@property(retain, nonatomic) NSTextField *cleanStatusLabel; // @synthesize cleanStatusLabel=_cleanStatusLabel;
@property(retain, nonatomic) NSTextField *totalSizeLabel; // @synthesize totalSizeLabel=_totalSizeLabel;
- (void).cxx_destruct;
- (void)showSessionViewController;
- (void)updateTotalSizeLabel;
- (void)clickManageSessionBtn:(id)arg1;
- (void)stopLoadData;
- (void)startLoadData;
- (void)viewWillAppear;
- (void)viewDidLoad;
- (id)init;

@end

