//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMView.h"

@interface MMStickerCollectionEventView : MMView
{
    CDUnknownBlockType _scrollWheelEventBlock;
}

@property(copy, nonatomic) CDUnknownBlockType scrollWheelEventBlock; // @synthesize scrollWheelEventBlock=_scrollWheelEventBlock;
- (void).cxx_destruct;
- (void)scrollWheel:(id)arg1;

@end

