//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSView.h"

@class MMTimer, NSImageView, NSString, NSTextField, NSVisualEffectView;

@interface MMStateToastView : NSView
{
    NSView *_containerView;
    NSVisualEffectView *_effectView;
    NSTextField *_textField;
    NSImageView *_imageView;
    MMTimer *_timer;
    NSString *_tips;
    CDUnknownBlockType _mouseDownInsideBlock;
}

@property(copy, nonatomic) CDUnknownBlockType mouseDownInsideBlock; // @synthesize mouseDownInsideBlock=_mouseDownInsideBlock;
@property(retain, nonatomic) NSString *tips; // @synthesize tips=_tips;
@property(retain, nonatomic) MMTimer *timer; // @synthesize timer=_timer;
@property(retain, nonatomic) NSImageView *imageView; // @synthesize imageView=_imageView;
@property(retain, nonatomic) NSTextField *textField; // @synthesize textField=_textField;
@property(retain, nonatomic) NSVisualEffectView *effectView; // @synthesize effectView=_effectView;
@property(retain, nonatomic) NSView *containerView; // @synthesize containerView=_containerView;
- (void).cxx_destruct;
- (void)setImageName:(id)arg1;
- (void)setToastTips:(id)arg1;
- (void)mouseDown:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

