//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMMessageCellView.h"

#import "EmoticonDownloadMgrExt.h"
#import "ToastViewDelegate.h"

@class NSButton, NSImageView, NSProgressIndicator, NSString;

@interface MMStickerMessageCellView : MMMessageCellView <EmoticonDownloadMgrExt, ToastViewDelegate>
{
    BOOL _isNeedSyncReloadImage;
    NSProgressIndicator *_loadingIndicator;
    NSImageView *_stickerImageView;
    NSButton *_downloadErrorIndicatorAccessory;
}

+ (struct CGSize)displaySizeWithStickerImg:(id)arg1;
+ (double)cellHeightWithMessage:(id)arg1 constrainedToWidth:(double)arg2;
@property(retain, nonatomic) NSButton *downloadErrorIndicatorAccessory; // @synthesize downloadErrorIndicatorAccessory=_downloadErrorIndicatorAccessory;
@property(nonatomic) BOOL isNeedSyncReloadImage; // @synthesize isNeedSyncReloadImage=_isNeedSyncReloadImage;
@property(retain, nonatomic) NSImageView *stickerImageView; // @synthesize stickerImageView=_stickerImageView;
@property(retain, nonatomic) NSProgressIndicator *loadingIndicator; // @synthesize loadingIndicator=_loadingIndicator;
- (void).cxx_destruct;
- (void)reDownloadMessage;
- (void)layoutDownloadAccessories;
- (void)setChoosable:(BOOL)arg1;
- (BOOL)allowChoose;
- (void)showAlertFavEmoticon:(id)arg1;
- (void)showToastViewAddFailFavEmoticon;
- (void)showToastViewAddedFavEmoticon;
- (void)showToastViewWarningFavEmoticon:(id)arg1;
- (void)showToastViewAddingFavEmoticon;
- (void)contextMenuAddEmotion;
- (id)getOperationMenuItem;
- (struct CGRect)clickableArea;
- (void)updateStickerWithImage:(id)arg1;
- (void)emoticonDownloadFailed:(id)arg1;
- (void)emoticonDownloadFinished:(id)arg1;
- (void)restartPlaying;
- (void)callForDelegate;
- (void)populateWithMessage:(id)arg1;
- (void)prepareForReuse;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

