//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMView.h"

@interface MMStickerPickerEventView : MMView
{
    CDUnknownBlockType _keyDownEventBlock;
    CDUnknownBlockType _keyUpEventBlock;
}

@property(copy, nonatomic) CDUnknownBlockType keyUpEventBlock; // @synthesize keyUpEventBlock=_keyUpEventBlock;
@property(copy, nonatomic) CDUnknownBlockType keyDownEventBlock; // @synthesize keyDownEventBlock=_keyDownEventBlock;
- (void).cxx_destruct;
- (void)keyUp:(id)arg1;
- (void)keyDown:(id)arg1;

@end

