//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableAttributedString;

@interface MMSystemLinkInfo : NSObject
{
    NSMutableAttributedString *_msgContent;
    unsigned long long _scene;
}

@property(nonatomic) unsigned long long scene; // @synthesize scene=_scene;
@property(retain, nonatomic) NSMutableAttributedString *msgContent; // @synthesize msgContent=_msgContent;
- (void).cxx_destruct;
- (void)formattedLinkAttributed:(id)arg1 value:(id)arg2 range:(struct _NSRange)arg3;
- (id)baseTextAttributesWithSize;
- (id)formattedSystemMessage:(id)arg1;
- (void)formattedMsgContent:(id)arg1;
- (void)parseShowMoreLinkInfo:(id)arg1;
- (void)parseNewXMLLinkInfo:(id)arg1;
- (void)parseLocalLinkInfo;
- (void)parseCustomLinkInfo;
- (void)parseNormalLinkInfo;
- (void)parseLinkInfoFromSysMessageData:(id)arg1;
- (id)initWithScene:(unsigned long long)arg1;

@end

