//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMWindowController.h"

#import "NSWindowDelegate.h"

@class MMOutlineButton, NSString, NSTextField, NSView;

@interface MMTechSupportWindowController : MMWindowController <NSWindowDelegate>
{
    NSView *_bgContainer;
    NSTextField *_jietuTitle;
    NSTextField *_jietuDesc;
    MMOutlineButton *_jietuOfficalWebsite;
}

@property __weak MMOutlineButton *jietuOfficalWebsite; // @synthesize jietuOfficalWebsite=_jietuOfficalWebsite;
@property __weak NSTextField *jietuDesc; // @synthesize jietuDesc=_jietuDesc;
@property __weak NSTextField *jietuTitle; // @synthesize jietuTitle=_jietuTitle;
@property __weak NSView *bgContainer; // @synthesize bgContainer=_bgContainer;
- (void).cxx_destruct;
- (void)setupJietu;
- (void)windowWillClose:(id)arg1;
- (void)windowDidLoad;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

