//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSTextField.h"

@interface MMTextField : NSTextField
{
    BOOL _ignoreMouseEvent;
    int _vibrancyMode;
    CDUnknownBlockType _mouseDownBlock;
    CDUnknownBlockType _mouseUpBlock;
    CDUnknownBlockType _menuForEventBlock;
}

@property(copy, nonatomic) CDUnknownBlockType menuForEventBlock; // @synthesize menuForEventBlock=_menuForEventBlock;
@property(copy, nonatomic) CDUnknownBlockType mouseUpBlock; // @synthesize mouseUpBlock=_mouseUpBlock;
@property(copy, nonatomic) CDUnknownBlockType mouseDownBlock; // @synthesize mouseDownBlock=_mouseDownBlock;
@property(nonatomic) BOOL ignoreMouseEvent; // @synthesize ignoreMouseEvent=_ignoreMouseEvent;
@property(nonatomic) int vibrancyMode; // @synthesize vibrancyMode=_vibrancyMode;
- (void).cxx_destruct;
- (BOOL)performKeyEquivalent:(id)arg1;
- (BOOL)allowsVibrancy;
- (id)textView:(id)arg1 menu:(id)arg2 forEvent:(id)arg3 atIndex:(unsigned long long)arg4;
- (void)mouseUp:(id)arg1;
- (void)mouseDown:(id)arg1;

@end

