//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSTextView.h"

@class NSColor;

@interface MMTextView : NSTextView
{
    BOOL _mmShowFocusRingIfEditable;
    BOOL _ignoreMouseEvent;
    BOOL _mmShouldTrackMouseEnterExitEvents;
    BOOL _selected;
    BOOL _scrollEnabled;
    NSColor *_normalTextColor;
    NSColor *_selectedTextColor;
    CDUnknownBlockType _didPressEscKeyBlock;
    CDUnknownBlockType _didPressEnterKeyBlock;
    CDUnknownBlockType _mouseDidEnteredBlock;
    CDUnknownBlockType _mouseDidExitBlock;
    CDUnknownBlockType _mouseDownBlock;
    CDUnknownBlockType _mouseUpBlock;
    CDUnknownBlockType _shouldDisableSetFrameOrigin;
    CDUnknownBlockType _didChangeTextBlock;
}

@property(copy, nonatomic) CDUnknownBlockType didChangeTextBlock; // @synthesize didChangeTextBlock=_didChangeTextBlock;
@property(copy, nonatomic) CDUnknownBlockType shouldDisableSetFrameOrigin; // @synthesize shouldDisableSetFrameOrigin=_shouldDisableSetFrameOrigin;
@property(copy, nonatomic) CDUnknownBlockType mouseUpBlock; // @synthesize mouseUpBlock=_mouseUpBlock;
@property(copy, nonatomic) CDUnknownBlockType mouseDownBlock; // @synthesize mouseDownBlock=_mouseDownBlock;
@property(copy, nonatomic) CDUnknownBlockType mouseDidExitBlock; // @synthesize mouseDidExitBlock=_mouseDidExitBlock;
@property(copy, nonatomic) CDUnknownBlockType mouseDidEnteredBlock; // @synthesize mouseDidEnteredBlock=_mouseDidEnteredBlock;
@property(copy, nonatomic) CDUnknownBlockType didPressEnterKeyBlock; // @synthesize didPressEnterKeyBlock=_didPressEnterKeyBlock;
@property(copy, nonatomic) CDUnknownBlockType didPressEscKeyBlock; // @synthesize didPressEscKeyBlock=_didPressEscKeyBlock;
@property(nonatomic) BOOL scrollEnabled; // @synthesize scrollEnabled=_scrollEnabled;
@property(nonatomic) BOOL selected; // @synthesize selected=_selected;
@property(retain, nonatomic) NSColor *selectedTextColor; // @synthesize selectedTextColor=_selectedTextColor;
@property(retain, nonatomic) NSColor *normalTextColor; // @synthesize normalTextColor=_normalTextColor;
@property(nonatomic) BOOL mmShouldTrackMouseEnterExitEvents; // @synthesize mmShouldTrackMouseEnterExitEvents=_mmShouldTrackMouseEnterExitEvents;
@property(nonatomic) BOOL ignoreMouseEvent; // @synthesize ignoreMouseEvent=_ignoreMouseEvent;
@property(nonatomic) BOOL mmShowFocusRingIfEditable; // @synthesize mmShowFocusRingIfEditable=_mmShowFocusRingIfEditable;
- (void).cxx_destruct;
- (void)dealloc;
- (void)_updateDisplayedTextToMatchSelectionStyle;
- (void)didChangeText;
- (struct CGSize)intrinsicContentSize;
- (void)setFrameOrigin:(struct CGPoint)arg1;
- (void)setFrame:(struct CGRect)arg1;
- (void)mouseUp:(id)arg1;
- (void)mouseDown:(id)arg1;
- (void)keyDown:(id)arg1;
- (struct CGRect)focusRingMaskBounds;
- (void)drawFocusRingMask;
- (void)mouseExited:(id)arg1;
- (void)mouseEntered:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)init;

@end

