//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface MMURLSessionConfiguration : NSObject
{
}

+ (void)networkConnectCheckWithConfig:(id)arg1 completion:(CDUnknownBlockType)arg2;
+ (void)useCustomHttpProxy;
+ (void)useSystemHttpProxyFirstWithCompletion:(CDUnknownBlockType)arg1;
+ (void)useDirectConnectFirstWithCompletion:(CDUnknownBlockType)arg1;
+ (void)updateUrlSessionConfigurationWithSuccess:(unsigned char)arg1;
+ (id)genUrlSessionConfigurationWithProxy;

@end

