//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "AccountServiceExt.h"
#import "MMCGIDelegate.h"
#import "MMGetA8KeyLogicDelegate.h"

@class MMGetA8KeyLogic, NSString;

@interface MMURLHandler : NSObject <MMGetA8KeyLogicDelegate, AccountServiceExt, MMCGIDelegate>
{
    MMGetA8KeyLogic *getA8KeyLogic;
    CDUnknownBlockType _didOpenUrlBlock;
}

+ (id)getUrlWithoutFragment:(id)arg1;
+ (BOOL)isA8KeyCGI:(int)arg1;
+ (int)getA8keyCgiCmdIDByUrl:(id)arg1;
+ (BOOL)containsPhoneLinkString:(id)arg1;
+ (BOOL)containEmailString:(id)arg1;
+ (BOOL)containsMoaString:(id)arg1;
+ (BOOL)containsWeixinString:(id)arg1;
+ (BOOL)containsLocalPathString:(id)arg1;
+ (BOOL)containsString:(id)arg1 withRegex:(id)arg2;
+ (BOOL)containsHTTPString:(id)arg1;
+ (id)defaultHandler;
@property(copy, nonatomic) CDUnknownBlockType didOpenUrlBlock; // @synthesize didOpenUrlBlock=_didOpenUrlBlock;
- (void).cxx_destruct;
- (void)handleDebugUrl:(id)arg1 withFromUserName:(id)arg2;
- (id)debugUrlActionFromUrl:(id)arg1;
- (id)debugAvailableActions;
- (BOOL)isDebugUrl:(id)arg1 withFromUserName:(id)arg2;
- (BOOL)isAdminUserName:(id)arg1;
- (void)getA8KeyDidFaildWithReason:(int)arg1;
- (void)getA8keyDidFinishedWithReason:(int)arg1 fullURL:(id)arg2 shareURL:(id)arg3;
- (void)OnResponseCGI:(BOOL)arg1 sessionId:(unsigned int)arg2 cgiWrap:(id)arg3;
- (void)openURL:(id)arg1 withA8KeyConfig:(id)arg2;
- (void)openURLWithDefault:(id)arg1 useA8Key:(BOOL)arg2;
- (BOOL)preHandleUrlStr:(id)arg1 withMessage:(id)arg2;
- (id)filterUrlStr:(id)arg1;
- (void)handleReceiveBrandMsgURL:(id)arg1 messageData:(id)arg2;
- (void)handleReTransferFileURL:(id)arg1 messageData:(id)arg2;
- (void)handleContactVerifyURL:(id)arg1 messageData:(id)arg2;
- (void)handleExposeUrl:(id)arg1 messageData:(id)arg2;
- (void)handleDlFeedbackUrl:(id)arg1 messageData:(id)arg2;
- (void)handleNextFeedbackUrl:(id)arg1;
- (long long)getMsgIdByReTransferUrl:(id)arg1;
- (id)getContactUserNameByReTransferURL:(id)arg1;
- (id)getContactByReTransferURL:(id)arg1;
- (id)getContactUserNameByVerifyURL:(id)arg1;
- (id)getContactByVerifyURL:(id)arg1;
- (BOOL)isTencentNewsURL:(id)arg1;
- (BOOL)isWXPayURL:(id)arg1;
- (BOOL)isReeditURL:(id)arg1;
- (BOOL)isShowAllURL:(id)arg1;
- (BOOL)isContactProfileURL:(id)arg1;
- (BOOL)isMacWeixinURL:(id)arg1;
- (BOOL)isQQMailUrl:(id)arg1;
- (BOOL)isGameCentreURL:(id)arg1;
- (BOOL)isGroupChatInviteUrl:(id)arg1;
- (BOOL)isBrandHistoryRecordURL:(id)arg1;
- (BOOL)isDlFeedbackUrl:(id)arg1;
- (BOOL)isNextFeedbackUrl:(id)arg1;
- (BOOL)isExposeEntranceURL:(id)arg1;
- (BOOL)isReceiveBrandMsgURL:(id)arg1;
- (BOOL)isReTransferFileURL:(id)arg1;
- (BOOL)isContactVerifyURL:(id)arg1;
- (BOOL)isWeChatURL:(id)arg1;
- (void)onUserLogout;
- (void)destroy;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

