//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSWindowController.h"

#import "AccountServiceExt.h"
#import "NSWindowDelegate.h"

@class MMUserExtInfosTextView, NSString;

@interface MMUserExtInfosViewerWindowController : NSWindowController <NSWindowDelegate, AccountServiceExt>
{
    MMUserExtInfosTextView *m_contentTextView;
    int m_type;
}

- (void)onCurrentDeviceLockStateChanged:(BOOL)arg1;
- (void)onUserLogout;
- (void)viewFavDBEssentialInfo;
- (void)viewUpgradeHistory;
- (id)title;
- (void)dealloc;
- (void)windowWillClose:(id)arg1;
- (void)windowDidLoad;
- (id)defaultParagraphStyle;
- (id)initWithUserExtInfosViewerType:(int)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

