//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface MMUserAgentUtils : NSObject
{
}

+ (id)userAgentPrefix;
+ (id)userAgentSuffix:(id)arg1;
+ (id)webViewExtraUserAgent:(id)arg1;
+ (id)webViewDefaultExtraUserAgent;

@end

