//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSView.h"

@class MMViewController, NSColor;

@interface MMView : NSView
{
    BOOL _highlighted;
    int _vibrancyMode;
    NSColor *_backgroundColor;
    MMViewController *_viewController;
}

@property(nonatomic) __weak MMViewController *viewController; // @synthesize viewController=_viewController;
@property(nonatomic) BOOL highlighted; // @synthesize highlighted=_highlighted;
@property(nonatomic) int vibrancyMode; // @synthesize vibrancyMode=_vibrancyMode;
@property(retain, nonatomic) NSColor *backgroundColor; // @synthesize backgroundColor=_backgroundColor;
- (void).cxx_destruct;
- (BOOL)allowsVibrancy;

@end

