//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "AVAudioPlayerDelegate.h"
#import "CommonPlayerDelegate.h"

@class AVAudioPlayer, MessageData, NSString, SilkAudioPlayer;

@interface MMVoiceMessagePlayer : NSObject <AVAudioPlayerDelegate, CommonPlayerDelegate>
{
    BOOL _isUnplayedBeforePlay;
    MessageData *_audioMessage;
    AVAudioPlayer *_audioPlayer;
    SilkAudioPlayer *_silkAudioPlayer;
}

+ (id)defaultQueue;
+ (id)defaultPlayer;
@property(nonatomic) BOOL isUnplayedBeforePlay; // @synthesize isUnplayedBeforePlay=_isUnplayedBeforePlay;
@property(retain, nonatomic) SilkAudioPlayer *silkAudioPlayer; // @synthesize silkAudioPlayer=_silkAudioPlayer;
@property(retain, nonatomic) AVAudioPlayer *audioPlayer; // @synthesize audioPlayer=_audioPlayer;
@property(retain, nonatomic) MessageData *audioMessage; // @synthesize audioMessage=_audioMessage;
- (void).cxx_destruct;
- (void)onCommonPlayerError:(id)arg1 withPath:(id)arg2;
- (void)onCommonPlayerEndWithPath:(id)arg1;
- (void)onCommonPlayerPlayWithPath:(id)arg1;
- (void)audioPlayerDecodeErrorDidOccur:(id)arg1 error:(id)arg2;
- (void)audioPlayerDidFinishPlaying:(id)arg1 successfully:(BOOL)arg2;
- (void)audioPlayerDidStartPlaying;
- (void)playVoiceWithMessage:(id)arg1 isUnplayedBeforePlay:(BOOL)arg2;
- (void)stopVoiceWithMessage:(id)arg1;
- (void)stopVoice;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

