//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMMessageCellView.h"

#import "MMVoiceTranslateExt.h"

@class CAShapeLayer, MMRoundedRectangleView, MMTimer, NSImageView, NSProgressIndicator, NSString, NSTextField, NSTextView;

@interface MMVoiceMessageCellView : MMMessageCellView <MMVoiceTranslateExt>
{
    struct CGRect _calculatedTranslationRect;
    BOOL _isTranslatingVoiceToText;
    BOOL _mouseDown;
    MMRoundedRectangleView *_unreadTip;
    NSTextField *_voiceTimeLabel;
    NSImageView *_voiceWavImageView;
    NSImageView *_voiceToTextFailedImageView;
    MMTimer *_animationTimer;
    unsigned long long _animationCount;
    NSTextView *_translationTextView;
    NSProgressIndicator *_waitingProgressIndicator;
    CAShapeLayer *_highlightLayer;
    CAShapeLayer *_strokeLayer;
    CAShapeLayer *_dividerLayer;
    NSTextField *_noDataMetionTextField;
}

+ (double)_availableTextWidthForItem:(id)arg1 constraitWidth:(double)arg2;
+ (double)cellWidthOfNoDataMetionTextCell;
+ (struct CGRect)translatedStringBoundsWithMessage:(id)arg1 constrainedToWidth:(double)arg2;
+ (double)cellHeightWithMessage:(id)arg1 constrainedToWidth:(double)arg2;
@property(retain, nonatomic) NSTextField *noDataMetionTextField; // @synthesize noDataMetionTextField=_noDataMetionTextField;
@property(retain, nonatomic) CAShapeLayer *dividerLayer; // @synthesize dividerLayer=_dividerLayer;
@property(retain, nonatomic) CAShapeLayer *strokeLayer; // @synthesize strokeLayer=_strokeLayer;
@property(retain, nonatomic) CAShapeLayer *highlightLayer; // @synthesize highlightLayer=_highlightLayer;
@property(nonatomic) BOOL mouseDown; // @synthesize mouseDown=_mouseDown;
@property(retain, nonatomic) NSProgressIndicator *waitingProgressIndicator; // @synthesize waitingProgressIndicator=_waitingProgressIndicator;
@property(retain, nonatomic) NSTextView *translationTextView; // @synthesize translationTextView=_translationTextView;
@property(nonatomic) unsigned long long animationCount; // @synthesize animationCount=_animationCount;
@property(retain, nonatomic) MMTimer *animationTimer; // @synthesize animationTimer=_animationTimer;
@property(retain, nonatomic) NSImageView *voiceToTextFailedImageView; // @synthesize voiceToTextFailedImageView=_voiceToTextFailedImageView;
@property(retain, nonatomic) NSImageView *voiceWavImageView; // @synthesize voiceWavImageView=_voiceWavImageView;
@property(retain, nonatomic) NSTextField *voiceTimeLabel; // @synthesize voiceTimeLabel=_voiceTimeLabel;
@property(retain, nonatomic) MMRoundedRectangleView *unreadTip; // @synthesize unreadTip=_unreadTip;
@property(nonatomic) BOOL isTranslatingVoiceToText; // @synthesize isTranslatingVoiceToText=_isTranslatingVoiceToText;
- (void).cxx_destruct;
- (void)onVoiceTranslateEnd:(id)arg1;
- (void)onVoiceTranslateStart:(id)arg1;
- (void)translate;
- (void)playerDidStopPlay:(id)arg1;
- (void)playerDidStartPlay:(id)arg1;
- (void)setChoosable:(BOOL)arg1;
- (BOOL)allowChoose;
- (void)contextMenuTranscribe;
- (void)contextMenuWipeOutText;
- (id)getOperationMenuItem;
- (BOOL)allowMultipleSelect;
- (void)resendMessage;
- (struct CGRect)rectForContextMenuButton;
- (id)draggingImage;
- (BOOL)draggingEnabled;
- (double)voiceBubbleWidthWithTime:(unsigned int)arg1;
- (void)stopWavAnimation;
- (void)wavAnimation;
- (void)startWavAnimation;
- (void)playAudio;
- (void)mouseExited:(id)arg1;
- (void)mouseUp:(id)arg1;
- (void)mouseDown:(id)arg1;
- (void)updateHighlightMaskView;
- (id)getFillColor;
- (struct CGRect)clickableArea;
- (struct CGRect)bubbleFrame;
- (void)resetVoiceWavImage;
- (void)updateMessageHeight;
- (void)updateVoiceMessageViewFrames;
- (void)layoutWavImageView:(struct CGRect)arg1;
- (void)layoutVoiceTimeLabel:(struct CGRect)arg1;
- (void)layoutUnreadTip:(struct CGRect)arg1;
- (void)layoutTranslationTextView;
- (void)layoutTranslationTextViewContent;
- (void)updateMessageLayer;
- (void)populateWithMessage:(id)arg1;
- (void)resizeSubviewsWithOldSize:(struct CGSize)arg1;
- (void)viewDidMoveToSuperview;
- (void)prepareForReuse;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

