//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMService.h"

#import "MMService.h"

@class NSMutableArray, NSRecursiveLock, NSString;

@interface MMVoiceTranslateMgr : MMService <MMService>
{
    BOOL _m_isStop;
    NSMutableArray *_m_taskArray;
    NSRecursiveLock *_m_lock;
    NSMutableArray *_m_msgWrapArray;
    NSMutableArray *_m_cgiArray;
}

@property(retain, nonatomic) NSMutableArray *m_cgiArray; // @synthesize m_cgiArray=_m_cgiArray;
@property(retain, nonatomic) NSMutableArray *m_msgWrapArray; // @synthesize m_msgWrapArray=_m_msgWrapArray;
@property(nonatomic) BOOL m_isStop; // @synthesize m_isStop=_m_isStop;
@property(retain, nonatomic) NSRecursiveLock *m_lock; // @synthesize m_lock=_m_lock;
@property(retain, nonatomic) NSMutableArray *m_taskArray; // @synthesize m_taskArray=_m_taskArray;
- (void).cxx_destruct;
- (void)updateTranscribeVoiceMessage:(id)arg1 voiceText:(id)arg2 voiceToTextStatus:(unsigned int)arg3;
- (void)tryNextMsgWrap:(id)arg1;
- (void)stopTranslate;
- (void)removeTask:(id)arg1;
- (void)doTranslate:(id)arg1;
- (void)onServiceClearData;
- (void)onServiceInit;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

