//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "AVAudioPlayerDelegate.h"
#import "CommonPlayerDelegate.h"

@class AVAudioPlayer, MMTimer, NSString, SilkAudioPlayer;

@interface MMVoiceCommonPlayer : NSObject <AVAudioPlayerDelegate, CommonPlayerDelegate>
{
    id <MMVoiceCommonPlayerDelegate> _delegate;
    AVAudioPlayer *_audioPlayer;
    SilkAudioPlayer *_silkAudioPlayer;
    MMTimer *_playTimer;
}

@property(retain, nonatomic) MMTimer *playTimer; // @synthesize playTimer=_playTimer;
@property(retain, nonatomic) SilkAudioPlayer *silkAudioPlayer; // @synthesize silkAudioPlayer=_silkAudioPlayer;
@property(retain, nonatomic) AVAudioPlayer *audioPlayer; // @synthesize audioPlayer=_audioPlayer;
@property(nonatomic) __weak id <MMVoiceCommonPlayerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)audioPlayerDidFinishPlaying:(id)arg1 successfully:(BOOL)arg2;
- (void)voiceDidChangedCurrentTime:(id)arg1;
- (void)stopPlayTimer;
- (void)startPlayTimer;
- (void)onCommonPlayerPlayAtTime:(double)arg1 withPath:(id)arg2;
- (void)playVoiceWithFilePath:(id)arg1;
- (void)stopVoice;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

