//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BaseWebViewController.h"

#import "AccountServiceExt.h"
#import "IContactMgrExt.h"
#import "IMessageExt.h"

@class MMCustomDisableButton, NSString;

@interface MMWebViewController : BaseWebViewController <IContactMgrExt, IMessageExt, AccountServiceExt>
{
    NSString *_chatUserName;
    MMCustomDisableButton *_prevItemBtn;
    MMCustomDisableButton *_nextItemBtn;
    MMCustomDisableButton *_refreshBtn;
    MMCustomDisableButton *_forwardBtn;
    MMCustomDisableButton *_favoriteBtn;
    MMCustomDisableButton *_doCopyUrlBtn;
    MMCustomDisableButton *_externalBrowserBtn;
}

@property(retain, nonatomic) MMCustomDisableButton *externalBrowserBtn; // @synthesize externalBrowserBtn=_externalBrowserBtn;
@property(retain, nonatomic) MMCustomDisableButton *doCopyUrlBtn; // @synthesize doCopyUrlBtn=_doCopyUrlBtn;
@property(retain, nonatomic) MMCustomDisableButton *favoriteBtn; // @synthesize favoriteBtn=_favoriteBtn;
@property(retain, nonatomic) MMCustomDisableButton *forwardBtn; // @synthesize forwardBtn=_forwardBtn;
@property(retain, nonatomic) MMCustomDisableButton *refreshBtn; // @synthesize refreshBtn=_refreshBtn;
@property(retain, nonatomic) MMCustomDisableButton *nextItemBtn; // @synthesize nextItemBtn=_nextItemBtn;
@property(retain, nonatomic) MMCustomDisableButton *prevItemBtn; // @synthesize prevItemBtn=_prevItemBtn;
@property(retain, nonatomic) NSString *chatUserName; // @synthesize chatUserName=_chatUserName;
- (void).cxx_destruct;
- (void)handleCloseWindowJSEvent;
- (void)onCopyAction:(id)arg1;
- (void)onDomReadyAction;
- (void)onPageStateChangeAction:(id)arg1;
- (void)forwardContent;
- (void)addToFavorites;
- (void)copyUrl;
- (void)openInExternalBrowser;
- (void)refreshContent;
- (void)nextItem;
- (void)previousItem;
- (void)onUserLogout;
- (void)onCurrentNetworkLockStateWillChange:(BOOL)arg1;
- (void)onCurrentDeviceLockStateChanged:(BOOL)arg1;
- (void)onModifyContacts:(id)arg1;
- (void)onDelMsg:(id)arg1 msgData:(id)arg2;
- (void)_setupContentContainer;
- (void)_setupHostLabel;
- (void)_setupProgressView;
- (void)_setupToolbarContainer;
- (void)handleWeixinJumpScheme:(id)arg1;
- (void)updateMenuItems;
- (void)updateNavigation;
- (void)setupUIControls;
- (void)dealloc;
- (void)viewDidLoad;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

