//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WKWebView.h"

@interface MMWKWebView : WKWebView
{
}

- (void)evaluateJavaScriptFromString:(id)arg1 completionBlock:(CDUnknownBlockType)arg2;
- (void)willOpenMenu:(id)arg1 withEvent:(id)arg2;
- (void)customLoadRequest:(id)arg1;

@end

