//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class WCTDatabase, WCTTable;

@interface MsgGapStorage : NSObject
{
    WCTDatabase *m_db;
    WCTTable *m_table;
}

+ (id)sharedInstance;
- (void).cxx_destruct;
- (void)deleteMsgGapBy:(id)arg1;
- (void)updateMsgGapBy:(id)arg1;
- (void)deleteMsgGapEarlierThan:(unsigned int)arg1;
- (id)getMsgGapsFrom:(unsigned int)arg1 to:(unsigned int)arg2 chat:(id)arg3;
- (void)addMsgGap:(id)arg1;
- (void)addMsgGaps:(id)arg1;
- (void)dealloc;
- (void)close;
- (void)closeDBBeforeInit;
- (id)init;

@end

