//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "WCTTableCoding.h"

@class NSString;

@interface MsgGap : NSObject <WCTTableCoding>
{
    BOOL isAutoIncrement;
    unsigned int _startTime;
    unsigned int _endTime;
    long long lastInsertedRowID;
    unsigned long long _gapId;
    NSString *_sessionName;
    NSString *_identifier;
}

+ (const struct WCTProperty *)identifier;
+ (const struct WCTProperty *)endTime;
+ (const struct WCTProperty *)startTime;
+ (const struct WCTProperty *)sessionName;
+ (const struct WCTProperty *)gapId;
+ (const struct WCTAnyProperty *)AnyProperty;
+ (const list_2812bee2 *)AllProperties;
+ (const struct WCTBinding *)objectRelationalMappingForWCDB;
@property(retain, nonatomic) NSString *identifier; // @synthesize identifier=_identifier;
@property(nonatomic) unsigned int endTime; // @synthesize endTime=_endTime;
@property(nonatomic) unsigned int startTime; // @synthesize startTime=_startTime;
@property(retain, nonatomic) NSString *sessionName; // @synthesize sessionName=_sessionName;
@property(nonatomic) unsigned long long gapId; // @synthesize gapId=_gapId;
@property(nonatomic) long long lastInsertedRowID; // @synthesize lastInsertedRowID;
@property(nonatomic) BOOL isAutoIncrement; // @synthesize isAutoIncrement;
- (void).cxx_destruct;
- (id)description;

@end

