//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSArray.h"

@interface NSArray (Swizzle)
+ (id)safe_arrayWithObjects:(const id *)arg1 count:(unsigned long long)arg2;
+ (void)load;
- (id)safe_arrayByAddingObject:(id)arg1;
- (id)safe_objectAtIndexForNSArray0:(unsigned long long)arg1;
- (id)safe_objectAtIndexedSubscript:(unsigned long long)arg1;
- (id)safe_objectAtIndex:(unsigned long long)arg1;
- (id)safe_initWithObjects:(const id *)arg1 count:(unsigned long long)arg2;
@end

