//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSMutableString.h"

@interface NSMutableString (Swizzle)
+ (void)load;
- (unsigned long long)safe_replaceOccurrencesOfString:(id)arg1 withString:(id)arg2 options:(unsigned long long)arg3 range:(struct _NSRange)arg4;
- (void)safe_insertString:(id)arg1 atIndex:(unsigned long long)arg2;
- (void)safe_setString:(id)arg1;
- (void)safe_appendFormat:(id)arg1;
- (void)safe_appendString:(id)arg1;
@end

