//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSWindowController.h"

@interface NSWindowController (Present)
- (void)popWindow:(id)arg1;
- (void)popWindow;
- (void)pushWindow:(id)arg1 withIdentifier:(id)arg2;
- (void)pushWindow:(id)arg1;
@end

