//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PBGeneratedMessage.h"

@class NSString;

@interface OpenIMModChatRoomTopOplog : PBGeneratedMessage
{
    unsigned int hasRoomName:1;
    unsigned int hasSwitchFlag:1;
    unsigned int switchFlag;
    NSString *roomName;
}

+ (id)parseFromData:(id)arg1;
@property(nonatomic, setter=SetSwitchFlag:) unsigned int switchFlag; // @synthesize switchFlag;
@property(readonly, nonatomic) BOOL hasSwitchFlag; // @synthesize hasSwitchFlag;
@property(retain, nonatomic, setter=SetRoomName:) NSString *roomName; // @synthesize roomName;
@property(readonly, nonatomic) BOOL hasRoomName; // @synthesize hasRoomName;
- (void).cxx_destruct;
- (id)mergeFromCodedInputStream:(id)arg1;
- (int)serializedSize;
- (void)writeToCodedOutputStream:(id)arg1;
- (BOOL)isInitialized;
- (id)init;

@end

