//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMService.h"

#import "MMCGIDelegate.h"
#import "MMService.h"

@class NSRecursiveLock, NSString, OpLogDB;

@interface OpLogService : MMService <MMCGIDelegate, MMService>
{
    BOOL _m_syncOplog;
    NSRecursiveLock *_m_lock;
    OpLogDB *_m_oplogDB;
}

@property(retain, nonatomic) OpLogDB *m_oplogDB; // @synthesize m_oplogDB=_m_oplogDB;
@property(retain, nonatomic) NSRecursiveLock *m_lock; // @synthesize m_lock=_m_lock;
@property(nonatomic) BOOL m_syncOplog; // @synthesize m_syncOplog=_m_syncOplog;
- (void).cxx_destruct;
- (BOOL)deleteOpLogs:(id)arg1;
- (BOOL)deleteOpLog:(id)arg1;
- (id)getOpLogOfTop:(unsigned int)arg1;
- (unsigned int)getOpLogCount;
- (BOOL)addOpLog:(unsigned int)arg1 Oplog:(id)arg2;
- (BOOL)addOpLog:(unsigned int)arg1 message:(id)arg2;
- (void)OnResponseCGI:(BOOL)arg1 sessionId:(unsigned int)arg2 cgiWrap:(id)arg3;
- (void)startSyncOplog;
- (void)checkSyncOplog;
- (void)NeedToSyncOplog;
- (BOOL)AddOpLog:(unsigned int)arg1 Oplog:(id)arg2 Sync:(BOOL)arg3;
- (BOOL)AddOpLog:(unsigned int)arg1 message:(id)arg2 needSync:(BOOL)arg3;
- (void)DeleteOplogDB;
- (void)dealloc;
- (void)onServiceClearData;
- (void)onServiceInit;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

