//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class WCTDatabase, WCTTable;

@interface OpLogDB : NSObject
{
    WCTDatabase *m_db;
    WCTTable *m_table;
}

+ (void)DeleteDB;
- (void).cxx_destruct;
- (BOOL)DeleteOpLogs:(id)arg1;
- (BOOL)DeleteOpLog:(id)arg1;
- (id)GetOpLogOfTop:(unsigned int)arg1;
- (unsigned int)GetOpLogCount;
- (BOOL)InsertOpLog:(id)arg1;
- (void)dealloc;
- (void)close;
- (void)closeDBBeforeInit;
- (id)init;

@end

