//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "MMNetExt.h"

@class MMTimer, NSData, NSString;

@interface PushLoginURLCGI : NSObject <MMNetExt>
{
    unsigned int _checkTime;
    MMTimer *_timer;
    NSData *_notifyDecodeKey;
    NSString *_uuid;
    CDUnknownBlockType _didFailedPushLoginCGIBlock;
    CDUnknownBlockType _didConfirmPushLoginCGIBlock;
    CDUnknownBlockType _didCancelPushLoginCGIBlock;
}

@property(copy, nonatomic) CDUnknownBlockType didCancelPushLoginCGIBlock; // @synthesize didCancelPushLoginCGIBlock=_didCancelPushLoginCGIBlock;
@property(copy, nonatomic) CDUnknownBlockType didConfirmPushLoginCGIBlock; // @synthesize didConfirmPushLoginCGIBlock=_didConfirmPushLoginCGIBlock;
@property(copy, nonatomic) CDUnknownBlockType didFailedPushLoginCGIBlock; // @synthesize didFailedPushLoginCGIBlock=_didFailedPushLoginCGIBlock;
@property(nonatomic) unsigned int checkTime; // @synthesize checkTime=_checkTime;
@property(retain, nonatomic) NSString *uuid; // @synthesize uuid=_uuid;
@property(retain, nonatomic) NSData *notifyDecodeKey; // @synthesize notifyDecodeKey=_notifyDecodeKey;
@property(retain, nonatomic) MMTimer *timer; // @synthesize timer=_timer;
- (void).cxx_destruct;
- (void)onServerNotify:(int)arg1 cmdID:(int)arg2 notifyData:(id)arg3;
- (BOOL)handleNotify:(id)arg1;
- (void)stoptimer;
- (void)handleFailed;
- (void)handleCanceled;
- (void)handleConfirmed:(id)arg1;
- (void)checkPushLoginURL;
- (void)sendRequestWithUserName:(id)arg1 autoAuthKey:(id)arg2;
- (void)stopCGI;
- (void)cleanup;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

