//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "WCTTableCoding.h"

@class NSString;

@interface RevokeMsgItem : NSObject <WCTTableCoding>
{
    unsigned int _createTime;
    NSString *_svrId;
    NSString *_content;
}

+ (const struct WCTProperty *)content;
+ (const struct WCTProperty *)svrId;
+ (const struct WCTProperty *)createTime;
+ (const struct WCTAnyProperty *)AnyProperty;
+ (const list_2812bee2 *)AllProperties;
+ (const struct WCTBinding *)objectRelationalMappingForWCDB;
@property(retain, nonatomic) NSString *content; // @synthesize content=_content;
@property(retain, nonatomic) NSString *svrId; // @synthesize svrId=_svrId;
@property(nonatomic) unsigned int createTime; // @synthesize createTime=_createTime;
- (void).cxx_destruct;

// Remaining properties
@property(nonatomic) BOOL isAutoIncrement;
@property(nonatomic) long long lastInsertedRowID;

@end

