//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSScrollView.h"

@interface RFOverlayScrollView : NSScrollView
{
    unsigned char _isViewDrag;
    BOOL _isOptiScroller;
    long long _headerOffset;
}

+ (void)swizzleMethod:(SEL)arg1 tarSel:(SEL)arg2;
@property(nonatomic) BOOL isOptiScroller; // @synthesize isOptiScroller=_isOptiScroller;
@property(nonatomic) unsigned char isViewDrag; // @synthesize isViewDrag=_isViewDrag;
@property(nonatomic) long long headerOffset; // @synthesize headerOffset=_headerOffset;
- (long long)tableHeaderOffsetFromSuperview;
- (void)tile;
- (void)commonInitializer;
- (void)awakeFromNib;
- (id)initWithCoder:(id)arg1;

@end

