//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSCondition;

@interface RWLock : NSObject
{
    long long _stat;
    NSCondition *_cond;
}

@property(retain, nonatomic) NSCondition *cond; // @synthesize cond=_cond;
@property(nonatomic) long long stat; // @synthesize stat=_stat;
- (void).cxx_destruct;
- (void)writeUnlock;
- (void)writeLock;
- (void)readUnlock;
- (void)readLock;
- (id)init;

@end

