//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PBGeneratedMessage.h"

@interface SyncControl : PBGeneratedMessage
{
    unsigned int hasUseInitContact:1;
    unsigned int useInitContact;
}

+ (id)parseFromData:(id)arg1;
@property(nonatomic, setter=SetUseInitContact:) unsigned int useInitContact; // @synthesize useInitContact;
@property(readonly, nonatomic) BOOL hasUseInitContact; // @synthesize hasUseInitContact;
- (id)mergeFromCodedInputStream:(id)arg1;
- (int)serializedSize;
- (void)writeToCodedOutputStream:(id)arg1;
- (BOOL)isInitialized;
- (id)init;

@end

