//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMService.h"

#import "ContactInitLogicDelegate.h"
#import "InitCGIDelegate.h"
#import "MMNetExt.h"
#import "MMService.h"
#import "SyncCGIExt.h"

@class ContactInitLogic, HeartBeatCGI, InitCGI, NSRecursiveLock, NSString, SyncCGI;

@interface SyncService : MMService <InitCGIDelegate, SyncCGIExt, MMNetExt, ContactInitLogicDelegate, MMService>
{
    InitCGI *_initCGI;
    SyncCGI *_syncCGI;
    HeartBeatCGI *_heartBeatCGI;
    NSRecursiveLock *_syncCgiLock;
    BOOL _isDoingInit;
    BOOL _isDoingSync;
    BOOL _isSyncClosed;
    BOOL _isFirstSync;
    BOOL _needSync;
    BOOL _needOpenIMSync;
    ContactInitLogic *m_contactInitLogic;
    unsigned int m_curPercent;
    unsigned int m_curFakePercent;
    BOOL _useInitContact;
    BOOL _hasClearData;
    unsigned int _lastSyncMsgFromSelfTime;
    NSString *_lastSyncMsgFromSelfChatName;
}

+ (void)ClearBeforeInit;
+ (void)ClearForInitAgain;
@property BOOL hasClearData; // @synthesize hasClearData=_hasClearData;
@property(nonatomic) BOOL useInitContact; // @synthesize useInitContact=_useInitContact;
@property(retain, nonatomic) NSString *lastSyncMsgFromSelfChatName; // @synthesize lastSyncMsgFromSelfChatName=_lastSyncMsgFromSelfChatName;
@property(nonatomic) unsigned int lastSyncMsgFromSelfTime; // @synthesize lastSyncMsgFromSelfTime=_lastSyncMsgFromSelfTime;
- (void).cxx_destruct;
- (BOOL)ProcessHeartBeatResponse:(id)arg1 isSessionTimeout:(char *)arg2;
- (BOOL)FillHeartBeatRequestBuffer:(id)arg1 reqCmdId:(int *)arg2 respCmdId:(int *)arg3;
- (void)CheckHeartBeatIfNeeded;
- (void)StartCheckHeartBeat;
- (void)ClearHeartBeat;
- (void)onServerNotify:(int)arg1 cmdID:(int)arg2 notifyData:(id)arg3;
- (void)onSyncSuccess;
- (void)onSyncFail;
- (void)CheckNeedToSync:(unsigned int)arg1;
- (void)FixOpenIMSync;
- (void)BackGroundToForeGroundSync;
- (void)sendSyncCGIWithScene:(unsigned int)arg1;
- (BOOL)isSyncClosed;
- (void)OpenSync;
- (void)CloseSync;
- (BOOL)IsNeedSync;
- (BOOL)IsDoingSync;
- (BOOL)isCanStartSync;
- (void)onContactInitSuccess;
- (void)onContactInitFail;
- (void)onContactInitUserNameUpdate;
- (void)onContactInitProcessUpdate:(unsigned int)arg1;
- (void)tryInitContact;
- (void)onInitCGIFail;
- (void)onInitCGIFinish;
- (void)onInitCGIProcessed:(unsigned int)arg1;
- (void)StartSyncOnAuthOK;
- (void)StartInitNoSyncBuffer;
- (void)StartInit;
- (void)CancelInit;
- (BOOL)IsDoingInit;
- (BOOL)IsNeedInit;
- (BOOL)IsFirstSync;
- (void)UnregisterKeyExtension;
- (void)RegisterKeyExtension;
- (void)onServiceClearData;
- (void)onServiceInit;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

