//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableArray, NSRecursiveLock;

@interface TSArray : NSObject
{
    NSMutableArray *_arr;
    NSRecursiveLock *_lock;
}

- (void).cxx_destruct;
- (void)foreach:(CDUnknownBlockType)arg1;
- (void)removeObjectsInRange:(struct _NSRange)arg1;
- (void)removeObjectsInArray:(id)arg1;
- (void)removeAllObjects;
- (void)removeObjectAtIndex:(unsigned long long)arg1;
- (void)removeObject:(id)arg1;
- (void)replaceObjectAtIndex:(unsigned long long)arg1 withObject:(id)arg2;
- (void)addObjectsFromArray:(id)arg1;
- (id)arrayByAddingObjectsFromArray:(id)arg1;
- (id)arrayByAddingObject:(id)arg1;
- (void)insertObject:(id)arg1 atIndex:(unsigned long long)arg2;
- (void)addObject:(id)arg1;
- (id)subarrayWithRange:(struct _NSRange)arg1;
- (BOOL)containsObject:(id)arg1;
- (id)lastObject;
- (id)firstObject;
- (unsigned long long)indexOfObject:(id)arg1;
- (id)objectAtIndex:(unsigned long long)arg1;
- (id)init;

@end

