//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCoding.h"

@interface WCBlockMonitorConfiguration : NSObject <NSCoding>
{
    BOOL _bMonitor;
    BOOL _bMainThreadHandle;
    BOOL _bPrintCPUUsage;
    unsigned int _runloopTimeOut;
    unsigned int _checkPeriodTime;
    float _limitCPUPercent;
    unsigned int _perStackInterval;
    unsigned int _mainThreadCount;
    unsigned int _limitFrameDrop;
}

+ (id)defaultConfig;
@property(nonatomic) BOOL bPrintCPUUsage; // @synthesize bPrintCPUUsage=_bPrintCPUUsage;
@property(nonatomic) unsigned int limitFrameDrop; // @synthesize limitFrameDrop=_limitFrameDrop;
@property(nonatomic) unsigned int mainThreadCount; // @synthesize mainThreadCount=_mainThreadCount;
@property(nonatomic) unsigned int perStackInterval; // @synthesize perStackInterval=_perStackInterval;
@property(nonatomic) BOOL bMainThreadHandle; // @synthesize bMainThreadHandle=_bMainThreadHandle;
@property(nonatomic) float limitCPUPercent; // @synthesize limitCPUPercent=_limitCPUPercent;
@property(nonatomic) unsigned int checkPeriodTime; // @synthesize checkPeriodTime=_checkPeriodTime;
@property(nonatomic) unsigned int runloopTimeOut; // @synthesize runloopTimeOut=_runloopTimeOut;
@property(nonatomic) BOOL bMonitor; // @synthesize bMonitor=_bMonitor;
- (id)description;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;

@end

