//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "WCCrashBlockMonitorDelegate.h"

@class NSString, WCCrashBlockMonitorPlugin;

@interface WCCrashBlockHandler : NSObject <WCCrashBlockMonitorDelegate>
{
    WCCrashBlockMonitorPlugin *_plugin;
}

+ (id)sharedInstance;
@property(retain, nonatomic) WCCrashBlockMonitorPlugin *plugin; // @synthesize plugin=_plugin;
- (void).cxx_destruct;
- (id)getCrashBlockPluginConfiguration;
- (id)getCrashBlockPlugin;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

