//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSObject<OS_dispatch_queue>, WCCrashReportInfo;

@interface WCCrashReportMgr : NSObject
{
    NSObject<OS_dispatch_queue> *m_crashRepoterQueue;
    BOOL m_uploading;
    WCCrashReportInfo *m_oCrashReportInfo;
    unsigned long long m_currentReportType;
}

+ (id)getCurrentDateForCrashReportInfo;
+ (id)getCrashReportInfoPath;
+ (id)sharedInstance;
- (void).cxx_destruct;
- (void)handleReportCrashIssue:(id)arg1 success:(BOOL)arg2;
- (void)refreshCrashReportInfo;
- (void)saveCrashReportInfo;
- (void)loadCrashReportInfo;
- (void)reportCrashWithMatrixIssue:(id)arg1;
- (void)p_tryUpload:(BOOL)arg1;
- (void)p_doCrashReport;
- (void)reportCrash;
- (BOOL)reportCrashReportOnSafeMode;
- (void)delayReportCrash;
- (id)init;

@end

