//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMService.h"

#import "AccountServiceExt.h"
#import "MMService.h"

@class NSMutableArray, NSMutableDictionary, NSMutableSet, NSRecursiveLock, NSString;

@interface WCDBRepairMgr : MMService <AccountServiceExt, MMService>
{
    NSMutableDictionary *m_repairInfoDic;
    NSMutableSet *m_corruptedDBTagSet;
    NSMutableSet *m_destoryDBTagSet;
    NSMutableArray *m_repairFailedList;
    NSRecursiveLock *m_oLock;
    BOOL m_stopRepair;
    unsigned int lastCheckWCDBTimeStamp;
    BOOL m_bNeedToast;
    id <WCDBRepairDelegate> _delegate;
}

@property(nonatomic) __weak id <WCDBRepairDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)FFAddRecvFavZZ:(BOOL)arg1;
- (void)onAutoRepairNotImportantCorruptedDB;
- (void)checkAndRepair;
- (id)getNeedRepairDBPath;
- (id)getMetasFromDB:(id)arg1;
- (void)deleteDBWith:(id)arg1;
- (void)deleteRepairFailedDB;
- (void)stopRepair;
- (void)deleteDestroyDB:(id)arg1;
- (void)repairCorruptedDBWith:(id)arg1;
- (void)repairAllCorruptedDB;
- (void)addDestroyDB:(id)arg1;
- (void)addCorruptedDB:(id)arg1;
- (void)registerRepairInfo:(id)arg1;
- (void)onRecvWCDBAutoDetectValueChanged:(id)arg1;
- (void)onNotifyCorruptedDB;
- (void)delayDetectCorruptDB;
- (void)onServiceDidWake;
- (void)onServiceClearData;
- (void)onServiceInit;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

