//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMWindowController.h"

#import "NSWindowDelegate.h"
#import "WCDBRepairDelegate.h"

@class MMButton, MMOutlineButton, NSImageView, NSString, NSTextView;

@interface WCDBAutoRepairWindowController : MMWindowController <WCDBRepairDelegate, NSWindowDelegate>
{
    NSImageView *_wrenchIcon;
    MMButton *_okBtn;
    NSTextView *_descTextView;
    MMOutlineButton *_cancleBtn;
}

@property(retain, nonatomic) MMOutlineButton *cancleBtn; // @synthesize cancleBtn=_cancleBtn;
@property(retain, nonatomic) NSTextView *descTextView; // @synthesize descTextView=_descTextView;
@property(retain, nonatomic) MMButton *okBtn; // @synthesize okBtn=_okBtn;
@property(retain, nonatomic) NSImageView *wrenchIcon; // @synthesize wrenchIcon=_wrenchIcon;
- (void).cxx_destruct;
- (void)onRepairFinish;
- (void)onRepairNoNeed;
- (void)onClearDBCompleted;
- (void)onRepairFailed;
- (void)onRepairing;
- (void)onCancleBtnClick:(id)arg1;
- (void)onDeletedRepairdDBBtnClick:(id)arg1;
- (void)onStartRepairBtnClick:(id)arg1;
- (void)onRepairedFinishBtnClicked:(id)arg1;
- (void)layoutSubviews;
- (void)windowWillClose:(id)arg1;
- (void)showWindow:(id)arg1;
- (void)windowDidLoad;
- (void)dealloc;
- (id)initWithWindowNibName:(id)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

