//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "IIPxxExt.h"

@class NSMutableArray, NSObject<OS_dispatch_queue>, NSString;

@interface WCDumpReporterMgr : NSObject <IIPxxExt>
{
    NSObject<OS_dispatch_queue> *_dumpReporterQueue;
    NSMutableArray *_uploadedIssueArray;
    NSMutableArray *_uploadingIssueArray;
}

+ (id)sharedInstance;
@property(retain, nonatomic) NSMutableArray *uploadingIssueArray; // @synthesize uploadingIssueArray=_uploadingIssueArray;
@property(retain, nonatomic) NSMutableArray *uploadedIssueArray; // @synthesize uploadedIssueArray=_uploadedIssueArray;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *dumpReporterQueue; // @synthesize dumpReporterQueue=_dumpReporterQueue;
- (void).cxx_destruct;
- (void)onGetIpxxMsgContent:(id)arg1;
- (void)handleReportLagIssue:(id)arg1 success:(BOOL)arg2;
- (void)uploadDumpOnIPXX:(id)arg1;
- (void)uploadDumpWithDate:(id)arg1 withReprotCntOneTime:(unsigned long long)arg2;
- (void)uploadAllDump;
- (void)autoUploadDump;
- (void)onEnterBackground;
- (void)onEnterForeground;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

