//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class BaseWebViewController, NSArray, NSString;

@protocol WebViewJSLogicDelegate <NSObject>

@optional
- (void)onCopy:(NSString *)arg1;
- (void)onDomReady;
- (void)onPageStateChange:(NSString *)arg1;
- (BaseWebViewController *)logicBaseWebViewController;
- (NSArray *)getAuthorizedMonitorEvents:(NSString *)arg1;
@end

