//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "WebviewJSEventHandler.h"

@class JSEvent, NSString;

@interface WebviewJSEventHandlerBase : NSObject <WebviewJSEventHandler>
{
    JSEvent *_currentEvent;
    id <WebviewJSEventHandlerBaseDelegate> _m_delegate;
}

@property(nonatomic) __weak id <WebviewJSEventHandlerBaseDelegate> m_delegate; // @synthesize m_delegate=_m_delegate;
@property(retain, nonatomic) JSEvent *currentEvent; // @synthesize currentEvent=_currentEvent;
- (void).cxx_destruct;
- (id)handlerWebViewController;
- (void)handleJSEvent:(id)arg1 HandlerFacade:(id)arg2 ExtraData:(id)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

