//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class FavoritesItem, FavoritesItemDataField, MessageData, NSDictionary, NSString, ReaderWrap, WCContactData;

@interface WebViewDataItem : NSObject
{
    BOOL _isForceWebView;
    NSString *_urlString;
    MessageData *_message;
    ReaderWrap *_readerWrap;
    FavoritesItem *_favoritesItem;
    WCContactData *_brandContact;
    FavoritesItemDataField *_dataField;
    NSDictionary *_extraData;
}

@property(nonatomic) BOOL isForceWebView; // @synthesize isForceWebView=_isForceWebView;
@property(retain, nonatomic) NSDictionary *extraData; // @synthesize extraData=_extraData;
@property(retain, nonatomic) FavoritesItemDataField *dataField; // @synthesize dataField=_dataField;
@property(retain, nonatomic) WCContactData *brandContact; // @synthesize brandContact=_brandContact;
@property(retain, nonatomic) FavoritesItem *favoritesItem; // @synthesize favoritesItem=_favoritesItem;
@property(retain, nonatomic) ReaderWrap *readerWrap; // @synthesize readerWrap=_readerWrap;
@property(retain, nonatomic) MessageData *message; // @synthesize message=_message;
@property(retain, nonatomic) NSString *urlString; // @synthesize urlString=_urlString;
- (void).cxx_destruct;

@end

