//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "AccountServiceExt.h"
#import "IContactMgrExt.h"
#import "MMNetServiceDelegate.h"
#import "MMNetServiceExt.h"
#import "NSMenuDelegate.h"

@class DiskMonitor, IoMonitor, LeftViewController, LogoutCGI, MMChatsViewController, MMComposeTextView, MMDockItem, MMMainWindowController, MMServiceCenter, MMStatusItem, MMViewController, NSMenu, NSMenuItem, NSString, ShareExtConfirmWindowController, VisualizationMonitor, WCDBMonitorMgr;

@interface WeChat : NSObject <NSMenuDelegate, AccountServiceExt, MMNetServiceDelegate, MMNetServiceExt, IContactMgrExt>
{
    BOOL _isLoggedIn;
    BOOL _isLocked;
    BOOL _isInBackground;
    BOOL _isAppTerminating;
    BOOL _showDisconnectBanner;
    BOOL _isWCDBRepairing;
    BOOL _hasMsgBeforeSync;
    BOOL _isWorkSpaceSleep;
    BOOL _isDisplayAsleep;
    BOOL _hasAuthOK;
    BOOL _triedAutoLogin;
    BOOL _isAppTerminateNow;
    int _loginType;
    MMMainWindowController *_mainWindowController;
    MMChatsViewController *_chatsViewController;
    LeftViewController *_leftViewController;
    MMViewController *_rightViewController;
    MMComposeTextView *_composeTextView;
    NSMenuItem *_lockMenuItem;
    NSMenu *_wechatMenu;
    long long _locateMessage;
    ShareExtConfirmWindowController *_shareExtConfirmWindowController;
    MMServiceCenter *_serviceCenter;
    MMStatusItem *_statusItem;
    MMDockItem *_dockItem;
    NSMenuItem *_feedbackItem;
    LogoutCGI *_logoutCGI;
    WCDBMonitorMgr *_wcdbMonitorMgr;
    IoMonitor *_ioMonitor;
    DiskMonitor *_diskMonitor;
    VisualizationMonitor *_visualizationMonitor;
}

+ (id)appDelegate;
+ (id)sharedInstance;
+ (void)initialize;
@property(retain, nonatomic) VisualizationMonitor *visualizationMonitor; // @synthesize visualizationMonitor=_visualizationMonitor;
@property(retain, nonatomic) DiskMonitor *diskMonitor; // @synthesize diskMonitor=_diskMonitor;
@property(retain, nonatomic) IoMonitor *ioMonitor; // @synthesize ioMonitor=_ioMonitor;
@property(retain, nonatomic) WCDBMonitorMgr *wcdbMonitorMgr; // @synthesize wcdbMonitorMgr=_wcdbMonitorMgr;
@property(retain, nonatomic) LogoutCGI *logoutCGI; // @synthesize logoutCGI=_logoutCGI;
@property(retain, nonatomic) NSMenuItem *feedbackItem; // @synthesize feedbackItem=_feedbackItem;
@property(retain, nonatomic) MMDockItem *dockItem; // @synthesize dockItem=_dockItem;
@property(retain, nonatomic) MMStatusItem *statusItem; // @synthesize statusItem=_statusItem;
@property(nonatomic) BOOL isAppTerminateNow; // @synthesize isAppTerminateNow=_isAppTerminateNow;
@property(retain, nonatomic) MMServiceCenter *serviceCenter; // @synthesize serviceCenter=_serviceCenter;
@property(retain, nonatomic) ShareExtConfirmWindowController *shareExtConfirmWindowController; // @synthesize shareExtConfirmWindowController=_shareExtConfirmWindowController;
@property(nonatomic) int loginType; // @synthesize loginType=_loginType;
@property(nonatomic) BOOL triedAutoLogin; // @synthesize triedAutoLogin=_triedAutoLogin;
@property(nonatomic) BOOL hasAuthOK; // @synthesize hasAuthOK=_hasAuthOK;
@property(nonatomic) BOOL isDisplayAsleep; // @synthesize isDisplayAsleep=_isDisplayAsleep;
@property(nonatomic) BOOL isWorkSpaceSleep; // @synthesize isWorkSpaceSleep=_isWorkSpaceSleep;
@property(nonatomic) long long locateMessage; // @synthesize locateMessage=_locateMessage;
@property(nonatomic) BOOL hasMsgBeforeSync; // @synthesize hasMsgBeforeSync=_hasMsgBeforeSync;
@property(nonatomic) BOOL isWCDBRepairing; // @synthesize isWCDBRepairing=_isWCDBRepairing;
@property(nonatomic) BOOL showDisconnectBanner; // @synthesize showDisconnectBanner=_showDisconnectBanner;
@property(nonatomic) BOOL isAppTerminating; // @synthesize isAppTerminating=_isAppTerminating;
@property(nonatomic) BOOL isInBackground; // @synthesize isInBackground=_isInBackground;
@property(nonatomic) BOOL isLocked; // @synthesize isLocked=_isLocked;
@property(nonatomic) BOOL isLoggedIn; // @synthesize isLoggedIn=_isLoggedIn;
@property(nonatomic) __weak NSMenu *wechatMenu; // @synthesize wechatMenu=_wechatMenu;
@property(nonatomic) __weak NSMenuItem *lockMenuItem; // @synthesize lockMenuItem=_lockMenuItem;
@property(retain, nonatomic) MMComposeTextView *composeTextView; // @synthesize composeTextView=_composeTextView;
@property(nonatomic) __weak MMViewController *rightViewController; // @synthesize rightViewController=_rightViewController;
@property(nonatomic) __weak LeftViewController *leftViewController; // @synthesize leftViewController=_leftViewController;
@property(nonatomic) __weak MMChatsViewController *chatsViewController; // @synthesize chatsViewController=_chatsViewController;
@property(retain, nonatomic) MMMainWindowController *mainWindowController; // @synthesize mainWindowController=_mainWindowController;
- (void).cxx_destruct;
- (void)onUserChangedSystemTime:(id)arg1;
- (void)showOrHideMainWindow;
- (void)orderFrontMainWindow;
- (void)showMainWindow;
- (void)updateMainWindowTitle;
- (void)setupFeedbackIfNeeded;
- (void)mainThreadMonitorStart;
- (int)CurrentQQUin;
- (int)CurrentWeixinUin;
- (id)CurrentUserName;
- (BOOL)OnHeadBeatCGIResponse:(id)arg1;
- (BOOL)GetHeartBeatRequestData:(id)arg1 reqCmdId:(int *)arg2 respCmdId:(int *)arg3;
- (BOOL)IsAuthOK;
- (BOOL)MakeSureAuth;
- (void)onSessionTimeout;
- (void)onAuthUpdateCert;
- (void)onAuthFaildForInvalidCGISessionID;
- (void)handleAuthFailedWithReason:(id)arg1 errorMsg:(id)arg2;
- (void)onAuthKickOutWithReason:(id)arg1 errorMsg:(id)arg2;
- (void)onAuthFaild:(id)arg1;
- (void)onAuthFaildWithWrongPasswordOrUsername;
- (void)onAuthAlphaVersion:(id)arg1;
- (void)onAuthKeyInfoInvalid:(id)arg1;
- (void)delayUpdateSessionGroupChat;
- (void)delayInitPanel;
- (void)createSearchCaches;
- (void)setupAuthServices;
- (void)securityReport;
- (void)updateCDNServerIP;
- (void)startSyncAndHeatbeat;
- (void)mainWindowOnAuth:(BOOL)arg1;
- (void)loadSessions;
- (void)doSomethingOnAuth;
- (void)FFAddRecvFavZZ:(BOOL)arg1;
- (void)onLoginAuthOK;
- (void)onPreAuthOKOfUser:(id)arg1;
- (void)setupSaveMessageOption;
- (void)performDelayCleanUpExtension;
- (void)onUserManualLogout;
- (void)onUserStopInit:(CDUnknownBlockType)arg1;
- (void)setupServices;
- (void)cleanServices;
- (void)cleanUI;
- (void)cleanProperties;
- (void)doSomethingWhenLogout;
- (void)doSomethingWhenAppEnterBackground;
- (void)doSomethindWhenAppEnterForeground;
- (void)applicationWillHide:(id)arg1;
- (BOOL)applicationShouldHandleReopen:(id)arg1 hasVisibleWindows:(BOOL)arg2;
- (void)applicationWillResignActive:(id)arg1;
- (void)applicationDidBecomeActive:(id)arg1;
- (void)applicationWillBecomeActive:(id)arg1;
- (void)doLogoutOnAppTerminate;
- (unsigned long long)applicationShouldTerminate:(id)arg1;
- (void)applicationDidFinishLaunching:(id)arg1;
- (void)setupCheckUpdateIfNeeded;
- (void)performSearchAction:(id)arg1;
- (void)setupDockItem;
- (void)setupMenubarIcon;
- (void)shareNotification:(id)arg1;
- (BOOL)isStopSyncToServer;
- (void)onWorkspaceWillSleep:(id)arg1;
- (void)onWorkspaceDidWake:(id)arg1;
- (void)screenDidUnlock:(id)arg1;
- (void)screenDidLock:(id)arg1;
- (void)onWorkspaceScreenDidWake:(id)arg1;
- (void)onWorkspaceScreenDidSleep:(id)arg1;
- (void)addObservers;
- (void)unregisterExtensions;
- (void)registerExtensions;
- (void)dealloc;
- (id)init;
- (void)showSettingsWindow:(id)arg1;
- (void)showProxySettingsWindow:(id)arg1;
- (void)showBetaWindow;
- (void)showWhatNewWindow;
- (void)uploadCov;
- (void)showLogReportWindow;
- (void)showFavDBEssentialInfo;
- (void)showUpgradeHistory;
- (void)showRecoverWindow;
- (void)showAutoRepairWindow;
- (void)showRepairWindow;
- (void)showTechSupport:(id)arg1;
- (void)showFeedBackWindow;
- (void)showJSConsoleWindow:(id)arg1;
- (void)showMemoryMonitorWindow;
- (void)showInfoWindow;
- (void)showAboutWindow:(id)arg1;
- (BOOL)isScreenSmallerThan13Inch;
- (id)mainWindowScreen;
- (struct CGRect)mainWindowScreenFrame;
- (BOOL)isMainWindowOcclused;
- (BOOL)isMainWindowVisible;
- (id)currentMainWindow;
- (BOOL)doUpgradeMigrationFromVersion:(unsigned int)arg1 toVersion:(unsigned int)arg2;
- (id)checkVersionFilePath;
- (void)saveToDiskWithVersion:(unsigned int)arg1;
- (unsigned int)checkVersionFromDisk;
- (void)doUpgradePreparationIfNeeded;
- (BOOL)isApplicationActive;
- (long long)applicationState;
- (void)previousTab:(id)arg1;
- (void)nextTab:(id)arg1;
- (void)showFavoritesTab:(id)arg1;
- (void)showContactsTab:(id)arg1;
- (void)showChatsTab:(id)arg1;
- (unsigned int)currentTab;
- (void)lock:(id)arg1;
- (void)pasteRevokMsgContent:(id)arg1;
- (void)pasteScreenshotToInputView:(id)arg1;
- (void)sendDragOperationToInputView:(id)arg1;
- (void)openFavoritesTabToFavoritesWithKeyWord:(id)arg1;
- (void)startANewGroupChatWithUserNames:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)startANewChatWithContact:(id)arg1;
- (void)selectChatWithUserName:(id)arg1;
- (void)showContactsTabWithUserName:(id)arg1;
- (void)goToNextUnreadChat:(id)arg1;
- (id)currentChatListViewController;
- (long long)chatLastSelectedRow;
- (id)currentSelectedUserName;
- (void)hideChatMemberListWithAnimated:(BOOL)arg1;
- (void)stopVoicePlayWhenSelectionChange;
- (void)orderFrontVoipWindow;
- (void)backupRecoverChatlog:(id)arg1;
- (void)orderFrontBackupWindow;
- (void)viewSourceForText:(id)arg1;
- (void)viewSourceForMessage:(id)arg1;
- (BOOL)shouldShowViewSourceTool;
- (BOOL)shouldShowDebugMessageLayoutGuides;
- (BOOL)releaseHasAutoupdate;
- (BOOL)releaseIsInternalTestBuild;
- (BOOL)releaseIsDebugBuild;
- (void)showFeatureMissingPlaceholderWithDescription:(id)arg1;
- (void)showFeatureMissingPlaceholder;
- (void)showDebugMenuIfNeeded;
- (void)_showNewXExprData:(id)arg1;
- (void)_showMiscOptions:(id)arg1;
- (void)_showIPSwitcher:(id)arg1;
- (void)_showChatLogDebug:(id)arg1;
- (void)_showNetDebugWindow:(id)arg1;
- (void)_showFavoritesDebug:(id)arg1;
- (void)_showIDKeyWindow:(id)arg1;
- (void)_showBenchmarkTool:(id)arg1;
- (void)_showLagMonitorDebug:(id)arg1;
- (void)_showReleaseNotesBlog:(id)arg1;
- (void)_openCacheFolder:(id)arg1;
- (void)_openCurrentDocument:(id)arg1;
- (void)_openCurrentSandbox:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

