//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSApplication.h"

@class NSMenuItem, VoiceOver;

@interface WeChatApplication : NSApplication
{
    NSMenuItem *_settingsMenuItem;
    VoiceOver *_status;
}

@property(retain, nonatomic) VoiceOver *status; // @synthesize status=_status;
@property(nonatomic) __weak NSMenuItem *settingsMenuItem; // @synthesize settingsMenuItem=_settingsMenuItem;
- (void).cxx_destruct;
- (unsigned char)isUndoMangerException:(id)arg1;
- (void)accessibilitySetValue:(id)arg1 forAttribute:(id)arg2;
- (BOOL)isVoiceOverRunning;
- (long long)requestUserAttention:(unsigned long long)arg1;
- (void)reportException:(id)arg1;

@end

