//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface WxamImageConvert : NSObject
{
}

+ (BOOL)decodeWxAmToPic:(id)arg1 wxamPath:(id)arg2 picType:(unsigned int)arg3;
+ (BOOL)decodeWxAmToPic:(id)arg1 wxamPath:(id)arg2;
+ (BOOL)isWxamFormat:(id)arg1;

@end

